-- Procurement & inventory (CM-502, `modules/06`): the
-- `construction_procurement` schema with every M5 table, so later M5
-- tickets add code, not tables. Touches no other schema (ADR-0030).
-- Product rules behind the columns: ADR CM-0015. The stock ledger
-- (`stock_entries`) is append-only (CM-0015 §5).
--
-- Generated by `prisma migrate diff`, then the CHECK constraints and
-- partial indexes Prisma cannot express.

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "construction_procurement";

-- CreateEnum
CREATE TYPE "construction_procurement"."approval_status" AS ENUM ('pending', 'approved', 'rejected');

-- CreateEnum
CREATE TYPE "construction_procurement"."location_kind" AS ENUM ('project', 'store');

-- CreateEnum
CREATE TYPE "construction_procurement"."document_type" AS ENUM ('purchase_request', 'purchase_order', 'goods_receipt', 'material_transfer', 'material_request', 'delivery_note');

-- CreateEnum
CREATE TYPE "construction_procurement"."discount_type" AS ENUM ('amount', 'percent');

-- CreateEnum
CREATE TYPE "construction_procurement"."supply_type" AS ENUM ('intra_state', 'inter_state');

-- CreateEnum
CREATE TYPE "construction_procurement"."purchase_request_source" AS ENUM ('manual', 'inventory');

-- CreateEnum
CREATE TYPE "construction_procurement"."order_status" AS ENUM ('not_ordered', 'partially_ordered', 'ordered', 'excess_ordered');

-- CreateEnum
CREATE TYPE "construction_procurement"."receipt_status" AS ENUM ('not_received', 'partially_received', 'received');

-- CreateEnum
CREATE TYPE "construction_procurement"."material_request_status" AS ENUM ('requested', 'partially_delivered', 'delivered', 'closed');

-- CreateEnum
CREATE TYPE "construction_procurement"."stock_entry_type" AS ENUM ('opening', 'received', 'transferred_in', 'transferred_out', 'issued', 'received_from_store', 'consumed', 'missing', 'adjustment');

-- CreateEnum
CREATE TYPE "construction_procurement"."stock_source" AS ENUM ('goods_receipt', 'material_transfer', 'delivery_note', 'stock_movement');

-- CreateEnum
CREATE TYPE "construction_procurement"."stock_movement_kind" AS ENUM ('opening', 'consumed', 'missing', 'adjustment');

-- CreateTable
CREATE TABLE "construction_procurement"."purchase_requests" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "project_id" UUID NOT NULL,
    "number" TEXT NOT NULL,
    "request_date" DATE NOT NULL,
    "required_date" DATE,
    "site_location_type" TEXT,
    "site_location" JSONB,
    "remark" TEXT,
    "separate_remarks" BOOLEAN NOT NULL DEFAULT false,
    "common_remark" TEXT,
    "source" "construction_procurement"."purchase_request_source" NOT NULL DEFAULT 'manual',
    "approval_status" "construction_procurement"."approval_status" NOT NULL DEFAULT 'pending',
    "decided_at" TIMESTAMPTZ(3),
    "decided_by" TEXT,
    "rejection_reason" TEXT,
    "order_status" "construction_procurement"."order_status" NOT NULL DEFAULT 'not_ordered',
    "marked_ordered_at" TIMESTAMPTZ(3),
    "marked_ordered_by" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "purchase_requests_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_procurement"."purchase_request_items" (
    "id" UUID NOT NULL,
    "purchase_request_id" UUID NOT NULL,
    "position" INTEGER NOT NULL,
    "material_id" UUID NOT NULL,
    "material_name" TEXT NOT NULL,
    "category_id" UUID,
    "uom_id" UUID NOT NULL,
    "uom_name" TEXT NOT NULL,
    "quantity" DECIMAL(14,3) NOT NULL,
    "remark" TEXT,
    "ordered_qty" DECIMAL(14,3) NOT NULL DEFAULT 0,

    CONSTRAINT "purchase_request_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_procurement"."purchase_orders" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "location_kind" "construction_procurement"."location_kind" NOT NULL,
    "location_id" UUID NOT NULL,
    "number" TEXT NOT NULL,
    "order_date" DATE NOT NULL,
    "expected_delivery_date" DATE NOT NULL,
    "purchase_request_id" UUID,
    "supplier_id" UUID NOT NULL,
    "supplier_name" TEXT NOT NULL,
    "supplier_gstin" VARCHAR(15),
    "supplier_state_code" CHAR(2),
    "site_location_type" TEXT,
    "site_location" JSONB,
    "supply_type" "construction_procurement"."supply_type" NOT NULL DEFAULT 'intra_state',
    "place_of_supply_state_code" CHAR(2),
    "billing_address_id" UUID NOT NULL,
    "billing_name" TEXT NOT NULL,
    "billing_address" TEXT NOT NULL,
    "billing_state_code" CHAR(2),
    "billing_gstin" VARCHAR(15),
    "supplier_poc_name" TEXT,
    "supplier_poc_mobile" TEXT,
    "site_poc_name" TEXT,
    "site_poc_mobile" TEXT,
    "payment_terms_days" INTEGER,
    "delivery_address_differs" BOOLEAN NOT NULL DEFAULT false,
    "delivery_address" TEXT,
    "delivery_state_code" CHAR(2),
    "remark" TEXT,
    "sub_total" BIGINT NOT NULL DEFAULT 0,
    "discount_total" BIGINT NOT NULL DEFAULT 0,
    "taxable_total" BIGINT NOT NULL DEFAULT 0,
    "cgst_total" BIGINT NOT NULL DEFAULT 0,
    "sgst_total" BIGINT NOT NULL DEFAULT 0,
    "igst_total" BIGINT NOT NULL DEFAULT 0,
    "items_total" BIGINT NOT NULL DEFAULT 0,
    "additional_charges" BIGINT NOT NULL DEFAULT 0,
    "deduction_amount" BIGINT NOT NULL DEFAULT 0,
    "grand_total" BIGINT NOT NULL DEFAULT 0,
    "approval_status" "construction_procurement"."approval_status" NOT NULL DEFAULT 'pending',
    "decided_at" TIMESTAMPTZ(3),
    "decided_by" TEXT,
    "rejection_reason" TEXT,
    "ordered_at" TIMESTAMPTZ(3),
    "ordered_by" TEXT,
    "receipt_status" "construction_procurement"."receipt_status" NOT NULL DEFAULT 'not_received',
    "closed_at" TIMESTAMPTZ(3),
    "closed_by" TEXT,
    "close_reason" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "purchase_orders_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_procurement"."purchase_order_items" (
    "id" UUID NOT NULL,
    "purchase_order_id" UUID NOT NULL,
    "purchase_request_item_id" UUID,
    "position" INTEGER NOT NULL,
    "material_id" UUID NOT NULL,
    "material_name" TEXT NOT NULL,
    "uom_id" UUID NOT NULL,
    "uom_name" TEXT NOT NULL,
    "hsn_code" VARCHAR(8),
    "quantity" DECIMAL(14,3) NOT NULL,
    "unit_rate" BIGINT NOT NULL,
    "discount_type" "construction_procurement"."discount_type",
    "discount_percent" DECIMAL(5,2),
    "discount_amount" BIGINT NOT NULL DEFAULT 0,
    "gst_rate" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "sub_total" BIGINT NOT NULL,
    "taxable" BIGINT NOT NULL,
    "cgst" BIGINT NOT NULL DEFAULT 0,
    "sgst" BIGINT NOT NULL DEFAULT 0,
    "igst" BIGINT NOT NULL DEFAULT 0,
    "total" BIGINT NOT NULL,
    "remark" TEXT,
    "received_qty" DECIMAL(14,3) NOT NULL DEFAULT 0,

    CONSTRAINT "purchase_order_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_procurement"."purchase_order_terms" (
    "id" UUID NOT NULL,
    "purchase_order_id" UUID NOT NULL,
    "position" INTEGER NOT NULL,
    "terms_id" UUID,
    "title" TEXT NOT NULL,
    "body" TEXT NOT NULL,

    CONSTRAINT "purchase_order_terms_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_procurement"."goods_receipts" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "location_kind" "construction_procurement"."location_kind" NOT NULL,
    "location_id" UUID NOT NULL,
    "number" TEXT NOT NULL,
    "receipt_date" DATE NOT NULL,
    "inventory_date" DATE NOT NULL,
    "supplier_id" UUID NOT NULL,
    "supplier_name" TEXT NOT NULL,
    "purchase_order_id" UUID,
    "supply_type" "construction_procurement"."supply_type" NOT NULL DEFAULT 'intra_state',
    "invoice_no" TEXT,
    "invoice_date" DATE,
    "invoice_amount" BIGINT,
    "delivery_challan_no" TEXT,
    "grn_dc_no" TEXT,
    "vehicle_no" TEXT,
    "driver_name" TEXT,
    "driver_mobile" TEXT,
    "eway_bill_no" TEXT,
    "remark" TEXT,
    "taxable_total" BIGINT NOT NULL DEFAULT 0,
    "cgst_total" BIGINT NOT NULL DEFAULT 0,
    "sgst_total" BIGINT NOT NULL DEFAULT 0,
    "igst_total" BIGINT NOT NULL DEFAULT 0,
    "total_value" BIGINT NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "goods_receipts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_procurement"."goods_receipt_items" (
    "id" UUID NOT NULL,
    "goods_receipt_id" UUID NOT NULL,
    "purchase_order_item_id" UUID,
    "position" INTEGER NOT NULL,
    "material_id" UUID NOT NULL,
    "material_name" TEXT NOT NULL,
    "uom_id" UUID NOT NULL,
    "uom_name" TEXT NOT NULL,
    "hsn_code" VARCHAR(8),
    "received_qty" DECIMAL(14,3) NOT NULL,
    "unit_rate" BIGINT NOT NULL,
    "gst_rate" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "taxable" BIGINT NOT NULL,
    "cgst" BIGINT NOT NULL DEFAULT 0,
    "sgst" BIGINT NOT NULL DEFAULT 0,
    "igst" BIGINT NOT NULL DEFAULT 0,
    "total" BIGINT NOT NULL,

    CONSTRAINT "goods_receipt_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_procurement"."stock_settings" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "location_kind" "construction_procurement"."location_kind" NOT NULL,
    "location_id" UUID NOT NULL,
    "material_id" UUID NOT NULL,
    "estimated_qty" DECIMAL(14,3),
    "min_stock_qty" DECIMAL(14,3),
    "min_alert_enabled" BOOLEAN NOT NULL DEFAULT false,
    "below_minimum" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,

    CONSTRAINT "stock_settings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_procurement"."stock_entries" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "location_kind" "construction_procurement"."location_kind" NOT NULL,
    "location_id" UUID NOT NULL,
    "material_id" UUID NOT NULL,
    "entry_date" DATE NOT NULL,
    "type" "construction_procurement"."stock_entry_type" NOT NULL,
    "quantity" DECIMAL(14,3) NOT NULL,
    "unit_rate" BIGINT,
    "source_type" "construction_procurement"."stock_source" NOT NULL,
    "source_id" UUID NOT NULL,
    "source_line_id" UUID,
    "counterparty_label" TEXT,
    "site_location_type" TEXT,
    "site_location" JSONB,
    "remark" TEXT,
    "reverses_entry_id" UUID,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,

    CONSTRAINT "stock_entries_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_procurement"."stock_movements" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "location_kind" "construction_procurement"."location_kind" NOT NULL,
    "location_id" UUID NOT NULL,
    "kind" "construction_procurement"."stock_movement_kind" NOT NULL,
    "movement_date" DATE NOT NULL,
    "material_id" UUID NOT NULL,
    "quantity" DECIMAL(14,3) NOT NULL,
    "site_location_type" TEXT,
    "site_location" JSONB,
    "remark" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "stock_movements_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_procurement"."material_transfers" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "number" TEXT NOT NULL,
    "transfer_date" DATE NOT NULL,
    "from_kind" "construction_procurement"."location_kind" NOT NULL,
    "from_id" UUID NOT NULL,
    "to_kind" "construction_procurement"."location_kind" NOT NULL,
    "to_id" UUID NOT NULL,
    "receiver_name" TEXT,
    "remark" TEXT,
    "approval_status" "construction_procurement"."approval_status" NOT NULL DEFAULT 'pending',
    "decided_at" TIMESTAMPTZ(3),
    "decided_by" TEXT,
    "rejection_reason" TEXT,
    "delivered_on" DATE,
    "delivered_at" TIMESTAMPTZ(3),
    "delivered_by" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "material_transfers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_procurement"."material_transfer_items" (
    "id" UUID NOT NULL,
    "material_transfer_id" UUID NOT NULL,
    "position" INTEGER NOT NULL,
    "material_id" UUID NOT NULL,
    "material_name" TEXT NOT NULL,
    "uom_id" UUID NOT NULL,
    "uom_name" TEXT NOT NULL,
    "quantity" DECIMAL(14,3) NOT NULL,
    "remark" TEXT,

    CONSTRAINT "material_transfer_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_procurement"."stores" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "address" TEXT,
    "state_code" CHAR(2),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "stores_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_procurement"."store_projects" (
    "store_id" UUID NOT NULL,
    "project_id" UUID NOT NULL,

    CONSTRAINT "store_projects_pkey" PRIMARY KEY ("store_id","project_id")
);

-- CreateTable
CREATE TABLE "construction_procurement"."store_keepers" (
    "store_id" UUID NOT NULL,
    "team_member_id" UUID NOT NULL,

    CONSTRAINT "store_keepers_pkey" PRIMARY KEY ("store_id","team_member_id")
);

-- CreateTable
CREATE TABLE "construction_procurement"."store_suppliers" (
    "store_id" UUID NOT NULL,
    "supplier_id" UUID NOT NULL,

    CONSTRAINT "store_suppliers_pkey" PRIMARY KEY ("store_id","supplier_id")
);

-- CreateTable
CREATE TABLE "construction_procurement"."material_requests" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "project_id" UUID NOT NULL,
    "store_id" UUID NOT NULL,
    "number" TEXT NOT NULL,
    "request_date" DATE NOT NULL,
    "contractor_id" UUID,
    "department_id" UUID,
    "site_location_type" TEXT,
    "site_location" JSONB,
    "receiver_name" TEXT,
    "remark" TEXT,
    "status" "construction_procurement"."material_request_status" NOT NULL DEFAULT 'requested',
    "closed_at" TIMESTAMPTZ(3),
    "closed_by" TEXT,
    "close_reason" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "material_requests_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_procurement"."material_request_items" (
    "id" UUID NOT NULL,
    "material_request_id" UUID NOT NULL,
    "position" INTEGER NOT NULL,
    "material_id" UUID NOT NULL,
    "material_name" TEXT NOT NULL,
    "uom_id" UUID NOT NULL,
    "uom_name" TEXT NOT NULL,
    "ask_qty" DECIMAL(14,3) NOT NULL,
    "delivered_qty" DECIMAL(14,3) NOT NULL DEFAULT 0,
    "remark" TEXT,

    CONSTRAINT "material_request_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_procurement"."delivery_notes" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "number" TEXT NOT NULL,
    "material_request_id" UUID NOT NULL,
    "store_id" UUID NOT NULL,
    "project_id" UUID NOT NULL,
    "delivery_date" DATE NOT NULL,
    "delivered_to" TEXT,
    "remark" TEXT,
    "approval_status" "construction_procurement"."approval_status" NOT NULL DEFAULT 'pending',
    "decided_at" TIMESTAMPTZ(3),
    "decided_by" TEXT,
    "delivered_on" DATE,
    "delivered_at" TIMESTAMPTZ(3),
    "delivered_by" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "delivery_notes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_procurement"."delivery_note_items" (
    "id" UUID NOT NULL,
    "delivery_note_id" UUID NOT NULL,
    "material_request_item_id" UUID NOT NULL,
    "position" INTEGER NOT NULL,
    "material_id" UUID NOT NULL,
    "material_name" TEXT NOT NULL,
    "uom_id" UUID NOT NULL,
    "uom_name" TEXT NOT NULL,
    "quantity" DECIMAL(14,3) NOT NULL,

    CONSTRAINT "delivery_note_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_procurement"."remarks" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "document_type" "construction_procurement"."document_type" NOT NULL,
    "document_id" UUID NOT NULL,
    "body" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,

    CONSTRAINT "remarks_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_procurement"."document_files" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "document_type" "construction_procurement"."document_type" NOT NULL,
    "document_id" UUID NOT NULL,
    "remark_id" UUID,
    "file_key" TEXT NOT NULL,
    "file_name" TEXT NOT NULL,
    "content_type" TEXT NOT NULL,
    "bytes" INTEGER NOT NULL,
    "thumb_key" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "document_files_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "purchase_requests_workspace_id_project_id_created_at_idx" ON "construction_procurement"."purchase_requests"("workspace_id", "project_id", "created_at");

-- CreateIndex
CREATE INDEX "purchase_requests_workspace_id_project_id_approval_status_idx" ON "construction_procurement"."purchase_requests"("workspace_id", "project_id", "approval_status");

-- CreateIndex
CREATE UNIQUE INDEX "purchase_requests_workspace_id_number_key" ON "construction_procurement"."purchase_requests"("workspace_id", "number");

-- CreateIndex
CREATE INDEX "purchase_request_items_purchase_request_id_idx" ON "construction_procurement"."purchase_request_items"("purchase_request_id");

-- CreateIndex
CREATE INDEX "purchase_request_items_material_id_idx" ON "construction_procurement"."purchase_request_items"("material_id");

-- CreateIndex
CREATE INDEX "purchase_orders_workspace_id_location_kind_location_id_crea_idx" ON "construction_procurement"."purchase_orders"("workspace_id", "location_kind", "location_id", "created_at");

-- CreateIndex
CREATE INDEX "purchase_orders_workspace_id_supplier_id_idx" ON "construction_procurement"."purchase_orders"("workspace_id", "supplier_id");

-- CreateIndex
CREATE INDEX "purchase_orders_purchase_request_id_idx" ON "construction_procurement"."purchase_orders"("purchase_request_id");

-- CreateIndex
CREATE UNIQUE INDEX "purchase_orders_workspace_id_number_key" ON "construction_procurement"."purchase_orders"("workspace_id", "number");

-- CreateIndex
CREATE INDEX "purchase_order_items_purchase_order_id_idx" ON "construction_procurement"."purchase_order_items"("purchase_order_id");

-- CreateIndex
CREATE INDEX "purchase_order_items_purchase_request_item_id_idx" ON "construction_procurement"."purchase_order_items"("purchase_request_item_id");

-- CreateIndex
CREATE INDEX "purchase_order_items_material_id_idx" ON "construction_procurement"."purchase_order_items"("material_id");

-- CreateIndex
CREATE INDEX "purchase_order_terms_purchase_order_id_idx" ON "construction_procurement"."purchase_order_terms"("purchase_order_id");

-- CreateIndex
CREATE INDEX "goods_receipts_workspace_id_location_kind_location_id_creat_idx" ON "construction_procurement"."goods_receipts"("workspace_id", "location_kind", "location_id", "created_at");

-- CreateIndex
CREATE INDEX "goods_receipts_workspace_id_supplier_id_idx" ON "construction_procurement"."goods_receipts"("workspace_id", "supplier_id");

-- CreateIndex
CREATE INDEX "goods_receipts_purchase_order_id_idx" ON "construction_procurement"."goods_receipts"("purchase_order_id");

-- CreateIndex
CREATE UNIQUE INDEX "goods_receipts_workspace_id_number_key" ON "construction_procurement"."goods_receipts"("workspace_id", "number");

-- CreateIndex
CREATE INDEX "goods_receipt_items_goods_receipt_id_idx" ON "construction_procurement"."goods_receipt_items"("goods_receipt_id");

-- CreateIndex
CREATE INDEX "goods_receipt_items_purchase_order_item_id_idx" ON "construction_procurement"."goods_receipt_items"("purchase_order_item_id");

-- CreateIndex
CREATE UNIQUE INDEX "stock_settings_workspace_id_location_kind_location_id_mater_key" ON "construction_procurement"."stock_settings"("workspace_id", "location_kind", "location_id", "material_id");

-- CreateIndex
CREATE UNIQUE INDEX "stock_entries_reverses_entry_id_key" ON "construction_procurement"."stock_entries"("reverses_entry_id");

-- CreateIndex
CREATE INDEX "stock_entries_workspace_id_location_kind_location_id_materi_idx" ON "construction_procurement"."stock_entries"("workspace_id", "location_kind", "location_id", "material_id", "entry_date");

-- CreateIndex
CREATE INDEX "stock_entries_workspace_id_material_id_entry_date_idx" ON "construction_procurement"."stock_entries"("workspace_id", "material_id", "entry_date");

-- CreateIndex
CREATE INDEX "stock_entries_source_type_source_id_idx" ON "construction_procurement"."stock_entries"("source_type", "source_id");

-- CreateIndex
CREATE INDEX "stock_movements_workspace_id_location_kind_location_id_move_idx" ON "construction_procurement"."stock_movements"("workspace_id", "location_kind", "location_id", "movement_date");

-- CreateIndex
CREATE INDEX "material_transfers_workspace_id_from_kind_from_id_created_a_idx" ON "construction_procurement"."material_transfers"("workspace_id", "from_kind", "from_id", "created_at");

-- CreateIndex
CREATE INDEX "material_transfers_workspace_id_to_kind_to_id_created_at_idx" ON "construction_procurement"."material_transfers"("workspace_id", "to_kind", "to_id", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "material_transfers_workspace_id_number_key" ON "construction_procurement"."material_transfers"("workspace_id", "number");

-- CreateIndex
CREATE INDEX "material_transfer_items_material_transfer_id_idx" ON "construction_procurement"."material_transfer_items"("material_transfer_id");

-- CreateIndex
CREATE INDEX "stores_workspace_id_name_idx" ON "construction_procurement"."stores"("workspace_id", "name");

-- CreateIndex
CREATE INDEX "store_projects_project_id_idx" ON "construction_procurement"."store_projects"("project_id");

-- CreateIndex
CREATE INDEX "store_keepers_team_member_id_idx" ON "construction_procurement"."store_keepers"("team_member_id");

-- CreateIndex
CREATE INDEX "store_suppliers_supplier_id_idx" ON "construction_procurement"."store_suppliers"("supplier_id");

-- CreateIndex
CREATE INDEX "material_requests_workspace_id_project_id_created_at_idx" ON "construction_procurement"."material_requests"("workspace_id", "project_id", "created_at");

-- CreateIndex
CREATE INDEX "material_requests_workspace_id_store_id_created_at_idx" ON "construction_procurement"."material_requests"("workspace_id", "store_id", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "material_requests_workspace_id_number_key" ON "construction_procurement"."material_requests"("workspace_id", "number");

-- CreateIndex
CREATE INDEX "material_request_items_material_request_id_idx" ON "construction_procurement"."material_request_items"("material_request_id");

-- CreateIndex
CREATE INDEX "delivery_notes_workspace_id_store_id_created_at_idx" ON "construction_procurement"."delivery_notes"("workspace_id", "store_id", "created_at");

-- CreateIndex
CREATE INDEX "delivery_notes_material_request_id_idx" ON "construction_procurement"."delivery_notes"("material_request_id");

-- CreateIndex
CREATE UNIQUE INDEX "delivery_notes_workspace_id_number_key" ON "construction_procurement"."delivery_notes"("workspace_id", "number");

-- CreateIndex
CREATE INDEX "delivery_note_items_delivery_note_id_idx" ON "construction_procurement"."delivery_note_items"("delivery_note_id");

-- CreateIndex
CREATE INDEX "delivery_note_items_material_request_item_id_idx" ON "construction_procurement"."delivery_note_items"("material_request_item_id");

-- CreateIndex
CREATE INDEX "remarks_workspace_id_document_type_document_id_created_at_idx" ON "construction_procurement"."remarks"("workspace_id", "document_type", "document_id", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "document_files_file_key_key" ON "construction_procurement"."document_files"("file_key");

-- CreateIndex
CREATE INDEX "document_files_workspace_id_document_type_document_id_delet_idx" ON "construction_procurement"."document_files"("workspace_id", "document_type", "document_id", "deleted_at");

-- AddForeignKey
ALTER TABLE "construction_procurement"."purchase_request_items" ADD CONSTRAINT "purchase_request_items_purchase_request_id_fkey" FOREIGN KEY ("purchase_request_id") REFERENCES "construction_procurement"."purchase_requests"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_procurement"."purchase_order_items" ADD CONSTRAINT "purchase_order_items_purchase_order_id_fkey" FOREIGN KEY ("purchase_order_id") REFERENCES "construction_procurement"."purchase_orders"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_procurement"."purchase_order_items" ADD CONSTRAINT "purchase_order_items_purchase_request_item_id_fkey" FOREIGN KEY ("purchase_request_item_id") REFERENCES "construction_procurement"."purchase_request_items"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_procurement"."purchase_order_terms" ADD CONSTRAINT "purchase_order_terms_purchase_order_id_fkey" FOREIGN KEY ("purchase_order_id") REFERENCES "construction_procurement"."purchase_orders"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_procurement"."goods_receipt_items" ADD CONSTRAINT "goods_receipt_items_goods_receipt_id_fkey" FOREIGN KEY ("goods_receipt_id") REFERENCES "construction_procurement"."goods_receipts"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_procurement"."material_transfer_items" ADD CONSTRAINT "material_transfer_items_material_transfer_id_fkey" FOREIGN KEY ("material_transfer_id") REFERENCES "construction_procurement"."material_transfers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_procurement"."store_projects" ADD CONSTRAINT "store_projects_store_id_fkey" FOREIGN KEY ("store_id") REFERENCES "construction_procurement"."stores"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_procurement"."store_keepers" ADD CONSTRAINT "store_keepers_store_id_fkey" FOREIGN KEY ("store_id") REFERENCES "construction_procurement"."stores"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_procurement"."store_suppliers" ADD CONSTRAINT "store_suppliers_store_id_fkey" FOREIGN KEY ("store_id") REFERENCES "construction_procurement"."stores"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_procurement"."material_request_items" ADD CONSTRAINT "material_request_items_material_request_id_fkey" FOREIGN KEY ("material_request_id") REFERENCES "construction_procurement"."material_requests"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_procurement"."delivery_notes" ADD CONSTRAINT "delivery_notes_material_request_id_fkey" FOREIGN KEY ("material_request_id") REFERENCES "construction_procurement"."material_requests"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_procurement"."delivery_note_items" ADD CONSTRAINT "delivery_note_items_delivery_note_id_fkey" FOREIGN KEY ("delivery_note_id") REFERENCES "construction_procurement"."delivery_notes"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_procurement"."delivery_note_items" ADD CONSTRAINT "delivery_note_items_material_request_item_id_fkey" FOREIGN KEY ("material_request_item_id") REFERENCES "construction_procurement"."material_request_items"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_procurement"."document_files" ADD CONSTRAINT "document_files_remark_id_fkey" FOREIGN KEY ("remark_id") REFERENCES "construction_procurement"."remarks"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Store names unique ignoring case among live rows.
CREATE UNIQUE INDEX "stores_live_name_key" ON "construction_procurement"."stores"("workspace_id", lower("name")) WHERE "deleted_at" IS NULL;

-- Line quantities are positive.
ALTER TABLE "construction_procurement"."purchase_request_items" ADD CONSTRAINT "purchase_request_items_quantity_check" CHECK ("quantity" > 0 AND "ordered_qty" >= 0);
ALTER TABLE "construction_procurement"."purchase_order_items" ADD CONSTRAINT "purchase_order_items_quantity_check" CHECK ("quantity" > 0 AND "unit_rate" >= 0 AND "received_qty" >= 0 AND "gst_rate" BETWEEN 0 AND 100);
ALTER TABLE "construction_procurement"."purchase_order_items" ADD CONSTRAINT "purchase_order_items_discount_check" CHECK (
  ("discount_type" IS NULL AND "discount_percent" IS NULL AND "discount_amount" = 0)
  OR ("discount_type" = 'percent' AND "discount_percent" BETWEEN 0 AND 100)
  OR ("discount_type" = 'amount' AND "discount_percent" IS NULL AND "discount_amount" >= 0)
);
ALTER TABLE "construction_procurement"."goods_receipt_items" ADD CONSTRAINT "goods_receipt_items_quantity_check" CHECK ("received_qty" > 0 AND "unit_rate" >= 0 AND "gst_rate" BETWEEN 0 AND 100);
ALTER TABLE "construction_procurement"."material_transfer_items" ADD CONSTRAINT "material_transfer_items_quantity_check" CHECK ("quantity" > 0);
ALTER TABLE "construction_procurement"."material_request_items" ADD CONSTRAINT "material_request_items_quantity_check" CHECK ("ask_qty" > 0 AND "delivered_qty" >= 0);
ALTER TABLE "construction_procurement"."delivery_note_items" ADD CONSTRAINT "delivery_note_items_quantity_check" CHECK ("quantity" > 0);

-- A transfer goes somewhere else.
ALTER TABLE "construction_procurement"."material_transfers" ADD CONSTRAINT "material_transfers_route_check" CHECK (NOT ("from_kind" = "to_kind" AND "from_id" = "to_id"));

-- Ledger entries move something; a hand-entered movement is positive except an adjustment.
ALTER TABLE "construction_procurement"."stock_entries" ADD CONSTRAINT "stock_entries_quantity_check" CHECK ("quantity" <> 0);
ALTER TABLE "construction_procurement"."stock_movements" ADD CONSTRAINT "stock_movements_quantity_check" CHECK ("quantity" <> 0 AND ("kind" = 'adjustment' OR "quantity" > 0));
ALTER TABLE "construction_procurement"."stock_settings" ADD CONSTRAINT "stock_settings_quantity_check" CHECK (("estimated_qty" IS NULL OR "estimated_qty" >= 0) AND ("min_stock_qty" IS NULL OR "min_stock_qty" >= 0));
