-- Procurement masters for M5 (CM-501, `modules/02`, ADR CM-0015 §1):
-- Measurement Units, Material Categories, Materials, Terms & Conditions and
-- party quotations; a GST state and a second contact on parties. Touches no
-- other schema (ADR-0030). Seed rows for existing Companies are a later
-- migration.
--
-- Generated by `prisma migrate diff`, then the partial unique indexes and
-- CHECK constraints Prisma cannot express.

-- CreateEnum
CREATE TYPE "construction_masters"."material_item_type" AS ENUM ('consumable', 'non_consumable', 'asset');

-- CreateEnum
CREATE TYPE "construction_masters"."discount_type" AS ENUM ('amount', 'percent');

-- CreateEnum
CREATE TYPE "construction_masters"."party_kind" AS ENUM ('contractor', 'supplier');

-- AlterTable
ALTER TABLE "construction_masters"."contractors" ADD COLUMN     "contact_person_2" TEXT,
ADD COLUMN     "mobile_2" TEXT,
ADD COLUMN     "state_code" CHAR(2);

-- AlterTable
ALTER TABLE "construction_masters"."suppliers" ADD COLUMN     "state_code" CHAR(2);

-- CreateTable
CREATE TABLE "construction_masters"."measurement_units" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "disabled_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "measurement_units_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_masters"."material_categories" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "parent_id" UUID,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "disabled_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "material_categories_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_masters"."materials" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "specification" TEXT,
    "uom_id" UUID NOT NULL,
    "category_id" UUID,
    "item_type" "construction_masters"."material_item_type" NOT NULL DEFAULT 'consumable',
    "unit_rate" BIGINT,
    "discount_type" "construction_masters"."discount_type",
    "discount_percent" DECIMAL(5,2),
    "discount_amount" BIGINT,
    "gst_rate" DECIMAL(5,2),
    "hsn_code" VARCHAR(8),
    "min_stock_qty" DECIMAL(14,3),
    "disabled_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "materials_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_masters"."terms_conditions" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "disabled_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "terms_conditions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_masters"."quotations" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "party_kind" "construction_masters"."party_kind" NOT NULL,
    "party_id" UUID NOT NULL,
    "file_key" TEXT NOT NULL,
    "file_name" TEXT NOT NULL,
    "content_type" TEXT NOT NULL,
    "bytes" INTEGER NOT NULL,
    "thumb_key" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "quotations_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "measurement_units_workspace_id_idx" ON "construction_masters"."measurement_units"("workspace_id");

-- CreateIndex
CREATE INDEX "material_categories_workspace_id_idx" ON "construction_masters"."material_categories"("workspace_id");

-- CreateIndex
CREATE INDEX "materials_workspace_id_name_idx" ON "construction_masters"."materials"("workspace_id", "name");

-- CreateIndex
CREATE INDEX "materials_category_id_idx" ON "construction_masters"."materials"("category_id");

-- CreateIndex
CREATE INDEX "terms_conditions_workspace_id_idx" ON "construction_masters"."terms_conditions"("workspace_id");

-- CreateIndex
CREATE UNIQUE INDEX "quotations_file_key_key" ON "construction_masters"."quotations"("file_key");

-- CreateIndex
CREATE INDEX "quotations_workspace_id_party_kind_party_id_deleted_at_idx" ON "construction_masters"."quotations"("workspace_id", "party_kind", "party_id", "deleted_at");

-- AddForeignKey
ALTER TABLE "construction_masters"."material_categories" ADD CONSTRAINT "material_categories_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "construction_masters"."material_categories"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_masters"."materials" ADD CONSTRAINT "materials_uom_id_fkey" FOREIGN KEY ("uom_id") REFERENCES "construction_masters"."measurement_units"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_masters"."materials" ADD CONSTRAINT "materials_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "construction_masters"."material_categories"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- Names unique ignoring case among live rows.
CREATE UNIQUE INDEX "measurement_units_live_name_key" ON "construction_masters"."measurement_units"("workspace_id", lower("name")) WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "material_categories_live_name_key" ON "construction_masters"."material_categories"("workspace_id", lower("name")) WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "materials_live_name_key" ON "construction_masters"."materials"("workspace_id", lower("name")) WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "terms_conditions_live_title_key" ON "construction_masters"."terms_conditions"("workspace_id", lower("title")) WHERE "deleted_at" IS NULL;

-- A discount is an amount or a percent, never both; rates and minimums are not negative.
ALTER TABLE "construction_masters"."materials" ADD CONSTRAINT "materials_discount_check" CHECK (
  ("discount_type" IS NULL AND "discount_percent" IS NULL AND "discount_amount" IS NULL)
  OR ("discount_type" = 'percent' AND "discount_percent" BETWEEN 0 AND 100 AND "discount_amount" IS NULL)
  OR ("discount_type" = 'amount' AND "discount_amount" >= 0 AND "discount_percent" IS NULL)
);
ALTER TABLE "construction_masters"."materials" ADD CONSTRAINT "materials_amounts_check" CHECK (
  ("unit_rate" IS NULL OR "unit_rate" >= 0)
  AND ("gst_rate" IS NULL OR "gst_rate" BETWEEN 0 AND 100)
  AND ("min_stock_qty" IS NULL OR "min_stock_qty" >= 0)
);
