import { StatusCodes } from "http-status-codes";
import { CalendarResponseModel } from "../calendar/calendar-response-model";
import {
  ClassDetailResponseModel,
  ClassParamsModel,
  ClassTokenResponseModel,
} from "../classes/class-models";

import { CloseBatchRequestModel } from "../batches/close-batch-request-model";
import { CloseBatchResponseModel } from "../batches/close-batch-response-model";
import { CreateBatchRequestModel } from "../batches/create-batch-request-model";
import { CreateBatchResponseModel } from "../batches/create-batch-response-model";
import { GetBatchRequestModel } from "../batches/get-batch-request-model";
import { GetBatchResponseModel } from "../batches/get-batch-response-model";
import { ListBatchesRequestModel } from "../batches/list-batches-request-model";
import { ListBatchesResponseModel } from "../batches/list-batches-response-model";
import { UpdateBatchScheduleParamsModel } from "../batches/update-batch-schedule-params-model";
import { UpdateBatchScheduleRequestModel } from "../batches/update-batch-schedule-request-model";
import { UpdateBatchScheduleResponseModel } from "../batches/update-batch-schedule-response-model";
import { CreateStudentRequestModel } from "../students/create-student-request-model";
import { CreateStudentResponseModel } from "../students/create-student-response-model";
import { DropStudentRequestModel } from "../students/drop-student-request-model";
import { DropStudentResponseModel } from "../students/drop-student-response-model";
import { GetStudentRequestModel } from "../students/get-student-request-model";
import { GetStudentResponseModel } from "../students/get-student-response-model";
import { ListStudentsRequestModel } from "../students/list-students-request-model";
import { ListStudentsResponseModel } from "../students/list-students-response-model";
import { UpdateStudentProfileParamsModel } from "../students/update-student-profile-params-model";
import { UpdateStudentProfileRequestModel } from "../students/update-student-profile-request-model";
import { UpdateStudentProfileResponseModel } from "../students/update-student-profile-response-model";
import { ArchiveCourseRequestModel } from "../courses/archive-course-request-model";
import { ArchiveCourseResponseModel } from "../courses/archive-course-response-model";
import { CreateCourseRequestModel } from "../courses/create-course-request-model";
import { CreateCourseResponseModel } from "../courses/create-course-response-model";
import { GetCourseRequestModel } from "../courses/get-course-request-model";
import { GetCourseResponseModel } from "../courses/get-course-response-model";
import { ListCoursesRequestModel } from "../courses/list-courses-request-model";
import { ListCoursesResponseModel } from "../courses/list-courses-response-model";
import { UpdateCourseParamsModel } from "../courses/update-course-params-model";
import { UpdateCourseRequestModel } from "../courses/update-course-request-model";
import { UpdateCourseResponseModel } from "../courses/update-course-response-model";
import { AdjustFeePlanParamsModel } from "../enrollments/adjust-fee-plan-params-model";
import { AdjustFeePlanRequestModel } from "../enrollments/adjust-fee-plan-request-model";
import { AdjustFeePlanResponseModel } from "../enrollments/adjust-fee-plan-response-model";
import { CreateEnrollmentRequestModel } from "../enrollments/create-enrollment-request-model";
import { CreateEnrollmentResponseModel } from "../enrollments/create-enrollment-response-model";
import { ListEnrollmentsRequestModel } from "../enrollments/list-enrollments-request-model";
import { ListEnrollmentsResponseModel } from "../enrollments/list-enrollments-response-model";
import { EndEnrollmentRequestModel } from "../enrollments/end-enrollment-request-model";
import { EndEnrollmentResponseModel } from "../enrollments/end-enrollment-response-model";
import { GetEnrollmentRequestModel } from "../enrollments/get-enrollment-request-model";
import { GetEnrollmentResponseModel } from "../enrollments/get-enrollment-response-model";
import { ListFeePaymentsParamsModel } from "../enrollments/list-fee-payments-params-model";
import { ListFeePaymentsRequestModel } from "../enrollments/list-fee-payments-request-model";
import { ListFeePaymentsResponseModel } from "../enrollments/list-fee-payments-response-model";
import { MoveEnrollmentParamsModel } from "../enrollments/move-enrollment-params-model";
import { MoveEnrollmentRequestModel } from "../enrollments/move-enrollment-request-model";
import { MoveEnrollmentResponseModel } from "../enrollments/move-enrollment-response-model";
import { OverrideEnrollmentModeParamsModel } from "../enrollments/override-enrollment-mode-params-model";
import { OverrideEnrollmentModeRequestModel } from "../enrollments/override-enrollment-mode-request-model";
import { OverrideEnrollmentModeResponseModel } from "../enrollments/override-enrollment-mode-response-model";
import { RecordFeePaymentParamsModel } from "../enrollments/record-fee-payment-params-model";
import { RecordFeePaymentRequestModel } from "../enrollments/record-fee-payment-request-model";
import { RecordFeePaymentResponseModel } from "../enrollments/record-fee-payment-response-model";
import { SetEnrollmentTimingsParamsModel } from "../enrollments/set-enrollment-timings-params-model";
import { SetEnrollmentTimingsRequestModel } from "../enrollments/set-enrollment-timings-request-model";
import { SetEnrollmentTimingsResponseModel } from "../enrollments/set-enrollment-timings-response-model";
import { GetOwnerDashboardResponseModel } from "../dashboard/get-owner-dashboard-response-model";
import { GetReceiptRequestModel } from "../payments/get-receipt-request-model";
import { GetReceiptResponseModel } from "../payments/get-receipt-response-model";
import { ActivateTeacherResponseModel } from "../teacher/activate/activate-teacher-response-model";
import { CreateTeacherRequestModel } from "../teachers/create-teacher-request-model";
import { ListTeachersRequestModel } from "../teachers/list-teachers-request-model";
import { ListTeachersResponseModel } from "../teachers/list-teachers-response-model";
import { TeacherResponseModel } from "../teachers/teacher-response-model";
import { TeacherParamsModel } from "../teachers/[id]/teacher-params-model";
import { UpdateTeacherProfileRequestModel } from "../teachers/[id]/profile/update-teacher-profile-request-model";
import {
  AddTeacherDocumentRequestModel,
  ListTeacherDocumentsResponseModel,
  RemoveTeacherDocumentResponseModel,
  TeacherDocumentMetadataModel,
  TeacherDocumentParamsModel,
} from "../teachers/[id]/documents/teacher-document-models";
import {
  AssignTeacherBatchRequestModel,
  TeacherBatchesResponseModel,
} from "../teachers/[id]/batches/assignment-models";
import { UnassignTeacherBatchParamsModel } from "../teachers/[id]/batches/[batchId]/unassign/unassign-teacher-batch-params-model";
import {
  AttendanceRegisterParamsModel,
  AttendanceRegisterResponseModel,
  ListAttendanceRegistersRequestModel,
  ListAttendanceRegistersResponseModel,
  OpenAttendanceRegisterRequestModel,
} from "../attendance/registers/attendance-models";
import { SaveAttendanceMarksRequestModel } from "../attendance/registers/[id]/marks/save-attendance-marks-request-model";
import {
  ListStudentAttendanceRequestModel,
  StudentAttendanceHistoryResponseModel,
  StudentAttendanceParamsModel,
} from "../students/[id]/attendance/student-attendance-models";
import { buildOpenApiDocument } from "./openapi";

export const openApiDocument = buildOpenApiDocument([
  {
    method: "get",
    path: "/api/calendar",
    summary: "View role-scoped recurring Batch Timings",
    tags: ["Calendar"],
    successStatus: StatusCodes.OK,
    successDescription: "Listed",
    successSchema: CalendarResponseModel,
    errors: [401, 403, 500],
  },
  {
    method: "get",
    path: "/api/classes/{batchId}/{date}/{startTime}",
    summary: "View a class before joining",
    tags: ["Classes"],
    params: ClassParamsModel,
    successStatus: StatusCodes.OK,
    successDescription: "Class",
    successSchema: ClassDetailResponseModel,
    errors: [400, 401, 403, 404, 500],
  },
  {
    method: "post",
    path: "/api/classes/{batchId}/{date}/{startTime}/start",
    summary: "Start a Whiteboard class as Owner or Teacher",
    tags: ["Classes"],
    params: ClassParamsModel,
    successStatus: StatusCodes.OK,
    successDescription: "Host token",
    successSchema: ClassTokenResponseModel,
    errors: [400, 401, 403, 404, 409, 503],
  },
  {
    method: "post",
    path: "/api/classes/{batchId}/{date}/{startTime}/join",
    summary: "Join a recorded Whiteboard class",
    tags: ["Classes"],
    params: ClassParamsModel,
    successStatus: StatusCodes.OK,
    successDescription: "Participant token",
    successSchema: ClassTokenResponseModel,
    errors: [400, 401, 403, 404, 409, 503],
  },
  {
    method: "get",
    path: "/api/classes/{batchId}/{date}/{startTime}/recording",
    summary: "Download a class recording",
    tags: ["Classes"],
    params: ClassParamsModel,
    successStatus: 302,
    successDescription: "Short-lived private R2 download redirect",
    errors: [400, 401, 403, 404, 409, 503],
  },
  {
    method: "post",
    path: "/api/webhooks/realtimekit",
    summary: "Receive signed RealtimeKit meeting and recording events",
    tags: ["Classes"],
    security: false,
    successStatus: StatusCodes.NO_CONTENT,
    successDescription: "Processed",
    errors: [400, 401, 503],
  },
  {
    method: "post",
    path: "/api/attendance/registers",
    summary: "Open a Batch Attendance Register for today or an earlier date",
    tags: ["Attendance"],
    body: OpenAttendanceRegisterRequestModel,
    successStatus: StatusCodes.CREATED,
    successDescription: "Opened",
    successSchema: AttendanceRegisterResponseModel,
    errors: [400, 401, 403, 404, 409, 500],
  },
  {
    method: "get",
    path: "/api/attendance/registers",
    summary: "List Batch Attendance Registers",
    tags: ["Attendance"],
    query: ListAttendanceRegistersRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Listed",
    successSchema: ListAttendanceRegistersResponseModel,
    errors: [400, 401, 403, 404, 500],
  },
  {
    method: "get",
    path: "/api/attendance/registers/{id}",
    summary: "Get an Attendance Register",
    tags: ["Attendance"],
    params: AttendanceRegisterParamsModel,
    successStatus: StatusCodes.OK,
    successDescription: "Found",
    successSchema: AttendanceRegisterResponseModel,
    errors: [400, 401, 403, 404, 500],
  },
  {
    method: "post",
    path: "/api/attendance/registers/{id}/marks",
    summary: "Mark or correct Attendance",
    tags: ["Attendance"],
    params: AttendanceRegisterParamsModel,
    body: SaveAttendanceMarksRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Saved",
    successSchema: AttendanceRegisterResponseModel,
    errors: [400, 401, 403, 404, 500],
  },
  {
    method: "get",
    path: "/api/students/{id}/attendance",
    summary: "Get Student Attendance history",
    tags: ["Attendance"],
    params: StudentAttendanceParamsModel,
    query: ListStudentAttendanceRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Listed",
    successSchema: StudentAttendanceHistoryResponseModel,
    errors: [400, 401, 403, 404, 500],
  },
  {
    method: "post",
    path: "/api/teachers",
    summary: "Add and invite a Teacher",
    tags: ["Teachers"],
    body: CreateTeacherRequestModel,
    successStatus: StatusCodes.CREATED,
    successDescription: "Created",
    successSchema: TeacherResponseModel,
    errors: [400, 401, 403, 409, 500],
  },
  {
    method: "get",
    path: "/api/teachers",
    summary: "List Teachers",
    tags: ["Teachers"],
    query: ListTeachersRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Listed",
    successSchema: ListTeachersResponseModel,
    errors: [400, 401, 403, 500],
  },
  {
    method: "get",
    path: "/api/teachers/{id}",
    summary: "Get a Teacher",
    tags: ["Teachers"],
    params: TeacherParamsModel,
    successStatus: StatusCodes.OK,
    successDescription: "Found",
    successSchema: TeacherResponseModel,
    errors: [400, 401, 403, 404, 500],
  },
  {
    method: "get",
    path: "/api/teachers/{id}/photo",
    summary: "Get a Teacher photo",
    tags: ["Teachers"],
    params: TeacherParamsModel,
    successStatus: StatusCodes.OK,
    successDescription: "Photo",
    successBinaryContentTypes: ["image/jpeg", "image/png", "image/webp"],
    errors: [400, 401, 403, 404, 500],
  },
  {
    method: "post",
    path: "/api/teachers/{id}/profile",
    summary: "Update Teacher profile",
    tags: ["Teachers"],
    params: TeacherParamsModel,
    body: UpdateTeacherProfileRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Updated",
    successSchema: TeacherResponseModel,
    errors: [400, 401, 403, 404, 409, 500],
  },
  {
    method: "get",
    path: "/api/teachers/{id}/documents",
    summary: "List private Teacher documents",
    tags: ["Teachers"],
    params: TeacherParamsModel,
    successStatus: StatusCodes.OK,
    successDescription: "Listed",
    successSchema: ListTeacherDocumentsResponseModel,
    errors: [400, 401, 403, 404, 500],
  },
  {
    method: "post",
    path: "/api/teachers/{id}/documents",
    summary: "Add a private Teacher document",
    tags: ["Teachers"],
    params: TeacherParamsModel,
    body: AddTeacherDocumentRequestModel,
    successStatus: StatusCodes.CREATED,
    successDescription: "Created",
    successSchema: TeacherDocumentMetadataModel,
    errors: [400, 401, 403, 404, 409, 500],
  },
  {
    method: "get",
    path: "/api/teachers/{id}/documents/{documentId}",
    summary: "Download a private Teacher document",
    tags: ["Teachers"],
    params: TeacherDocumentParamsModel,
    successStatus: StatusCodes.OK,
    successDescription: "Document",
    successBinaryContentTypes: ["application/pdf", "image/jpeg", "image/png"],
    errors: [400, 401, 403, 404, 500],
  },
  {
    method: "post",
    path: "/api/teachers/{id}/documents/{documentId}/remove",
    summary: "Remove a private Teacher document",
    tags: ["Teachers"],
    params: TeacherDocumentParamsModel,
    successStatus: StatusCodes.OK,
    successDescription: "Removed",
    successSchema: RemoveTeacherDocumentResponseModel,
    errors: [400, 401, 403, 404, 500],
  },
  {
    method: "post",
    path: "/api/teachers/{id}/invite",
    summary: "Resend Teacher invitation",
    tags: ["Teachers"],
    params: TeacherParamsModel,
    successStatus: StatusCodes.OK,
    successDescription: "Updated",
    successSchema: TeacherResponseModel,
    errors: [400, 401, 403, 404, 409, 500],
  },
  {
    method: "post",
    path: "/api/teachers/{id}/deactivate",
    summary: "Deactivate Teacher",
    tags: ["Teachers"],
    params: TeacherParamsModel,
    successStatus: StatusCodes.OK,
    successDescription: "Updated",
    successSchema: TeacherResponseModel,
    errors: [400, 401, 403, 404, 409, 500],
  },
  {
    method: "get",
    path: "/api/teachers/{id}/batches",
    summary: "List Teacher Batches",
    tags: ["Teachers"],
    params: TeacherParamsModel,
    successStatus: StatusCodes.OK,
    successDescription: "Listed",
    successSchema: TeacherBatchesResponseModel,
    errors: [400, 401, 403, 404, 500],
  },
  {
    method: "post",
    path: "/api/teachers/{id}/batches",
    summary: "Assign Teacher to Batch",
    tags: ["Teachers"],
    params: TeacherParamsModel,
    body: AssignTeacherBatchRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Assigned",
    successSchema: TeacherBatchesResponseModel,
    errors: [400, 401, 403, 404, 409, 500],
  },
  {
    method: "post",
    path: "/api/teachers/{id}/batches/{batchId}/unassign",
    summary: "Unassign Teacher from Batch",
    tags: ["Teachers"],
    params: UnassignTeacherBatchParamsModel,
    successStatus: StatusCodes.OK,
    successDescription: "Unassigned",
    successSchema: TeacherBatchesResponseModel,
    errors: [400, 401, 403, 404, 409, 500],
  },
  {
    method: "post",
    path: "/api/teacher/activate",
    summary: "Activate Teacher membership link",
    tags: ["Teachers"],
    successStatus: StatusCodes.OK,
    successDescription: "Activated",
    successSchema: ActivateTeacherResponseModel,
    errors: [401, 403, 404, 409, 500],
  },
  {
    method: "get",
    path: "/api/teacher/batches",
    summary: "List My Batches",
    tags: ["Teachers"],
    successStatus: StatusCodes.OK,
    successDescription: "Listed",
    successSchema: TeacherBatchesResponseModel,
    errors: [401, 403, 404, 500],
  },
  {
    method: "post",
    path: "/api/students",
    summary: "Admit a Student",
    tags: ["Students"],
    body: CreateStudentRequestModel,
    successStatus: StatusCodes.CREATED,
    successDescription: "Created",
    successSchema: CreateStudentResponseModel,
    errors: [
      StatusCodes.BAD_REQUEST,
      StatusCodes.UNAUTHORIZED,
      StatusCodes.FORBIDDEN,
      StatusCodes.CONFLICT,
      StatusCodes.INTERNAL_SERVER_ERROR,
    ],
  },
  {
    method: "get",
    path: "/api/students",
    summary: "List Students in the Active Workspace",
    tags: ["Students"],
    query: ListStudentsRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Listed",
    successSchema: ListStudentsResponseModel,
    errors: [
      StatusCodes.BAD_REQUEST,
      StatusCodes.UNAUTHORIZED,
      StatusCodes.FORBIDDEN,
      StatusCodes.INTERNAL_SERVER_ERROR,
    ],
  },
  {
    method: "get",
    path: "/api/students/{id}",
    summary: "Get a Student",
    tags: ["Students"],
    params: GetStudentRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Found",
    successSchema: GetStudentResponseModel,
    errors: [
      StatusCodes.BAD_REQUEST,
      StatusCodes.UNAUTHORIZED,
      StatusCodes.FORBIDDEN,
      StatusCodes.NOT_FOUND,
      StatusCodes.INTERNAL_SERVER_ERROR,
    ],
  },
  {
    method: "post",
    path: "/api/students/{id}/profile",
    summary: "Update a Student profile",
    tags: ["Students"],
    params: UpdateStudentProfileParamsModel,
    body: UpdateStudentProfileRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Updated",
    successSchema: UpdateStudentProfileResponseModel,
    errors: [
      StatusCodes.BAD_REQUEST,
      StatusCodes.UNAUTHORIZED,
      StatusCodes.FORBIDDEN,
      StatusCodes.NOT_FOUND,
      StatusCodes.INTERNAL_SERVER_ERROR,
    ],
  },
  {
    method: "post",
    path: "/api/students/{id}/drop",
    summary: "Drop a Student",
    tags: ["Students"],
    params: DropStudentRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Dropped",
    successSchema: DropStudentResponseModel,
    errors: [
      StatusCodes.BAD_REQUEST,
      StatusCodes.UNAUTHORIZED,
      StatusCodes.FORBIDDEN,
      StatusCodes.NOT_FOUND,
      StatusCodes.CONFLICT,
      StatusCodes.INTERNAL_SERVER_ERROR,
    ],
  },
  {
    method: "post",
    path: "/api/courses",
    summary: "Create a Course",
    tags: ["Courses"],
    body: CreateCourseRequestModel,
    successStatus: StatusCodes.CREATED,
    successDescription: "Created",
    successSchema: CreateCourseResponseModel,
    errors: [
      StatusCodes.BAD_REQUEST,
      StatusCodes.UNAUTHORIZED,
      StatusCodes.FORBIDDEN,
      StatusCodes.INTERNAL_SERVER_ERROR,
    ],
  },
  {
    method: "get",
    path: "/api/courses",
    summary: "List Courses in the Active Workspace",
    tags: ["Courses"],
    query: ListCoursesRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Listed",
    successSchema: ListCoursesResponseModel,
    errors: [
      StatusCodes.BAD_REQUEST,
      StatusCodes.UNAUTHORIZED,
      StatusCodes.FORBIDDEN,
      StatusCodes.INTERNAL_SERVER_ERROR,
    ],
  },
  {
    method: "get",
    path: "/api/courses/{id}",
    summary: "Get a Course",
    tags: ["Courses"],
    params: GetCourseRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Found",
    successSchema: GetCourseResponseModel,
    errors: [
      StatusCodes.BAD_REQUEST,
      StatusCodes.UNAUTHORIZED,
      StatusCodes.FORBIDDEN,
      StatusCodes.NOT_FOUND,
      StatusCodes.INTERNAL_SERVER_ERROR,
    ],
  },
  {
    method: "post",
    path: "/api/courses/{id}/update",
    summary: "Update a Course",
    tags: ["Courses"],
    params: UpdateCourseParamsModel,
    body: UpdateCourseRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Updated",
    successSchema: UpdateCourseResponseModel,
    errors: [
      StatusCodes.BAD_REQUEST,
      StatusCodes.UNAUTHORIZED,
      StatusCodes.FORBIDDEN,
      StatusCodes.NOT_FOUND,
      StatusCodes.INTERNAL_SERVER_ERROR,
    ],
  },
  {
    method: "post",
    path: "/api/courses/{id}/archive",
    summary: "Archive a Course",
    tags: ["Courses"],
    params: ArchiveCourseRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Archived",
    successSchema: ArchiveCourseResponseModel,
    errors: [
      StatusCodes.BAD_REQUEST,
      StatusCodes.UNAUTHORIZED,
      StatusCodes.FORBIDDEN,
      StatusCodes.NOT_FOUND,
      StatusCodes.CONFLICT,
      StatusCodes.INTERNAL_SERVER_ERROR,
    ],
  },
  {
    method: "post",
    path: "/api/batches",
    summary: "Create a Batch",
    tags: ["Batches"],
    body: CreateBatchRequestModel,
    successStatus: StatusCodes.CREATED,
    successDescription: "Created",
    successSchema: CreateBatchResponseModel,
    errors: [
      StatusCodes.BAD_REQUEST,
      StatusCodes.UNAUTHORIZED,
      StatusCodes.FORBIDDEN,
      StatusCodes.NOT_FOUND,
      StatusCodes.CONFLICT,
      StatusCodes.INTERNAL_SERVER_ERROR,
    ],
  },
  {
    method: "get",
    path: "/api/batches",
    summary: "List Batches in the Active Workspace",
    tags: ["Batches"],
    query: ListBatchesRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Listed",
    successSchema: ListBatchesResponseModel,
    errors: [
      StatusCodes.BAD_REQUEST,
      StatusCodes.UNAUTHORIZED,
      StatusCodes.FORBIDDEN,
      StatusCodes.INTERNAL_SERVER_ERROR,
    ],
  },
  {
    method: "get",
    path: "/api/batches/{id}",
    summary: "Get a Batch",
    tags: ["Batches"],
    params: GetBatchRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Found",
    successSchema: GetBatchResponseModel,
    errors: [
      StatusCodes.BAD_REQUEST,
      StatusCodes.UNAUTHORIZED,
      StatusCodes.FORBIDDEN,
      StatusCodes.NOT_FOUND,
      StatusCodes.INTERNAL_SERVER_ERROR,
    ],
  },
  {
    method: "post",
    path: "/api/batches/{id}/schedule",
    summary: "Update a Batch schedule",
    tags: ["Batches"],
    params: UpdateBatchScheduleParamsModel,
    body: UpdateBatchScheduleRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Updated",
    successSchema: UpdateBatchScheduleResponseModel,
    errors: [
      StatusCodes.BAD_REQUEST,
      StatusCodes.UNAUTHORIZED,
      StatusCodes.FORBIDDEN,
      StatusCodes.NOT_FOUND,
      StatusCodes.INTERNAL_SERVER_ERROR,
    ],
  },
  {
    method: "post",
    path: "/api/batches/{id}/close",
    summary: "Close a Batch",
    tags: ["Batches"],
    params: CloseBatchRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Closed",
    successSchema: CloseBatchResponseModel,
    errors: [
      StatusCodes.BAD_REQUEST,
      StatusCodes.UNAUTHORIZED,
      StatusCodes.FORBIDDEN,
      StatusCodes.NOT_FOUND,
      StatusCodes.CONFLICT,
      StatusCodes.INTERNAL_SERVER_ERROR,
    ],
  },
  {
    method: "post",
    path: "/api/enrollments",
    summary: "Enroll a Student in a Batch",
    tags: ["Enrollments"],
    body: CreateEnrollmentRequestModel,
    successStatus: StatusCodes.CREATED,
    successDescription: "Created",
    successSchema: CreateEnrollmentResponseModel,
    errors: [
      StatusCodes.BAD_REQUEST,
      StatusCodes.UNAUTHORIZED,
      StatusCodes.FORBIDDEN,
      StatusCodes.NOT_FOUND,
      StatusCodes.CONFLICT,
      StatusCodes.INTERNAL_SERVER_ERROR,
    ],
  },
  {
    method: "get",
    path: "/api/enrollments",
    summary: "List Enrollments in the Active Workspace",
    tags: ["Enrollments"],
    query: ListEnrollmentsRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Listed",
    successSchema: ListEnrollmentsResponseModel,
    errors: [
      StatusCodes.BAD_REQUEST,
      StatusCodes.UNAUTHORIZED,
      StatusCodes.FORBIDDEN,
      StatusCodes.INTERNAL_SERVER_ERROR,
    ],
  },
  {
    method: "get",
    path: "/api/enrollments/{id}",
    summary: "Get an Enrollment",
    tags: ["Enrollments"],
    params: GetEnrollmentRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Found",
    successSchema: GetEnrollmentResponseModel,
    errors: [
      StatusCodes.BAD_REQUEST,
      StatusCodes.UNAUTHORIZED,
      StatusCodes.FORBIDDEN,
      StatusCodes.NOT_FOUND,
      StatusCodes.INTERNAL_SERVER_ERROR,
    ],
  },
  {
    method: "post",
    path: "/api/enrollments/{id}/mode",
    summary: "Override Enrollment Class Mode",
    tags: ["Enrollments"],
    params: OverrideEnrollmentModeParamsModel,
    body: OverrideEnrollmentModeRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Updated",
    successSchema: OverrideEnrollmentModeResponseModel,
    errors: [
      StatusCodes.BAD_REQUEST,
      StatusCodes.UNAUTHORIZED,
      StatusCodes.FORBIDDEN,
      StatusCodes.NOT_FOUND,
      StatusCodes.CONFLICT,
      StatusCodes.INTERNAL_SERVER_ERROR,
    ],
  },
  {
    method: "post",
    path: "/api/enrollments/{id}/timings",
    summary: "Set Enrollment Timings",
    tags: ["Enrollments"],
    params: SetEnrollmentTimingsParamsModel,
    body: SetEnrollmentTimingsRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Updated",
    successSchema: SetEnrollmentTimingsResponseModel,
    errors: [
      StatusCodes.BAD_REQUEST,
      StatusCodes.UNAUTHORIZED,
      StatusCodes.FORBIDDEN,
      StatusCodes.NOT_FOUND,
      StatusCodes.CONFLICT,
      StatusCodes.INTERNAL_SERVER_ERROR,
    ],
  },
  {
    method: "post",
    path: "/api/enrollments/{id}/move",
    summary: "Move an Enrollment to another Batch",
    tags: ["Enrollments"],
    params: MoveEnrollmentParamsModel,
    body: MoveEnrollmentRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Moved",
    successSchema: MoveEnrollmentResponseModel,
    errors: [
      StatusCodes.BAD_REQUEST,
      StatusCodes.UNAUTHORIZED,
      StatusCodes.FORBIDDEN,
      StatusCodes.NOT_FOUND,
      StatusCodes.CONFLICT,
      StatusCodes.INTERNAL_SERVER_ERROR,
    ],
  },
  {
    method: "post",
    path: "/api/enrollments/{id}/end",
    summary: "End an Enrollment",
    tags: ["Enrollments"],
    params: EndEnrollmentRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Ended",
    successSchema: EndEnrollmentResponseModel,
    errors: [
      StatusCodes.BAD_REQUEST,
      StatusCodes.UNAUTHORIZED,
      StatusCodes.FORBIDDEN,
      StatusCodes.NOT_FOUND,
      StatusCodes.CONFLICT,
      StatusCodes.INTERNAL_SERVER_ERROR,
    ],
  },
  {
    method: "post",
    path: "/api/enrollments/{id}/fee-plan",
    summary: "Adjust the Fee Plan on an Enrollment",
    tags: ["Fees"],
    params: AdjustFeePlanParamsModel,
    body: AdjustFeePlanRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Updated",
    successSchema: AdjustFeePlanResponseModel,
    errors: [
      StatusCodes.BAD_REQUEST,
      StatusCodes.UNAUTHORIZED,
      StatusCodes.FORBIDDEN,
      StatusCodes.NOT_FOUND,
      StatusCodes.CONFLICT,
      StatusCodes.INTERNAL_SERVER_ERROR,
    ],
  },
  {
    method: "post",
    path: "/api/enrollments/{id}/payments",
    summary: "Record a Fee Payment",
    tags: ["Fees"],
    params: RecordFeePaymentParamsModel,
    body: RecordFeePaymentRequestModel,
    successStatus: StatusCodes.CREATED,
    successDescription: "Recorded",
    successSchema: RecordFeePaymentResponseModel,
    errors: [
      StatusCodes.BAD_REQUEST,
      StatusCodes.UNAUTHORIZED,
      StatusCodes.FORBIDDEN,
      StatusCodes.NOT_FOUND,
      StatusCodes.CONFLICT,
      StatusCodes.INTERNAL_SERVER_ERROR,
    ],
  },
  {
    method: "get",
    path: "/api/enrollments/{id}/payments",
    summary: "List Fee Payments for an Enrollment",
    tags: ["Fees"],
    params: ListFeePaymentsParamsModel,
    query: ListFeePaymentsRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Listed",
    successSchema: ListFeePaymentsResponseModel,
    errors: [
      StatusCodes.BAD_REQUEST,
      StatusCodes.UNAUTHORIZED,
      StatusCodes.FORBIDDEN,
      StatusCodes.NOT_FOUND,
      StatusCodes.INTERNAL_SERVER_ERROR,
    ],
  },
  {
    method: "get",
    path: "/api/payments/{id}/receipt",
    summary: "Get a Receipt",
    tags: ["Fees"],
    params: GetReceiptRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Found",
    successSchema: GetReceiptResponseModel,
    errors: [
      StatusCodes.BAD_REQUEST,
      StatusCodes.UNAUTHORIZED,
      StatusCodes.FORBIDDEN,
      StatusCodes.NOT_FOUND,
      StatusCodes.INTERNAL_SERVER_ERROR,
    ],
  },
  {
    method: "get",
    path: "/api/dashboard",
    summary: "Get the Owner Dashboard",
    tags: ["Dashboard"],
    successStatus: StatusCodes.OK,
    successDescription: "Found",
    successSchema: GetOwnerDashboardResponseModel,
    errors: [
      StatusCodes.UNAUTHORIZED,
      StatusCodes.FORBIDDEN,
      StatusCodes.INTERNAL_SERVER_ERROR,
    ],
  },
]);
