import { StatusCodes } from "http-status-codes";
import { TrainingInstituteCalendarResponseModel } from "../training-institute/calendar/calendar-response-model";
import {
  CancelTrainingInstituteClassRequestModel,
  TrainingInstituteClassChangeModel,
  MoveTrainingInstituteClassRequestModel,
} from "../training-institute/classes/class-change-models";
import {
  DeclareTrainingInstituteHolidayRequestModel,
  TrainingInstituteHolidayModel,
  TrainingInstituteHolidayParamsModel,
} from "../training-institute/holidays/holiday-models";
import {
  TrainingInstituteClassDetailResponseModel,
  TrainingInstituteClassParamsModel,
  TrainingInstituteClassTokenResponseModel,
} from "../training-institute/classes/class-models";

import { CloseTrainingInstituteBatchRequestModel } from "../training-institute/batches/close-batch-request-model";
import { CloseTrainingInstituteBatchResponseModel } from "../training-institute/batches/close-batch-response-model";
import { CreateTrainingInstituteBatchRequestModel } from "../training-institute/batches/create-batch-request-model";
import { CreateTrainingInstituteBatchResponseModel } from "../training-institute/batches/create-batch-response-model";
import { GetTrainingInstituteBatchRequestModel } from "../training-institute/batches/get-batch-request-model";
import { GetTrainingInstituteBatchResponseModel } from "../training-institute/batches/get-batch-response-model";
import { ListTrainingInstituteBatchesRequestModel } from "../training-institute/batches/list-batches-request-model";
import { ListTrainingInstituteBatchesResponseModel } from "../training-institute/batches/list-batches-response-model";
import { UpdateTrainingInstituteBatchScheduleParamsModel } from "../training-institute/batches/update-batch-schedule-params-model";
import { UpdateTrainingInstituteBatchScheduleRequestModel } from "../training-institute/batches/update-batch-schedule-request-model";
import { UpdateTrainingInstituteBatchScheduleResponseModel } from "../training-institute/batches/update-batch-schedule-response-model";
import { CreateTrainingInstituteStudentRequestModel } from "../training-institute/students/create-student-request-model";
import { CreateTrainingInstituteStudentResponseModel } from "../training-institute/students/create-student-response-model";
import { DropTrainingInstituteStudentRequestModel } from "../training-institute/students/drop-student-request-model";
import { DropTrainingInstituteStudentResponseModel } from "../training-institute/students/drop-student-response-model";
import { GetTrainingInstituteStudentRequestModel } from "../training-institute/students/get-student-request-model";
import { GetTrainingInstituteStudentResponseModel } from "../training-institute/students/get-student-response-model";
import { ListTrainingInstituteStudentsRequestModel } from "../training-institute/students/list-students-request-model";
import { ListTrainingInstituteStudentsResponseModel } from "../training-institute/students/list-students-response-model";
import { UpdateTrainingInstituteStudentProfileParamsModel } from "../training-institute/students/update-student-profile-params-model";
import { UpdateTrainingInstituteStudentProfileRequestModel } from "../training-institute/students/update-student-profile-request-model";
import { UpdateTrainingInstituteStudentProfileResponseModel } from "../training-institute/students/update-student-profile-response-model";
import { ArchiveTrainingInstituteCourseRequestModel } from "../training-institute/courses/archive-course-request-model";
import { ArchiveTrainingInstituteCourseResponseModel } from "../training-institute/courses/archive-course-response-model";
import { CreateTrainingInstituteCourseRequestModel } from "../training-institute/courses/create-course-request-model";
import { CreateTrainingInstituteCourseResponseModel } from "../training-institute/courses/create-course-response-model";
import { GetTrainingInstituteCourseRequestModel } from "../training-institute/courses/get-course-request-model";
import { GetTrainingInstituteCourseResponseModel } from "../training-institute/courses/get-course-response-model";
import { ListTrainingInstituteCoursesRequestModel } from "../training-institute/courses/list-courses-request-model";
import { ListTrainingInstituteCoursesResponseModel } from "../training-institute/courses/list-courses-response-model";
import { UpdateTrainingInstituteCourseParamsModel } from "../training-institute/courses/update-course-params-model";
import { UpdateTrainingInstituteCourseRequestModel } from "../training-institute/courses/update-course-request-model";
import { UpdateTrainingInstituteCourseResponseModel } from "../training-institute/courses/update-course-response-model";
import { AdjustTrainingInstituteFeePlanParamsModel } from "../training-institute/enrollments/adjust-fee-plan-params-model";
import { AdjustTrainingInstituteFeePlanRequestModel } from "../training-institute/enrollments/adjust-fee-plan-request-model";
import { AdjustTrainingInstituteFeePlanResponseModel } from "../training-institute/enrollments/adjust-fee-plan-response-model";
import { CreateTrainingInstituteEnrollmentRequestModel } from "../training-institute/enrollments/create-enrollment-request-model";
import { CreateTrainingInstituteEnrollmentResponseModel } from "../training-institute/enrollments/create-enrollment-response-model";
import { ListTrainingInstituteEnrollmentsRequestModel } from "../training-institute/enrollments/list-enrollments-request-model";
import { ListTrainingInstituteEnrollmentsResponseModel } from "../training-institute/enrollments/list-enrollments-response-model";
import { EndTrainingInstituteEnrollmentRequestModel } from "../training-institute/enrollments/end-enrollment-request-model";
import { EndTrainingInstituteEnrollmentResponseModel } from "../training-institute/enrollments/end-enrollment-response-model";
import { GetTrainingInstituteEnrollmentRequestModel } from "../training-institute/enrollments/get-enrollment-request-model";
import { GetTrainingInstituteEnrollmentResponseModel } from "../training-institute/enrollments/get-enrollment-response-model";
import { ListTrainingInstituteFeePaymentsParamsModel } from "../training-institute/enrollments/list-fee-payments-params-model";
import { ListTrainingInstituteFeePaymentsRequestModel } from "../training-institute/enrollments/list-fee-payments-request-model";
import { ListTrainingInstituteFeePaymentsResponseModel } from "../training-institute/enrollments/list-fee-payments-response-model";
import { MoveTrainingInstituteEnrollmentParamsModel } from "../training-institute/enrollments/move-enrollment-params-model";
import { MoveTrainingInstituteEnrollmentRequestModel } from "../training-institute/enrollments/move-enrollment-request-model";
import { MoveTrainingInstituteEnrollmentResponseModel } from "../training-institute/enrollments/move-enrollment-response-model";
import { OverrideTrainingInstituteEnrollmentModeParamsModel } from "../training-institute/enrollments/override-enrollment-mode-params-model";
import { OverrideTrainingInstituteEnrollmentModeRequestModel } from "../training-institute/enrollments/override-enrollment-mode-request-model";
import { OverrideTrainingInstituteEnrollmentModeResponseModel } from "../training-institute/enrollments/override-enrollment-mode-response-model";
import { RecordTrainingInstituteFeePaymentParamsModel } from "../training-institute/enrollments/record-fee-payment-params-model";
import { RecordTrainingInstituteFeePaymentRequestModel } from "../training-institute/enrollments/record-fee-payment-request-model";
import { RecordTrainingInstituteFeePaymentResponseModel } from "../training-institute/enrollments/record-fee-payment-response-model";
import { SetTrainingInstituteEnrollmentTimingsParamsModel } from "../training-institute/enrollments/set-enrollment-timings-params-model";
import { SetTrainingInstituteEnrollmentTimingsRequestModel } from "../training-institute/enrollments/set-enrollment-timings-request-model";
import { SetTrainingInstituteEnrollmentTimingsResponseModel } from "../training-institute/enrollments/set-enrollment-timings-response-model";
import { GetTrainingInstituteOwnerDashboardResponseModel } from "../training-institute/dashboard/get-owner-dashboard-response-model";
import { GetTrainingInstituteFamilyHomeResponseModel } from "../training-institute/home/get-family-home-response-model";
import { GetTrainingInstituteReceiptRequestModel } from "../training-institute/payments/get-receipt-request-model";
import { GetTrainingInstituteReceiptResponseModel } from "../training-institute/payments/get-receipt-response-model";
import { ActivateTrainingInstituteTeacherResponseModel } from "../training-institute/teacher/activate/activate-teacher-response-model";
import { CreateTrainingInstituteTeacherRequestModel } from "../training-institute/teachers/create-teacher-request-model";
import { ListTrainingInstituteTeachersRequestModel } from "../training-institute/teachers/list-teachers-request-model";
import { ListTrainingInstituteTeachersResponseModel } from "../training-institute/teachers/list-teachers-response-model";
import { TrainingInstituteTeacherResponseModel } from "../training-institute/teachers/teacher-response-model";
import { TrainingInstituteTeacherParamsModel } from "../training-institute/teachers/[id]/teacher-params-model";
import { UpdateTrainingInstituteTeacherProfileRequestModel } from "../training-institute/teachers/[id]/profile/update-teacher-profile-request-model";
import {
  AddTrainingInstituteTeacherDocumentRequestModel,
  ListTrainingInstituteTeacherDocumentsResponseModel,
  RemoveTrainingInstituteTeacherDocumentResponseModel,
  TrainingInstituteTeacherDocumentMetadataModel,
  TrainingInstituteTeacherDocumentParamsModel,
} from "../training-institute/teachers/[id]/documents/teacher-document-models";
import {
  AssignTrainingInstituteTeacherBatchRequestModel,
  TrainingInstituteTeacherBatchesResponseModel,
} from "../training-institute/teachers/[id]/batches/assignment-models";
import { UnassignTrainingInstituteTeacherBatchParamsModel } from "../training-institute/teachers/[id]/batches/[batchId]/unassign/unassign-teacher-batch-params-model";
import {
  TrainingInstituteAttendanceRegisterParamsModel,
  TrainingInstituteAttendanceRegisterResponseModel,
  ListTrainingInstituteAttendanceRegistersRequestModel,
  ListTrainingInstituteAttendanceRegistersResponseModel,
  OpenTrainingInstituteAttendanceRegisterRequestModel,
} from "../training-institute/attendance/registers/attendance-models";
import { SaveTrainingInstituteAttendanceMarksRequestModel } from "../training-institute/attendance/registers/[id]/marks/save-attendance-marks-request-model";
import {
  ListTrainingInstituteStudentAttendanceRequestModel,
  TrainingInstituteStudentAttendanceHistoryResponseModel,
  TrainingInstituteStudentAttendanceParamsModel,
} from "../training-institute/students/[id]/attendance/student-attendance-models";
import {
  BookTrainingInstituteDemoRequestModel,
  ListTrainingInstituteDemoSlotsRequestModel,
  ListTrainingInstituteDemoSlotsResponseModel,
  ListTrainingInstituteDemosRequestModel,
  ListTrainingInstituteDemosResponseModel,
  MarkTrainingInstituteDemoAttendanceRequestModel,
  TrainingInstituteDemoModel,
  TrainingInstituteDemoParamsModel,
} from "../training-institute/demos/demo-models";
import {
  ConvertTrainingInstituteEnquiryRequestModel,
  ConvertTrainingInstituteEnquiryResponseModel,
  CreateTrainingInstituteEnquiryRequestModel,
  FindTrainingInstituteEnquiryPhoneMatchesRequestModel,
  FindTrainingInstituteEnquiryPhoneMatchesResponseModel,
  GetTrainingInstituteEnquirySummaryRequestModel,
  ListTrainingInstituteEnquiriesRequestModel,
  ListTrainingInstituteEnquiriesResponseModel,
  LogTrainingInstituteEnquiryFollowUpRequestModel,
  MarkTrainingInstituteEnquiryNotInterestedRequestModel,
  ReopenTrainingInstituteEnquiryRequestModel,
  TrainingInstituteEnquiryDetailModel,
  TrainingInstituteEnquiryModel,
  TrainingInstituteEnquiryOptionsResponseModel,
  TrainingInstituteEnquiryParamsModel,
  TrainingInstituteEnquirySummaryResponseModel,
  UpdateTrainingInstituteEnquiryDetailsRequestModel,
} from "../training-institute/enquiries/enquiry-models";
import {
  AddTrainingInstituteEnquirySourceRequestModel,
  ListTrainingInstituteEnquirySourcesResponseModel,
  RenameTrainingInstituteEnquirySourceRequestModel,
  TrainingInstituteEnquirySourceModel,
  TrainingInstituteEnquirySourceParamsModel,
} from "../training-institute/enquiry-sources/enquiry-source-models";
import {
  CheckTrainingInstituteHomeworkSubmissionRequestModel,
  PostTrainingInstituteStudyMaterialRequestModel,
  SetTrainingInstituteHomeworkRequestModel,
  SubmitTrainingInstituteHomeworkRequestModel,
  TrainingInstituteAttachmentModel,
  TrainingInstituteBatchClassWorkResponseModel,
  TrainingInstituteClassWorkIdParamsModel,
  TrainingInstituteFamilyClassWorkResponseModel,
  TrainingInstituteFamilyHomeworkModel,
  TrainingInstituteHomeworkModel,
  TrainingInstituteHomeworkSubmissionModel,
  TrainingInstituteHomeworkSubmissionParamsModel,
  TrainingInstituteHomeworkSubmissionsResponseModel,
  TrainingInstituteStudyMaterialModel,
  UndoTrainingInstituteHomeworkSubmissionRequestModel,
  UpdateTrainingInstituteHomeworkRequestModel,
  UpdateTrainingInstituteStudyMaterialRequestModel,
  UploadTrainingInstituteAttachmentRequestModel,
} from "../training-institute/homework/class-work-models";
import { buildOpenApiDocument } from "./openapi";

export const openApiDocument = buildOpenApiDocument(
  [
    {
      method: "get",
      path: "/api/training-institute/calendar",
      summary: "View role-scoped Batch Timings with Class Changes and Holidays",
      tags: ["Calendar"],
      successStatus: StatusCodes.OK,
      successDescription: "Listed",
      successSchema: TrainingInstituteCalendarResponseModel,
      errors: [401, 403, 500],
    },
    {
      method: "get",
      path: "/api/training-institute/classes/{batchId}/{date}/{startTime}",
      summary: "View a class before joining",
      tags: ["Classes"],
      params: TrainingInstituteClassParamsModel,
      successStatus: StatusCodes.OK,
      successDescription: "Class",
      successSchema: TrainingInstituteClassDetailResponseModel,
      errors: [400, 401, 403, 404, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/classes/{batchId}/{date}/{startTime}/start",
      summary: "Start a Whiteboard class as Owner or Teacher",
      tags: ["Classes"],
      params: TrainingInstituteClassParamsModel,
      successStatus: StatusCodes.OK,
      successDescription: "Host token",
      successSchema: TrainingInstituteClassTokenResponseModel,
      errors: [400, 401, 403, 404, 409, 503],
    },
    {
      method: "post",
      path: "/api/training-institute/classes/{batchId}/{date}/{startTime}/join",
      summary: "Join a recorded Whiteboard class",
      tags: ["Classes"],
      params: TrainingInstituteClassParamsModel,
      successStatus: StatusCodes.OK,
      successDescription: "Participant token",
      successSchema: TrainingInstituteClassTokenResponseModel,
      errors: [400, 401, 403, 404, 409, 503],
    },
    {
      method: "get",
      path: "/api/training-institute/classes/{batchId}/{date}/{startTime}/recording",
      summary: "Download a class recording",
      tags: ["Classes"],
      params: TrainingInstituteClassParamsModel,
      successStatus: 302,
      successDescription: "Short-lived private R2 download redirect",
      errors: [400, 401, 403, 404, 409, 503],
    },
    {
      method: "post",
      path: "/api/training-institute/classes/{batchId}/{date}/{startTime}/cancel",
      summary:
        "Cancel a Class, or a Rescheduled Class, as Owner or assigned Teacher",
      tags: ["Classes"],
      params: TrainingInstituteClassParamsModel,
      body: CancelTrainingInstituteClassRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Cancelled",
      successSchema: TrainingInstituteClassChangeModel,
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/classes/{batchId}/{date}/{startTime}/move",
      summary:
        "Move a Class to another date or time as Owner or assigned Teacher",
      tags: ["Classes"],
      params: TrainingInstituteClassParamsModel,
      body: MoveTrainingInstituteClassRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Moved",
      successSchema: TrainingInstituteClassChangeModel,
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/classes/{batchId}/{date}/{startTime}/restore",
      summary: "Restore a Cancelled or Moved Class before it happens",
      tags: ["Classes"],
      params: TrainingInstituteClassParamsModel,
      successStatus: StatusCodes.NO_CONTENT,
      successDescription: "Restored",
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/holidays",
      summary: "Declare a Workspace Holiday as Owner",
      tags: ["Classes"],
      body: DeclareTrainingInstituteHolidayRequestModel,
      successStatus: StatusCodes.CREATED,
      successDescription: "Declared",
      successSchema: TrainingInstituteHolidayModel,
      errors: [400, 401, 403, 409, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/holidays/{id}/remove",
      summary: "Remove an upcoming Holiday as Owner",
      tags: ["Classes"],
      params: TrainingInstituteHolidayParamsModel,
      successStatus: StatusCodes.NO_CONTENT,
      successDescription: "Removed",
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      method: "post",
      path: "/api/webhooks/realtimekit",
      summary: "Receive signed RealtimeKit meeting and recording events",
      tags: ["Classes"],
      security: false,
      successStatus: StatusCodes.NO_CONTENT,
      successDescription: "Processed",
      errors: [400, 401, 503],
    },
    {
      method: "post",
      path: "/api/training-institute/attendance/registers",
      summary: "Open a Batch Attendance Register for today or an earlier date",
      tags: ["Attendance"],
      body: OpenTrainingInstituteAttendanceRegisterRequestModel,
      successStatus: StatusCodes.CREATED,
      successDescription: "Opened",
      successSchema: TrainingInstituteAttendanceRegisterResponseModel,
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      method: "get",
      path: "/api/training-institute/attendance/registers",
      summary: "List Batch Attendance Registers",
      tags: ["Attendance"],
      query: ListTrainingInstituteAttendanceRegistersRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Listed",
      successSchema: ListTrainingInstituteAttendanceRegistersResponseModel,
      errors: [400, 401, 403, 404, 500],
    },
    {
      method: "get",
      path: "/api/training-institute/attendance/registers/{id}",
      summary: "Get an Attendance Register",
      tags: ["Attendance"],
      params: TrainingInstituteAttendanceRegisterParamsModel,
      successStatus: StatusCodes.OK,
      successDescription: "Found",
      successSchema: TrainingInstituteAttendanceRegisterResponseModel,
      errors: [400, 401, 403, 404, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/attendance/registers/{id}/marks",
      summary: "Mark or correct Attendance",
      tags: ["Attendance"],
      params: TrainingInstituteAttendanceRegisterParamsModel,
      body: SaveTrainingInstituteAttendanceMarksRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Saved",
      successSchema: TrainingInstituteAttendanceRegisterResponseModel,
      errors: [400, 401, 403, 404, 500],
    },
    {
      method: "get",
      path: "/api/training-institute/students/{id}/attendance",
      summary: "Get Student Attendance history",
      tags: ["Attendance"],
      params: TrainingInstituteStudentAttendanceParamsModel,
      query: ListTrainingInstituteStudentAttendanceRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Listed",
      successSchema: TrainingInstituteStudentAttendanceHistoryResponseModel,
      errors: [400, 401, 403, 404, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/teachers",
      summary: "Add and invite a Teacher",
      tags: ["Teachers"],
      body: CreateTrainingInstituteTeacherRequestModel,
      successStatus: StatusCodes.CREATED,
      successDescription: "Created",
      successSchema: TrainingInstituteTeacherResponseModel,
      errors: [400, 401, 403, 409, 500],
    },
    {
      method: "get",
      path: "/api/training-institute/teachers",
      summary: "List Teachers",
      tags: ["Teachers"],
      query: ListTrainingInstituteTeachersRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Listed",
      successSchema: ListTrainingInstituteTeachersResponseModel,
      errors: [400, 401, 403, 500],
    },
    {
      method: "get",
      path: "/api/training-institute/teachers/{id}",
      summary: "Get a Teacher",
      tags: ["Teachers"],
      params: TrainingInstituteTeacherParamsModel,
      successStatus: StatusCodes.OK,
      successDescription: "Found",
      successSchema: TrainingInstituteTeacherResponseModel,
      errors: [400, 401, 403, 404, 500],
    },
    {
      method: "get",
      path: "/api/training-institute/teachers/{id}/photo",
      summary: "Get a Teacher photo",
      tags: ["Teachers"],
      params: TrainingInstituteTeacherParamsModel,
      successStatus: StatusCodes.OK,
      successDescription: "Photo",
      successBinaryContentTypes: ["image/jpeg", "image/png", "image/webp"],
      errors: [400, 401, 403, 404, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/teachers/{id}/profile",
      summary: "Update Teacher profile",
      tags: ["Teachers"],
      params: TrainingInstituteTeacherParamsModel,
      body: UpdateTrainingInstituteTeacherProfileRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Updated",
      successSchema: TrainingInstituteTeacherResponseModel,
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      method: "get",
      path: "/api/training-institute/teachers/{id}/documents",
      summary: "List private Teacher documents",
      tags: ["Teachers"],
      params: TrainingInstituteTeacherParamsModel,
      successStatus: StatusCodes.OK,
      successDescription: "Listed",
      successSchema: ListTrainingInstituteTeacherDocumentsResponseModel,
      errors: [400, 401, 403, 404, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/teachers/{id}/documents",
      summary: "Add a private Teacher document",
      tags: ["Teachers"],
      params: TrainingInstituteTeacherParamsModel,
      body: AddTrainingInstituteTeacherDocumentRequestModel,
      successStatus: StatusCodes.CREATED,
      successDescription: "Created",
      successSchema: TrainingInstituteTeacherDocumentMetadataModel,
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      method: "get",
      path: "/api/training-institute/teachers/{id}/documents/{documentId}",
      summary: "Download a private Teacher document",
      tags: ["Teachers"],
      params: TrainingInstituteTeacherDocumentParamsModel,
      successStatus: StatusCodes.OK,
      successDescription: "Document",
      successBinaryContentTypes: ["application/pdf", "image/jpeg", "image/png"],
      errors: [400, 401, 403, 404, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/teachers/{id}/documents/{documentId}/remove",
      summary: "Remove a private Teacher document",
      tags: ["Teachers"],
      params: TrainingInstituteTeacherDocumentParamsModel,
      successStatus: StatusCodes.OK,
      successDescription: "Removed",
      successSchema: RemoveTrainingInstituteTeacherDocumentResponseModel,
      errors: [400, 401, 403, 404, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/teachers/{id}/invite",
      summary: "Resend Teacher invitation",
      tags: ["Teachers"],
      params: TrainingInstituteTeacherParamsModel,
      successStatus: StatusCodes.OK,
      successDescription: "Updated",
      successSchema: TrainingInstituteTeacherResponseModel,
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/teachers/{id}/deactivate",
      summary: "Deactivate Teacher",
      tags: ["Teachers"],
      params: TrainingInstituteTeacherParamsModel,
      successStatus: StatusCodes.OK,
      successDescription: "Updated",
      successSchema: TrainingInstituteTeacherResponseModel,
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      method: "get",
      path: "/api/training-institute/teachers/{id}/batches",
      summary: "List Teacher Batches",
      tags: ["Teachers"],
      params: TrainingInstituteTeacherParamsModel,
      successStatus: StatusCodes.OK,
      successDescription: "Listed",
      successSchema: TrainingInstituteTeacherBatchesResponseModel,
      errors: [400, 401, 403, 404, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/teachers/{id}/batches",
      summary: "Assign Teacher to Batch",
      tags: ["Teachers"],
      params: TrainingInstituteTeacherParamsModel,
      body: AssignTrainingInstituteTeacherBatchRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Assigned",
      successSchema: TrainingInstituteTeacherBatchesResponseModel,
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/teachers/{id}/batches/{batchId}/unassign",
      summary: "Unassign Teacher from Batch",
      tags: ["Teachers"],
      params: UnassignTrainingInstituteTeacherBatchParamsModel,
      successStatus: StatusCodes.OK,
      successDescription: "Unassigned",
      successSchema: TrainingInstituteTeacherBatchesResponseModel,
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/teacher/activate",
      summary: "Activate Teacher membership link",
      tags: ["Teachers"],
      successStatus: StatusCodes.OK,
      successDescription: "Activated",
      successSchema: ActivateTrainingInstituteTeacherResponseModel,
      errors: [401, 403, 404, 409, 500],
    },
    {
      method: "get",
      path: "/api/training-institute/teacher/batches",
      summary: "List My Batches",
      tags: ["Teachers"],
      successStatus: StatusCodes.OK,
      successDescription: "Listed",
      successSchema: TrainingInstituteTeacherBatchesResponseModel,
      errors: [401, 403, 404, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/students",
      summary: "Admit a Student",
      tags: ["Students"],
      body: CreateTrainingInstituteStudentRequestModel,
      successStatus: StatusCodes.CREATED,
      successDescription: "Created",
      successSchema: CreateTrainingInstituteStudentResponseModel,
      errors: [
        StatusCodes.BAD_REQUEST,
        StatusCodes.UNAUTHORIZED,
        StatusCodes.FORBIDDEN,
        StatusCodes.CONFLICT,
        StatusCodes.INTERNAL_SERVER_ERROR,
      ],
    },
    {
      method: "get",
      path: "/api/training-institute/students",
      summary: "List Students in the Active Workspace",
      tags: ["Students"],
      query: ListTrainingInstituteStudentsRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Listed",
      successSchema: ListTrainingInstituteStudentsResponseModel,
      errors: [
        StatusCodes.BAD_REQUEST,
        StatusCodes.UNAUTHORIZED,
        StatusCodes.FORBIDDEN,
        StatusCodes.INTERNAL_SERVER_ERROR,
      ],
    },
    {
      method: "get",
      path: "/api/training-institute/students/{id}",
      summary: "Get a Student",
      tags: ["Students"],
      params: GetTrainingInstituteStudentRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Found",
      successSchema: GetTrainingInstituteStudentResponseModel,
      errors: [
        StatusCodes.BAD_REQUEST,
        StatusCodes.UNAUTHORIZED,
        StatusCodes.FORBIDDEN,
        StatusCodes.NOT_FOUND,
        StatusCodes.INTERNAL_SERVER_ERROR,
      ],
    },
    {
      method: "post",
      path: "/api/training-institute/students/{id}/profile",
      summary: "Update a Student profile",
      tags: ["Students"],
      params: UpdateTrainingInstituteStudentProfileParamsModel,
      body: UpdateTrainingInstituteStudentProfileRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Updated",
      successSchema: UpdateTrainingInstituteStudentProfileResponseModel,
      errors: [
        StatusCodes.BAD_REQUEST,
        StatusCodes.UNAUTHORIZED,
        StatusCodes.FORBIDDEN,
        StatusCodes.NOT_FOUND,
        StatusCodes.INTERNAL_SERVER_ERROR,
      ],
    },
    {
      method: "post",
      path: "/api/training-institute/students/{id}/drop",
      summary: "Drop a Student",
      tags: ["Students"],
      params: DropTrainingInstituteStudentRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Dropped",
      successSchema: DropTrainingInstituteStudentResponseModel,
      errors: [
        StatusCodes.BAD_REQUEST,
        StatusCodes.UNAUTHORIZED,
        StatusCodes.FORBIDDEN,
        StatusCodes.NOT_FOUND,
        StatusCodes.CONFLICT,
        StatusCodes.INTERNAL_SERVER_ERROR,
      ],
    },
    {
      method: "post",
      path: "/api/training-institute/courses",
      summary: "Create a Course",
      tags: ["Courses"],
      body: CreateTrainingInstituteCourseRequestModel,
      successStatus: StatusCodes.CREATED,
      successDescription: "Created",
      successSchema: CreateTrainingInstituteCourseResponseModel,
      errors: [
        StatusCodes.BAD_REQUEST,
        StatusCodes.UNAUTHORIZED,
        StatusCodes.FORBIDDEN,
        StatusCodes.INTERNAL_SERVER_ERROR,
      ],
    },
    {
      method: "get",
      path: "/api/training-institute/courses",
      summary: "List Courses in the Active Workspace",
      tags: ["Courses"],
      query: ListTrainingInstituteCoursesRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Listed",
      successSchema: ListTrainingInstituteCoursesResponseModel,
      errors: [
        StatusCodes.BAD_REQUEST,
        StatusCodes.UNAUTHORIZED,
        StatusCodes.FORBIDDEN,
        StatusCodes.INTERNAL_SERVER_ERROR,
      ],
    },
    {
      method: "get",
      path: "/api/training-institute/courses/{id}",
      summary: "Get a Course",
      tags: ["Courses"],
      params: GetTrainingInstituteCourseRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Found",
      successSchema: GetTrainingInstituteCourseResponseModel,
      errors: [
        StatusCodes.BAD_REQUEST,
        StatusCodes.UNAUTHORIZED,
        StatusCodes.FORBIDDEN,
        StatusCodes.NOT_FOUND,
        StatusCodes.INTERNAL_SERVER_ERROR,
      ],
    },
    {
      method: "post",
      path: "/api/training-institute/courses/{id}/update",
      summary: "Update a Course",
      tags: ["Courses"],
      params: UpdateTrainingInstituteCourseParamsModel,
      body: UpdateTrainingInstituteCourseRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Updated",
      successSchema: UpdateTrainingInstituteCourseResponseModel,
      errors: [
        StatusCodes.BAD_REQUEST,
        StatusCodes.UNAUTHORIZED,
        StatusCodes.FORBIDDEN,
        StatusCodes.NOT_FOUND,
        StatusCodes.INTERNAL_SERVER_ERROR,
      ],
    },
    {
      method: "post",
      path: "/api/training-institute/courses/{id}/archive",
      summary: "Archive a Course",
      tags: ["Courses"],
      params: ArchiveTrainingInstituteCourseRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Archived",
      successSchema: ArchiveTrainingInstituteCourseResponseModel,
      errors: [
        StatusCodes.BAD_REQUEST,
        StatusCodes.UNAUTHORIZED,
        StatusCodes.FORBIDDEN,
        StatusCodes.NOT_FOUND,
        StatusCodes.CONFLICT,
        StatusCodes.INTERNAL_SERVER_ERROR,
      ],
    },
    {
      method: "post",
      path: "/api/training-institute/batches",
      summary: "Create a Batch",
      tags: ["Batches"],
      body: CreateTrainingInstituteBatchRequestModel,
      successStatus: StatusCodes.CREATED,
      successDescription: "Created",
      successSchema: CreateTrainingInstituteBatchResponseModel,
      errors: [
        StatusCodes.BAD_REQUEST,
        StatusCodes.UNAUTHORIZED,
        StatusCodes.FORBIDDEN,
        StatusCodes.NOT_FOUND,
        StatusCodes.CONFLICT,
        StatusCodes.INTERNAL_SERVER_ERROR,
      ],
    },
    {
      method: "get",
      path: "/api/training-institute/batches",
      summary: "List Batches in the Active Workspace",
      tags: ["Batches"],
      query: ListTrainingInstituteBatchesRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Listed",
      successSchema: ListTrainingInstituteBatchesResponseModel,
      errors: [
        StatusCodes.BAD_REQUEST,
        StatusCodes.UNAUTHORIZED,
        StatusCodes.FORBIDDEN,
        StatusCodes.INTERNAL_SERVER_ERROR,
      ],
    },
    {
      method: "get",
      path: "/api/training-institute/batches/{id}",
      summary: "Get a Batch",
      tags: ["Batches"],
      params: GetTrainingInstituteBatchRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Found",
      successSchema: GetTrainingInstituteBatchResponseModel,
      errors: [
        StatusCodes.BAD_REQUEST,
        StatusCodes.UNAUTHORIZED,
        StatusCodes.FORBIDDEN,
        StatusCodes.NOT_FOUND,
        StatusCodes.INTERNAL_SERVER_ERROR,
      ],
    },
    {
      method: "post",
      path: "/api/training-institute/batches/{id}/schedule",
      summary: "Update a Batch schedule",
      tags: ["Batches"],
      params: UpdateTrainingInstituteBatchScheduleParamsModel,
      body: UpdateTrainingInstituteBatchScheduleRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Updated",
      successSchema: UpdateTrainingInstituteBatchScheduleResponseModel,
      errors: [
        StatusCodes.BAD_REQUEST,
        StatusCodes.UNAUTHORIZED,
        StatusCodes.FORBIDDEN,
        StatusCodes.NOT_FOUND,
        StatusCodes.CONFLICT,
        StatusCodes.INTERNAL_SERVER_ERROR,
      ],
    },
    {
      method: "post",
      path: "/api/training-institute/batches/{id}/close",
      summary: "Close a Batch",
      tags: ["Batches"],
      params: CloseTrainingInstituteBatchRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Closed",
      successSchema: CloseTrainingInstituteBatchResponseModel,
      errors: [
        StatusCodes.BAD_REQUEST,
        StatusCodes.UNAUTHORIZED,
        StatusCodes.FORBIDDEN,
        StatusCodes.NOT_FOUND,
        StatusCodes.CONFLICT,
        StatusCodes.INTERNAL_SERVER_ERROR,
      ],
    },
    {
      method: "post",
      path: "/api/training-institute/enrollments",
      summary: "Enroll a Student in a Batch",
      tags: ["Enrollments"],
      body: CreateTrainingInstituteEnrollmentRequestModel,
      successStatus: StatusCodes.CREATED,
      successDescription: "Created",
      successSchema: CreateTrainingInstituteEnrollmentResponseModel,
      errors: [
        StatusCodes.BAD_REQUEST,
        StatusCodes.UNAUTHORIZED,
        StatusCodes.FORBIDDEN,
        StatusCodes.NOT_FOUND,
        StatusCodes.CONFLICT,
        StatusCodes.INTERNAL_SERVER_ERROR,
      ],
    },
    {
      method: "get",
      path: "/api/training-institute/enrollments",
      summary: "List Enrollments in the Active Workspace",
      tags: ["Enrollments"],
      query: ListTrainingInstituteEnrollmentsRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Listed",
      successSchema: ListTrainingInstituteEnrollmentsResponseModel,
      errors: [
        StatusCodes.BAD_REQUEST,
        StatusCodes.UNAUTHORIZED,
        StatusCodes.FORBIDDEN,
        StatusCodes.INTERNAL_SERVER_ERROR,
      ],
    },
    {
      method: "get",
      path: "/api/training-institute/enrollments/{id}",
      summary: "Get an Enrollment",
      tags: ["Enrollments"],
      params: GetTrainingInstituteEnrollmentRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Found",
      successSchema: GetTrainingInstituteEnrollmentResponseModel,
      errors: [
        StatusCodes.BAD_REQUEST,
        StatusCodes.UNAUTHORIZED,
        StatusCodes.FORBIDDEN,
        StatusCodes.NOT_FOUND,
        StatusCodes.INTERNAL_SERVER_ERROR,
      ],
    },
    {
      method: "post",
      path: "/api/training-institute/enrollments/{id}/mode",
      summary: "Override Enrollment Class Mode",
      tags: ["Enrollments"],
      params: OverrideTrainingInstituteEnrollmentModeParamsModel,
      body: OverrideTrainingInstituteEnrollmentModeRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Updated",
      successSchema: OverrideTrainingInstituteEnrollmentModeResponseModel,
      errors: [
        StatusCodes.BAD_REQUEST,
        StatusCodes.UNAUTHORIZED,
        StatusCodes.FORBIDDEN,
        StatusCodes.NOT_FOUND,
        StatusCodes.CONFLICT,
        StatusCodes.INTERNAL_SERVER_ERROR,
      ],
    },
    {
      method: "post",
      path: "/api/training-institute/enrollments/{id}/timings",
      summary: "Set Enrollment Timings",
      tags: ["Enrollments"],
      params: SetTrainingInstituteEnrollmentTimingsParamsModel,
      body: SetTrainingInstituteEnrollmentTimingsRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Updated",
      successSchema: SetTrainingInstituteEnrollmentTimingsResponseModel,
      errors: [
        StatusCodes.BAD_REQUEST,
        StatusCodes.UNAUTHORIZED,
        StatusCodes.FORBIDDEN,
        StatusCodes.NOT_FOUND,
        StatusCodes.CONFLICT,
        StatusCodes.INTERNAL_SERVER_ERROR,
      ],
    },
    {
      method: "post",
      path: "/api/training-institute/enrollments/{id}/move",
      summary: "Move an Enrollment to another Batch",
      tags: ["Enrollments"],
      params: MoveTrainingInstituteEnrollmentParamsModel,
      body: MoveTrainingInstituteEnrollmentRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Moved",
      successSchema: MoveTrainingInstituteEnrollmentResponseModel,
      errors: [
        StatusCodes.BAD_REQUEST,
        StatusCodes.UNAUTHORIZED,
        StatusCodes.FORBIDDEN,
        StatusCodes.NOT_FOUND,
        StatusCodes.CONFLICT,
        StatusCodes.INTERNAL_SERVER_ERROR,
      ],
    },
    {
      method: "post",
      path: "/api/training-institute/enrollments/{id}/end",
      summary: "End an Enrollment",
      tags: ["Enrollments"],
      params: EndTrainingInstituteEnrollmentRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Ended",
      successSchema: EndTrainingInstituteEnrollmentResponseModel,
      errors: [
        StatusCodes.BAD_REQUEST,
        StatusCodes.UNAUTHORIZED,
        StatusCodes.FORBIDDEN,
        StatusCodes.NOT_FOUND,
        StatusCodes.CONFLICT,
        StatusCodes.INTERNAL_SERVER_ERROR,
      ],
    },
    {
      method: "post",
      path: "/api/training-institute/enrollments/{id}/fee-plan",
      summary: "Adjust the Fee Plan on an Enrollment",
      tags: ["Fees"],
      params: AdjustTrainingInstituteFeePlanParamsModel,
      body: AdjustTrainingInstituteFeePlanRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Updated",
      successSchema: AdjustTrainingInstituteFeePlanResponseModel,
      errors: [
        StatusCodes.BAD_REQUEST,
        StatusCodes.UNAUTHORIZED,
        StatusCodes.FORBIDDEN,
        StatusCodes.NOT_FOUND,
        StatusCodes.CONFLICT,
        StatusCodes.INTERNAL_SERVER_ERROR,
      ],
    },
    {
      method: "post",
      path: "/api/training-institute/enrollments/{id}/payments",
      summary: "Record a Fee Payment",
      tags: ["Fees"],
      params: RecordTrainingInstituteFeePaymentParamsModel,
      body: RecordTrainingInstituteFeePaymentRequestModel,
      successStatus: StatusCodes.CREATED,
      successDescription: "Recorded",
      successSchema: RecordTrainingInstituteFeePaymentResponseModel,
      errors: [
        StatusCodes.BAD_REQUEST,
        StatusCodes.UNAUTHORIZED,
        StatusCodes.FORBIDDEN,
        StatusCodes.NOT_FOUND,
        StatusCodes.CONFLICT,
        StatusCodes.INTERNAL_SERVER_ERROR,
      ],
    },
    {
      method: "get",
      path: "/api/training-institute/enrollments/{id}/payments",
      summary: "List Fee Payments for an Enrollment",
      tags: ["Fees"],
      params: ListTrainingInstituteFeePaymentsParamsModel,
      query: ListTrainingInstituteFeePaymentsRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Listed",
      successSchema: ListTrainingInstituteFeePaymentsResponseModel,
      errors: [
        StatusCodes.BAD_REQUEST,
        StatusCodes.UNAUTHORIZED,
        StatusCodes.FORBIDDEN,
        StatusCodes.NOT_FOUND,
        StatusCodes.INTERNAL_SERVER_ERROR,
      ],
    },
    {
      method: "get",
      path: "/api/training-institute/payments/{id}/receipt",
      summary: "Get a Receipt",
      tags: ["Fees"],
      params: GetTrainingInstituteReceiptRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Found",
      successSchema: GetTrainingInstituteReceiptResponseModel,
      errors: [
        StatusCodes.BAD_REQUEST,
        StatusCodes.UNAUTHORIZED,
        StatusCodes.FORBIDDEN,
        StatusCodes.NOT_FOUND,
        StatusCodes.INTERNAL_SERVER_ERROR,
      ],
    },
    {
      method: "get",
      path: "/api/training-institute/dashboard",
      summary: "Get the Owner Dashboard",
      tags: ["Dashboard"],
      successStatus: StatusCodes.OK,
      successDescription: "Found",
      successSchema: GetTrainingInstituteOwnerDashboardResponseModel,
      errors: [
        StatusCodes.UNAUTHORIZED,
        StatusCodes.FORBIDDEN,
        StatusCodes.INTERNAL_SERVER_ERROR,
      ],
    },
    {
      method: "get",
      path: "/api/training-institute/home",
      summary:
        "Get the Student or Parent Home: next Class, dues, recent Attendance, and recordings for each linked Student",
      tags: ["Home"],
      successStatus: StatusCodes.OK,
      successDescription: "Found",
      successSchema: GetTrainingInstituteFamilyHomeResponseModel,
      errors: [
        StatusCodes.UNAUTHORIZED,
        StatusCodes.FORBIDDEN,
        StatusCodes.INTERNAL_SERVER_ERROR,
      ],
    },
    {
      method: "get",
      path: "/api/training-institute/enquiries",
      summary:
        "List Enquiries by view (Follow-ups due, Open, Closed, All) with search, as Owner or Teacher",
      tags: ["Enquiries"],
      query: ListTrainingInstituteEnquiriesRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Listed",
      successSchema: ListTrainingInstituteEnquiriesResponseModel,
      errors: [400, 401, 403, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/enquiries",
      summary: "Record an Enquiry as Owner or Teacher",
      tags: ["Enquiries"],
      body: CreateTrainingInstituteEnquiryRequestModel,
      successStatus: StatusCodes.CREATED,
      successDescription: "Recorded",
      successSchema: TrainingInstituteEnquiryModel,
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      method: "get",
      path: "/api/training-institute/enquiries/options",
      summary:
        "Courses, open Batches, active Teachers, and Sources for Enquiry forms",
      tags: ["Enquiries"],
      successStatus: StatusCodes.OK,
      successDescription: "Options",
      successSchema: TrainingInstituteEnquiryOptionsResponseModel,
      errors: [401, 403, 500],
    },
    {
      method: "get",
      path: "/api/training-institute/enquiries/summary",
      summary: "Monthly Enquiry summary (Asia/Kolkata) as Owner",
      tags: ["Enquiries"],
      query: GetTrainingInstituteEnquirySummaryRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Summary",
      successSchema: TrainingInstituteEnquirySummaryResponseModel,
      errors: [400, 401, 403, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/enquiries/phone-matches",
      summary:
        "Find open Enquiries and active Students with the same phone number",
      tags: ["Enquiries"],
      body: FindTrainingInstituteEnquiryPhoneMatchesRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Matches",
      successSchema: FindTrainingInstituteEnquiryPhoneMatchesResponseModel,
      errors: [400, 401, 403, 500],
    },
    {
      method: "get",
      path: "/api/training-institute/enquiries/{id}",
      summary: "Get an Enquiry with its history and demos",
      tags: ["Enquiries"],
      params: TrainingInstituteEnquiryParamsModel,
      successStatus: StatusCodes.OK,
      successDescription: "Found",
      successSchema: TrainingInstituteEnquiryDetailModel,
      errors: [400, 401, 403, 404, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/enquiries/{id}/details",
      summary: "Edit an Enquiry's details",
      tags: ["Enquiries"],
      params: TrainingInstituteEnquiryParamsModel,
      body: UpdateTrainingInstituteEnquiryDetailsRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Updated",
      successSchema: TrainingInstituteEnquiryModel,
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/enquiries/{id}/follow-ups",
      summary: "Log a follow-up and set or clear the next follow-up date",
      tags: ["Enquiries"],
      params: TrainingInstituteEnquiryParamsModel,
      body: LogTrainingInstituteEnquiryFollowUpRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Logged",
      successSchema: TrainingInstituteEnquiryDetailModel,
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/enquiries/{id}/not-interested",
      summary: "Close an Enquiry as Not interested; cancels its unmarked demos",
      tags: ["Enquiries"],
      params: TrainingInstituteEnquiryParamsModel,
      body: MarkTrainingInstituteEnquiryNotInterestedRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Closed",
      successSchema: TrainingInstituteEnquiryModel,
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/enquiries/{id}/reopen",
      summary: "Reopen a Not interested Enquiry",
      tags: ["Enquiries"],
      params: TrainingInstituteEnquiryParamsModel,
      body: ReopenTrainingInstituteEnquiryRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Reopened",
      successSchema: TrainingInstituteEnquiryModel,
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/enquiries/{id}/convert",
      summary: "Convert an Enquiry into a Student and Enrollment as Owner",
      tags: ["Enquiries"],
      params: TrainingInstituteEnquiryParamsModel,
      body: ConvertTrainingInstituteEnquiryRequestModel,
      successStatus: StatusCodes.CREATED,
      successDescription: "Converted",
      successSchema: ConvertTrainingInstituteEnquiryResponseModel,
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/enquiries/{id}/demos",
      summary: "Book a Batch demo or a one-to-one demo for an Enquiry",
      tags: ["Demos"],
      params: TrainingInstituteEnquiryParamsModel,
      body: BookTrainingInstituteDemoRequestModel,
      successStatus: StatusCodes.CREATED,
      successDescription: "Booked",
      successSchema: TrainingInstituteDemoModel,
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      method: "get",
      path: "/api/training-institute/demos",
      summary:
        "List booked demos in a date range: every demo for the Owner, a Teacher's own demos for a Teacher",
      tags: ["Demos"],
      query: ListTrainingInstituteDemosRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Listed",
      successSchema: ListTrainingInstituteDemosResponseModel,
      errors: [400, 401, 403, 500],
    },
    {
      method: "get",
      path: "/api/training-institute/demos/slots",
      summary: "A Batch's Classes on a date, with which can take a demo",
      tags: ["Demos"],
      query: ListTrainingInstituteDemoSlotsRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Slots",
      successSchema: ListTrainingInstituteDemoSlotsResponseModel,
      errors: [400, 401, 403, 404, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/demos/{id}/attendance",
      summary: "Mark a demo attended or missed, from its start time",
      tags: ["Demos"],
      params: TrainingInstituteDemoParamsModel,
      body: MarkTrainingInstituteDemoAttendanceRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Marked",
      successSchema: TrainingInstituteDemoModel,
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/demos/{id}/fee-paid",
      summary: "Mark a paid demo's fee as collected",
      tags: ["Demos"],
      params: TrainingInstituteDemoParamsModel,
      successStatus: StatusCodes.OK,
      successDescription: "Marked paid",
      successSchema: TrainingInstituteDemoModel,
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/demos/{id}/cancel",
      summary: "Cancel a demo booking that isn't marked yet",
      tags: ["Demos"],
      params: TrainingInstituteDemoParamsModel,
      successStatus: StatusCodes.OK,
      successDescription: "Cancelled",
      successSchema: TrainingInstituteDemoModel,
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      method: "get",
      path: "/api/training-institute/enquiry-sources",
      summary: "List Enquiry Sources, adding the defaults the first time",
      tags: ["Enquiry Sources"],
      successStatus: StatusCodes.OK,
      successDescription: "Listed",
      successSchema: ListTrainingInstituteEnquirySourcesResponseModel,
      errors: [401, 403, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/enquiry-sources",
      summary: "Add an Enquiry Source as Owner",
      tags: ["Enquiry Sources"],
      body: AddTrainingInstituteEnquirySourceRequestModel,
      successStatus: StatusCodes.CREATED,
      successDescription: "Added",
      successSchema: TrainingInstituteEnquirySourceModel,
      errors: [400, 401, 403, 409, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/enquiry-sources/{id}/rename",
      summary: "Rename an Enquiry Source as Owner",
      tags: ["Enquiry Sources"],
      params: TrainingInstituteEnquirySourceParamsModel,
      body: RenameTrainingInstituteEnquirySourceRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Renamed",
      successSchema: TrainingInstituteEnquirySourceModel,
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/enquiry-sources/{id}/retire",
      summary: "Retire an Enquiry Source as Owner; past Enquiries keep it",
      tags: ["Enquiry Sources"],
      params: TrainingInstituteEnquirySourceParamsModel,
      successStatus: StatusCodes.OK,
      successDescription: "Retired",
      successSchema: TrainingInstituteEnquirySourceModel,
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/enquiry-sources/{id}/restore",
      summary: "Restore a retired Enquiry Source as Owner",
      tags: ["Enquiry Sources"],
      params: TrainingInstituteEnquirySourceParamsModel,
      successStatus: StatusCodes.OK,
      successDescription: "Restored",
      successSchema: TrainingInstituteEnquirySourceModel,
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      method: "get",
      path: "/api/training-institute/batches/{id}/class-work",
      summary:
        "A Batch's Homework and Study Material, with Submission counts and Class dates, as Owner or assigned Teacher",
      tags: ["Homework"],
      params: TrainingInstituteClassWorkIdParamsModel,
      successStatus: StatusCodes.OK,
      successDescription: "Homework and Study Material",
      successSchema: TrainingInstituteBatchClassWorkResponseModel,
      errors: [400, 401, 403, 404, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/batches/{id}/study-materials",
      summary: "Share Study Material with a Batch as Owner or assigned Teacher",
      tags: ["Homework"],
      params: TrainingInstituteClassWorkIdParamsModel,
      body: PostTrainingInstituteStudyMaterialRequestModel,
      successStatus: StatusCodes.CREATED,
      successDescription: "Shared",
      successSchema: TrainingInstituteStudyMaterialModel,
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/study-materials/{id}/update",
      summary: "Edit Study Material",
      tags: ["Homework"],
      params: TrainingInstituteClassWorkIdParamsModel,
      body: UpdateTrainingInstituteStudyMaterialRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Updated",
      successSchema: TrainingInstituteStudyMaterialModel,
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/study-materials/{id}/remove",
      summary:
        "Remove Study Material from Teachers, Students, and Parents (the Owner keeps it)",
      tags: ["Homework"],
      params: TrainingInstituteClassWorkIdParamsModel,
      successStatus: StatusCodes.OK,
      successDescription: "Removed",
      successSchema: TrainingInstituteStudyMaterialModel,
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/batches/{id}/homework",
      summary:
        "Set Homework for a Batch against a Class date, as Owner or assigned Teacher",
      tags: ["Homework"],
      params: TrainingInstituteClassWorkIdParamsModel,
      body: SetTrainingInstituteHomeworkRequestModel,
      successStatus: StatusCodes.CREATED,
      successDescription: "Set",
      successSchema: TrainingInstituteHomeworkModel,
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/homework/{id}/update",
      summary:
        "Edit Homework: title, instructions, Class date, due date, files",
      tags: ["Homework"],
      params: TrainingInstituteClassWorkIdParamsModel,
      body: UpdateTrainingInstituteHomeworkRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Updated",
      successSchema: TrainingInstituteHomeworkModel,
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/homework/{id}/remove",
      summary:
        "Remove Homework from Teachers, Students, and Parents (the Owner keeps it)",
      tags: ["Homework"],
      params: TrainingInstituteClassWorkIdParamsModel,
      successStatus: StatusCodes.OK,
      successDescription: "Removed",
      successSchema: TrainingInstituteHomeworkModel,
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      method: "get",
      path: "/api/training-institute/homework/{id}/submissions",
      summary:
        "Who has submitted, who hasn't, and who is late, as Owner or assigned Teacher",
      tags: ["Homework"],
      params: TrainingInstituteClassWorkIdParamsModel,
      successStatus: StatusCodes.OK,
      successDescription: "Submissions",
      successSchema: TrainingInstituteHomeworkSubmissionsResponseModel,
      errors: [400, 401, 403, 404, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/homework/{id}/submissions/{submissionId}/check",
      summary:
        "Mark a Submission checked with an optional remark the Student and Parents see",
      tags: ["Homework"],
      params: TrainingInstituteHomeworkSubmissionParamsModel,
      body: CheckTrainingInstituteHomeworkSubmissionRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Checked",
      successSchema: TrainingInstituteHomeworkSubmissionModel,
      errors: [400, 401, 403, 404, 500],
    },
    {
      method: "get",
      path: "/api/training-institute/home/homework",
      summary:
        "Homework and Study Material for each Student linked to a Student or Parent",
      tags: ["Homework"],
      successStatus: StatusCodes.OK,
      successDescription: "Homework and Study Material",
      successSchema: TrainingInstituteFamilyClassWorkResponseModel,
      errors: [401, 403, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/homework/{id}/submit",
      summary:
        "Mark Homework done, or change it until checked, as the Student or a linked Parent",
      tags: ["Homework"],
      params: TrainingInstituteClassWorkIdParamsModel,
      body: SubmitTrainingInstituteHomeworkRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Submitted",
      successSchema: TrainingInstituteFamilyHomeworkModel,
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/homework/{id}/undo-submission",
      summary: "Undo marking Homework done, until it's checked",
      tags: ["Homework"],
      params: TrainingInstituteClassWorkIdParamsModel,
      body: UndoTrainingInstituteHomeworkSubmissionRequestModel,
      successStatus: StatusCodes.OK,
      successDescription: "Undone",
      successSchema: TrainingInstituteFamilyHomeworkModel,
      errors: [400, 401, 403, 404, 409, 500],
    },
    {
      method: "post",
      path: "/api/training-institute/attachments",
      summary:
        "Upload one PDF, JPEG, or PNG (4 MB or smaller) to attach when an item or Submission is saved",
      tags: ["Homework"],
      query: UploadTrainingInstituteAttachmentRequestModel,
      bodyBinaryContentTypes: ["application/pdf", "image/jpeg", "image/png"],
      successStatus: StatusCodes.CREATED,
      successDescription: "Uploaded",
      successSchema: TrainingInstituteAttachmentModel,
      errors: [400, 401, 403, 409, 413, 500],
    },
    {
      method: "get",
      path: "/api/training-institute/attachments/{id}",
      summary: "Download a file on Study Material, Homework, or a Submission",
      tags: ["Homework"],
      params: TrainingInstituteClassWorkIdParamsModel,
      successStatus: StatusCodes.OK,
      successDescription: "File",
      successBinaryContentTypes: ["application/pdf", "image/jpeg", "image/png"],
      errors: [400, 401, 403, 404, 500],
    },
  ],
  {
    ActivateTrainingInstituteTeacherResponseModel,
    AddTrainingInstituteTeacherDocumentRequestModel,
    AdjustTrainingInstituteFeePlanRequestModel,
    AdjustTrainingInstituteFeePlanResponseModel,
    ArchiveTrainingInstituteCourseResponseModel,
    AssignTrainingInstituteTeacherBatchRequestModel,
    CancelTrainingInstituteClassRequestModel,
    CloseTrainingInstituteBatchResponseModel,
    CreateTrainingInstituteBatchRequestModel,
    CreateTrainingInstituteBatchResponseModel,
    CreateTrainingInstituteCourseRequestModel,
    CreateTrainingInstituteCourseResponseModel,
    CreateTrainingInstituteEnrollmentRequestModel,
    CreateTrainingInstituteEnrollmentResponseModel,
    CreateTrainingInstituteStudentRequestModel,
    CreateTrainingInstituteStudentResponseModel,
    CreateTrainingInstituteTeacherRequestModel,
    DeclareTrainingInstituteHolidayRequestModel,
    DropTrainingInstituteStudentResponseModel,
    EndTrainingInstituteEnrollmentResponseModel,
    GetTrainingInstituteBatchResponseModel,
    GetTrainingInstituteCourseResponseModel,
    GetTrainingInstituteEnrollmentResponseModel,
    GetTrainingInstituteFamilyHomeResponseModel,
    GetTrainingInstituteOwnerDashboardResponseModel,
    GetTrainingInstituteReceiptResponseModel,
    GetTrainingInstituteStudentResponseModel,
    ListTrainingInstituteAttendanceRegistersResponseModel,
    ListTrainingInstituteBatchesResponseModel,
    ListTrainingInstituteCoursesResponseModel,
    ListTrainingInstituteEnrollmentsResponseModel,
    ListTrainingInstituteFeePaymentsResponseModel,
    ListTrainingInstituteStudentsResponseModel,
    ListTrainingInstituteTeacherDocumentsResponseModel,
    ListTrainingInstituteTeachersResponseModel,
    MoveTrainingInstituteClassRequestModel,
    MoveTrainingInstituteEnrollmentRequestModel,
    MoveTrainingInstituteEnrollmentResponseModel,
    OpenTrainingInstituteAttendanceRegisterRequestModel,
    OverrideTrainingInstituteEnrollmentModeRequestModel,
    OverrideTrainingInstituteEnrollmentModeResponseModel,
    RecordTrainingInstituteFeePaymentRequestModel,
    RecordTrainingInstituteFeePaymentResponseModel,
    RemoveTrainingInstituteTeacherDocumentResponseModel,
    SaveTrainingInstituteAttendanceMarksRequestModel,
    SetTrainingInstituteEnrollmentTimingsRequestModel,
    SetTrainingInstituteEnrollmentTimingsResponseModel,
    TrainingInstituteAttendanceRegisterResponseModel,
    TrainingInstituteCalendarResponseModel,
    TrainingInstituteClassChangeModel,
    TrainingInstituteClassDetailResponseModel,
    TrainingInstituteClassTokenResponseModel,
    TrainingInstituteHolidayModel,
    TrainingInstituteStudentAttendanceHistoryResponseModel,
    TrainingInstituteTeacherBatchesResponseModel,
    TrainingInstituteTeacherDocumentMetadataModel,
    TrainingInstituteTeacherResponseModel,
    UpdateTrainingInstituteBatchScheduleRequestModel,
    UpdateTrainingInstituteBatchScheduleResponseModel,
    UpdateTrainingInstituteCourseRequestModel,
    UpdateTrainingInstituteCourseResponseModel,
    UpdateTrainingInstituteStudentProfileRequestModel,
    UpdateTrainingInstituteStudentProfileResponseModel,
    UpdateTrainingInstituteTeacherProfileRequestModel,
    AddTrainingInstituteEnquirySourceRequestModel,
    BookTrainingInstituteDemoRequestModel,
    ConvertTrainingInstituteEnquiryRequestModel,
    ConvertTrainingInstituteEnquiryResponseModel,
    CreateTrainingInstituteEnquiryRequestModel,
    FindTrainingInstituteEnquiryPhoneMatchesRequestModel,
    FindTrainingInstituteEnquiryPhoneMatchesResponseModel,
    ListTrainingInstituteDemoSlotsResponseModel,
    ListTrainingInstituteDemosResponseModel,
    ListTrainingInstituteEnquiriesResponseModel,
    ListTrainingInstituteEnquirySourcesResponseModel,
    LogTrainingInstituteEnquiryFollowUpRequestModel,
    MarkTrainingInstituteDemoAttendanceRequestModel,
    MarkTrainingInstituteEnquiryNotInterestedRequestModel,
    RenameTrainingInstituteEnquirySourceRequestModel,
    ReopenTrainingInstituteEnquiryRequestModel,
    TrainingInstituteDemoModel,
    TrainingInstituteEnquiryDetailModel,
    TrainingInstituteEnquiryModel,
    TrainingInstituteEnquiryOptionsResponseModel,
    TrainingInstituteEnquirySourceModel,
    TrainingInstituteEnquirySummaryResponseModel,
    UpdateTrainingInstituteEnquiryDetailsRequestModel,
    CheckTrainingInstituteHomeworkSubmissionRequestModel,
    PostTrainingInstituteStudyMaterialRequestModel,
    SetTrainingInstituteHomeworkRequestModel,
    SubmitTrainingInstituteHomeworkRequestModel,
    TrainingInstituteAttachmentModel,
    TrainingInstituteBatchClassWorkResponseModel,
    TrainingInstituteFamilyClassWorkResponseModel,
    TrainingInstituteFamilyHomeworkModel,
    TrainingInstituteHomeworkModel,
    TrainingInstituteHomeworkSubmissionModel,
    TrainingInstituteHomeworkSubmissionsResponseModel,
    TrainingInstituteStudyMaterialModel,
    UndoTrainingInstituteHomeworkSubmissionRequestModel,
    UpdateTrainingInstituteHomeworkRequestModel,
    UpdateTrainingInstituteStudyMaterialRequestModel,
  },
);
