-- Masters for M4 (CM-404, CM-406, `modules/02`): Amenities and Common
-- Developments with their Projects, and minimal Contractors and Suppliers
-- with their Departments and Projects (ADR CM-0013 §5–6). Touches no other
-- schema (ADR-0030). Seed rows for existing Companies are the next
-- migration.
--
-- Generated by `prisma migrate diff`, then the partial unique indexes
-- Prisma cannot express.

-- CreateEnum
CREATE TYPE "construction_masters"."development_kind" AS ENUM ('amenity', 'common_development');

-- CreateTable
CREATE TABLE "construction_masters"."development_types" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "kind" "construction_masters"."development_kind" NOT NULL,
    "name" TEXT NOT NULL,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "disabled_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "development_types_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_masters"."development_projects" (
    "development_id" UUID NOT NULL,
    "project_id" UUID NOT NULL,

    CONSTRAINT "development_projects_pkey" PRIMARY KEY ("development_id","project_id")
);

-- CreateTable
CREATE TABLE "construction_masters"."contractors" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "contact_person" TEXT,
    "mobile" TEXT,
    "email" TEXT,
    "address" TEXT,
    "gstin" VARCHAR(15),
    "pan" VARCHAR(10),
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "contractors_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_masters"."contractor_departments" (
    "contractor_id" UUID NOT NULL,
    "department_id" UUID NOT NULL,

    CONSTRAINT "contractor_departments_pkey" PRIMARY KEY ("contractor_id","department_id")
);

-- CreateTable
CREATE TABLE "construction_masters"."contractor_projects" (
    "contractor_id" UUID NOT NULL,
    "project_id" UUID NOT NULL,

    CONSTRAINT "contractor_projects_pkey" PRIMARY KEY ("contractor_id","project_id")
);

-- CreateTable
CREATE TABLE "construction_masters"."suppliers" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "contact_person" TEXT,
    "mobile" TEXT,
    "email" TEXT,
    "address" TEXT,
    "gstin" VARCHAR(15),
    "pan" VARCHAR(10),
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "suppliers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_masters"."supplier_projects" (
    "supplier_id" UUID NOT NULL,
    "project_id" UUID NOT NULL,

    CONSTRAINT "supplier_projects_pkey" PRIMARY KEY ("supplier_id","project_id")
);

-- CreateIndex
CREATE INDEX "development_types_workspace_id_kind_idx" ON "construction_masters"."development_types"("workspace_id", "kind");

-- CreateIndex
CREATE INDEX "development_projects_project_id_idx" ON "construction_masters"."development_projects"("project_id");

-- CreateIndex
CREATE INDEX "contractors_workspace_id_name_idx" ON "construction_masters"."contractors"("workspace_id", "name");

-- CreateIndex
CREATE INDEX "contractor_departments_department_id_idx" ON "construction_masters"."contractor_departments"("department_id");

-- CreateIndex
CREATE INDEX "contractor_projects_project_id_idx" ON "construction_masters"."contractor_projects"("project_id");

-- CreateIndex
CREATE INDEX "suppliers_workspace_id_name_idx" ON "construction_masters"."suppliers"("workspace_id", "name");

-- CreateIndex
CREATE INDEX "supplier_projects_project_id_idx" ON "construction_masters"."supplier_projects"("project_id");

-- AddForeignKey
ALTER TABLE "construction_masters"."development_projects" ADD CONSTRAINT "development_projects_development_id_fkey" FOREIGN KEY ("development_id") REFERENCES "construction_masters"."development_types"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_masters"."contractor_departments" ADD CONSTRAINT "contractor_departments_contractor_id_fkey" FOREIGN KEY ("contractor_id") REFERENCES "construction_masters"."contractors"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_masters"."contractor_departments" ADD CONSTRAINT "contractor_departments_department_id_fkey" FOREIGN KEY ("department_id") REFERENCES "construction_masters"."departments"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_masters"."contractor_projects" ADD CONSTRAINT "contractor_projects_contractor_id_fkey" FOREIGN KEY ("contractor_id") REFERENCES "construction_masters"."contractors"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_masters"."supplier_projects" ADD CONSTRAINT "supplier_projects_supplier_id_fkey" FOREIGN KEY ("supplier_id") REFERENCES "construction_masters"."suppliers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Names unique ignoring case among live rows (per kind for developments).
CREATE UNIQUE INDEX "development_types_live_name_key" ON "construction_masters"."development_types"("workspace_id", "kind", lower("name")) WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "contractors_live_name_key" ON "construction_masters"."contractors"("workspace_id", lower("name")) WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "suppliers_live_name_key" ON "construction_masters"."suppliers"("workspace_id", lower("name")) WHERE "deleted_at" IS NULL;
