import { StatusCodes } from "http-status-codes";

import type {
  OpenApiComponents,
  OpenApiOperation,
} from "@/app/api/_lib/openapi";

import {
  AccrueConstructionHrmsLeaveBalancesRequestModel,
  AccrueConstructionHrmsLeaveBalancesResponseModel,
  AdjustConstructionHrmsLeaveBalanceRequestModel,
  ConstructionHrmsLeaveBalanceRowResponseModel,
  ConstructionHrmsMemberLeaveBalancesResponseModel,
  GetConstructionHrmsLeaveBalancesRequestModel,
  GetConstructionHrmsTeamLeaveBalancesRequestModel,
  GetConstructionHrmsTeamLeaveBalancesResponseModel,
  InitializeConstructionHrmsLeaveBalancesByStructureRequestModel,
  InitializeConstructionHrmsLeaveBalancesRequestModel,
  InitializeConstructionHrmsLeaveBalancesResponseModel,
  LEAVE_BALANCES_PATH,
  ListConstructionHrmsLeaveCreditsResponseModel,
  RunConstructionHrmsScheduledLeaveAccrualResponseModel,
} from "./leave-balances/leave-balance-models";
import {
  ConstructionHrmsLeaveExpectedUpdatedAtRequestModel,
  ConstructionHrmsLeaveIdParamsModel,
} from "./leave-route";
import {
  ConstructionHrmsLeaveAssignmentResponseModel,
  ConstructionHrmsLeaveStructureResponseModel,
  CreateConstructionHrmsLeaveAssignmentsRequestModel,
  CreateConstructionHrmsLeaveStructureRequestModel,
  LEAVE_STRUCTURES_PATH,
  ListConstructionHrmsLeaveAssignmentsRequestModel,
  ListConstructionHrmsLeaveAssignmentsResponseModel,
  ListConstructionHrmsLeaveStructuresResponseModel,
  UpdateConstructionHrmsLeaveStructureRequestModel,
} from "./leave-structures/leave-structure-models";
import {
  ConstructionHrmsLeaveTypeResponseModel,
  CreateConstructionHrmsLeaveTypeRequestModel,
  GetConstructionHrmsLeaveAccrualOptionsResponseModel,
  LEAVE_TYPES_PATH,
  ListConstructionHrmsLeaveTypesResponseModel,
  UpdateConstructionHrmsLeaveTypeRequestModel,
} from "./leave-types/leave-type-models";
import {
  ApplyConstructionHrmsLeaveRequestModel,
  ApproveConstructionHrmsLeaveRequestModel,
  ConstructionHrmsLeaveRequestResponseModel,
  GetConstructionHrmsLeaveOptionsResponseModel,
  GetConstructionHrmsTeamLeaveReportResponseModel,
  LEAVES_PATH,
  ListConstructionHrmsLeaveApprovalsRequestModel,
  ListConstructionHrmsLeaveApprovalsResponseModel,
  ListConstructionHrmsLeaveRequestsResponseModel,
  ListConstructionHrmsMyLeavesRequestModel,
  ListConstructionHrmsTeamLeavesRequestModel,
  PreviewConstructionHrmsLeaveRequestModel,
  PreviewConstructionHrmsLeaveResponseModel,
  RejectConstructionHrmsLeaveRequestModel,
  RequestConstructionHrmsLeaveCancellationRequestModel,
  WithdrawConstructionHrmsLeaveRequestModel,
} from "./leaves/leave-models";

const HRMS = ["Construction · HRMS"];

const READ = [
  StatusCodes.BAD_REQUEST,
  StatusCodes.UNAUTHORIZED,
  StatusCodes.FORBIDDEN,
  StatusCodes.NOT_FOUND,
];

const WRITE = [...READ, StatusCodes.CONFLICT, StatusCodes.PAYMENT_REQUIRED];

/** Leave models (CM-310 … CM-313). */
export const leaveOpenApiComponents: OpenApiComponents = {
  ConstructionHrmsLeaveIdParamsModel,
  ConstructionHrmsLeaveExpectedUpdatedAtRequestModel,
  CreateConstructionHrmsLeaveTypeRequestModel,
  UpdateConstructionHrmsLeaveTypeRequestModel,
  ConstructionHrmsLeaveTypeResponseModel,
  ListConstructionHrmsLeaveTypesResponseModel,
  GetConstructionHrmsLeaveAccrualOptionsResponseModel,
  CreateConstructionHrmsLeaveStructureRequestModel,
  UpdateConstructionHrmsLeaveStructureRequestModel,
  ConstructionHrmsLeaveStructureResponseModel,
  ListConstructionHrmsLeaveStructuresResponseModel,
  ListConstructionHrmsLeaveAssignmentsRequestModel,
  CreateConstructionHrmsLeaveAssignmentsRequestModel,
  ConstructionHrmsLeaveAssignmentResponseModel,
  ListConstructionHrmsLeaveAssignmentsResponseModel,
  GetConstructionHrmsLeaveBalancesRequestModel,
  GetConstructionHrmsTeamLeaveBalancesRequestModel,
  ConstructionHrmsLeaveBalanceRowResponseModel,
  ConstructionHrmsMemberLeaveBalancesResponseModel,
  GetConstructionHrmsTeamLeaveBalancesResponseModel,
  ListConstructionHrmsLeaveCreditsResponseModel,
  InitializeConstructionHrmsLeaveBalancesRequestModel,
  InitializeConstructionHrmsLeaveBalancesByStructureRequestModel,
  InitializeConstructionHrmsLeaveBalancesResponseModel,
  AccrueConstructionHrmsLeaveBalancesRequestModel,
  AccrueConstructionHrmsLeaveBalancesResponseModel,
  RunConstructionHrmsScheduledLeaveAccrualResponseModel,
  AdjustConstructionHrmsLeaveBalanceRequestModel,
  PreviewConstructionHrmsLeaveRequestModel,
  PreviewConstructionHrmsLeaveResponseModel,
  ApplyConstructionHrmsLeaveRequestModel,
  ListConstructionHrmsMyLeavesRequestModel,
  ListConstructionHrmsLeaveApprovalsRequestModel,
  ListConstructionHrmsTeamLeavesRequestModel,
  WithdrawConstructionHrmsLeaveRequestModel,
  RequestConstructionHrmsLeaveCancellationRequestModel,
  ApproveConstructionHrmsLeaveRequestModel,
  RejectConstructionHrmsLeaveRequestModel,
  ConstructionHrmsLeaveRequestResponseModel,
  ListConstructionHrmsLeaveRequestsResponseModel,
  ListConstructionHrmsLeaveApprovalsResponseModel,
  GetConstructionHrmsLeaveOptionsResponseModel,
  GetConstructionHrmsTeamLeaveReportResponseModel,
};

const TYPE = `${LEAVE_TYPES_PATH}/{id}`;
const STRUCTURE = `${LEAVE_STRUCTURES_PATH}/{id}`;
const LEAVE = `${LEAVES_PATH}/{id}`;

/**
 * Leave routes. Types, structures, assignments, initialise, accrue and
 * adjust are menu `hrms.leave_structures`; balances and requests are
 * `hrms.leaves` (own with read, others with View All; decisions with
 * approve / reject).
 */
export const leaveOpenApiOperations: OpenApiOperation[] = [
  // Leave types (CM-310)
  {
    method: "get",
    path: LEAVE_TYPES_PATH,
    summary: "Leave types, inactive ones included (hrms.leave_structures read)",
    tags: HRMS,
    successStatus: StatusCodes.OK,
    successDescription: "Leave types by name",
    successSchema: ListConstructionHrmsLeaveTypesResponseModel,
    errors: READ,
  },
  {
    method: "post",
    path: LEAVE_TYPES_PATH,
    summary:
      "Add a leave type (create; accrual fields required when periodic, LEAVE_TYPE_NAME_IN_USE 409)",
    tags: HRMS,
    body: CreateConstructionHrmsLeaveTypeRequestModel,
    successStatus: StatusCodes.CREATED,
    successDescription: "The leave type",
    successSchema: ConstructionHrmsLeaveTypeResponseModel,
    errors: WRITE,
  },
  {
    method: "get",
    path: `${LEAVE_TYPES_PATH}/accrual-options`,
    summary: "Accrual modes and frequencies (ADR CM-0012 §7)",
    tags: HRMS,
    successStatus: StatusCodes.OK,
    successDescription: "The choices",
    successSchema: GetConstructionHrmsLeaveAccrualOptionsResponseModel,
    errors: READ,
  },
  {
    method: "get",
    path: TYPE,
    summary: "One leave type",
    tags: HRMS,
    params: ConstructionHrmsLeaveIdParamsModel,
    successStatus: StatusCodes.OK,
    successDescription: "The leave type",
    successSchema: ConstructionHrmsLeaveTypeResponseModel,
    errors: READ,
  },
  {
    method: "post",
    path: `${TYPE}/update`,
    summary: "Replace a leave type's settings (update; LEAVE_TYPE_CHANGED 409)",
    tags: HRMS,
    params: ConstructionHrmsLeaveIdParamsModel,
    body: UpdateConstructionHrmsLeaveTypeRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "The leave type",
    successSchema: ConstructionHrmsLeaveTypeResponseModel,
    errors: WRITE,
  },
  ...(["activate", "deactivate"] as const).map((verb): OpenApiOperation => ({
    method: "post",
    path: `${TYPE}/${verb}`,
    summary:
      verb === "activate"
        ? "Offer a leave type again (update)"
        : "Stop new requests of a leave type (update); balances and requests stay",
    tags: HRMS,
    params: ConstructionHrmsLeaveIdParamsModel,
    body: ConstructionHrmsLeaveExpectedUpdatedAtRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "The leave type",
    successSchema: ConstructionHrmsLeaveTypeResponseModel,
    errors: WRITE,
  })),
  {
    method: "post",
    path: `${TYPE}/delete`,
    summary:
      "Delete a leave type nobody uses (delete; LEAVE_TYPE_IN_USE 409 — deactivate instead)",
    tags: HRMS,
    params: ConstructionHrmsLeaveIdParamsModel,
    body: ConstructionHrmsLeaveExpectedUpdatedAtRequestModel,
    successStatus: StatusCodes.NO_CONTENT,
    successDescription: "Deleted",
    errors: WRITE,
  },

  // Structures and assignments (CM-311)
  {
    method: "get",
    path: LEAVE_STRUCTURES_PATH,
    summary: "Leave structures with their lines (hrms.leave_structures read)",
    tags: HRMS,
    successStatus: StatusCodes.OK,
    successDescription: "Structures by name",
    successSchema: ListConstructionHrmsLeaveStructuresResponseModel,
    errors: READ,
  },
  {
    method: "post",
    path: LEAVE_STRUCTURES_PATH,
    summary: "Add a leave structure (create)",
    tags: HRMS,
    body: CreateConstructionHrmsLeaveStructureRequestModel,
    successStatus: StatusCodes.CREATED,
    successDescription: "The structure",
    successSchema: ConstructionHrmsLeaveStructureResponseModel,
    errors: WRITE,
  },
  {
    method: "get",
    path: STRUCTURE,
    summary: "One leave structure",
    tags: HRMS,
    params: ConstructionHrmsLeaveIdParamsModel,
    successStatus: StatusCodes.OK,
    successDescription: "The structure",
    successSchema: ConstructionHrmsLeaveStructureResponseModel,
    errors: READ,
  },
  {
    method: "post",
    path: `${STRUCTURE}/update`,
    summary: "Replace a structure's name and lines (update)",
    tags: HRMS,
    params: ConstructionHrmsLeaveIdParamsModel,
    body: UpdateConstructionHrmsLeaveStructureRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "The structure",
    successSchema: ConstructionHrmsLeaveStructureResponseModel,
    errors: WRITE,
  },
  {
    method: "post",
    path: `${STRUCTURE}/delete`,
    summary:
      "Delete a structure nobody is assigned (delete; LEAVE_STRUCTURE_IN_USE 409)",
    tags: HRMS,
    params: ConstructionHrmsLeaveIdParamsModel,
    body: ConstructionHrmsLeaveExpectedUpdatedAtRequestModel,
    successStatus: StatusCodes.NO_CONTENT,
    successDescription: "Deleted",
    errors: WRITE,
  },
  {
    method: "get",
    path: `${LEAVE_STRUCTURES_PATH}/assignments`,
    summary: "Structure assignments, by member and structure",
    tags: HRMS,
    query: ListConstructionHrmsLeaveAssignmentsRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Assignments",
    successSchema: ListConstructionHrmsLeaveAssignmentsResponseModel,
    errors: READ,
  },
  {
    method: "post",
    path: `${LEAVE_STRUCTURES_PATH}/assignments`,
    summary:
      "Assign a structure to Team Members from a date (create; LEAVE_ASSIGNMENT_EXISTS 409)",
    tags: HRMS,
    body: CreateConstructionHrmsLeaveAssignmentsRequestModel,
    successStatus: StatusCodes.CREATED,
    successDescription: "The new assignments",
    successSchema: ListConstructionHrmsLeaveAssignmentsResponseModel,
    errors: WRITE,
  },
  {
    method: "post",
    path: `${LEAVE_STRUCTURES_PATH}/assignments/{id}/delete`,
    summary: "Remove a structure assignment (delete)",
    tags: HRMS,
    params: ConstructionHrmsLeaveIdParamsModel,
    successStatus: StatusCodes.NO_CONTENT,
    successDescription: "Removed",
    errors: WRITE,
  },

  // Balances (CM-311)
  {
    method: "get",
    path: LEAVE_BALANCES_PATH,
    summary:
      "A member's balances per leave type from the ledger (hrms.leaves read; another member needs View All)",
    tags: HRMS,
    query: GetConstructionHrmsLeaveBalancesRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Balances",
    successSchema: ConstructionHrmsMemberLeaveBalancesResponseModel,
    errors: READ,
  },
  {
    method: "get",
    path: `${LEAVE_BALANCES_PATH}/team`,
    summary: "Every active Team Member's balances (hrms.leaves View All)",
    tags: HRMS,
    query: GetConstructionHrmsTeamLeaveBalancesRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Balances per member",
    successSchema: GetConstructionHrmsTeamLeaveBalancesResponseModel,
    errors: READ,
  },
  {
    method: "get",
    path: `${LEAVE_BALANCES_PATH}/accruals`,
    summary:
      "Credit history: initial, monthly, carry-forward and adjustment entries, newest first",
    tags: HRMS,
    query: GetConstructionHrmsLeaveBalancesRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Credits",
    successSchema: ListConstructionHrmsLeaveCreditsResponseModel,
    errors: READ,
  },
  {
    method: "post",
    path: `${LEAVE_BALANCES_PATH}/initialize`,
    summary:
      "Open a leave year's balances for Team Members (hrms.leave_structures update); idempotent, carries forward",
    tags: HRMS,
    body: InitializeConstructionHrmsLeaveBalancesRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "What was opened",
    successSchema: InitializeConstructionHrmsLeaveBalancesResponseModel,
    errors: WRITE,
  },
  {
    method: "post",
    path: `${LEAVE_BALANCES_PATH}/initialize-by-structure`,
    summary:
      "Open balances for everyone whose structure in force is this one (LEAVE_STRUCTURE_NOT_ASSIGNED 400)",
    tags: HRMS,
    body: InitializeConstructionHrmsLeaveBalancesByStructureRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "What was opened",
    successSchema: InitializeConstructionHrmsLeaveBalancesResponseModel,
    errors: WRITE,
  },
  {
    method: "post",
    path: `${LEAVE_BALANCES_PATH}/accrue`,
    summary:
      "Accrue now: post every monthly credit due up to today, capped and once per period (LEAVE_ACCRUAL_DISABLED 409)",
    tags: HRMS,
    body: AccrueConstructionHrmsLeaveBalancesRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Credits posted",
    successSchema: AccrueConstructionHrmsLeaveBalancesResponseModel,
    errors: WRITE,
  },
  {
    method: "get",
    path: `${LEAVE_BALANCES_PATH}/accrue/scheduled`,
    summary:
      "Scheduled monthly accrual for every Company with it on; `Authorization: Bearer <CRON_SECRET>` (Vercel Cron), no Session",
    tags: HRMS,
    security: false,
    successStatus: StatusCodes.OK,
    successDescription: "Companies run and credits posted",
    successSchema: RunConstructionHrmsScheduledLeaveAccrualResponseModel,
    errors: [StatusCodes.UNAUTHORIZED, StatusCodes.SERVICE_UNAVAILABLE],
  },
  {
    method: "post",
    path: `${LEAVE_BALANCES_PATH}/adjust`,
    summary:
      "Adjust a balance with a reason, e.g. credit Compensatory Off (hrms.leave_structures update; LEAVE_ADJUSTMENT_BELOW_ZERO 400)",
    tags: HRMS,
    body: AdjustConstructionHrmsLeaveBalanceRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "The balance after the adjustment",
    successSchema: ConstructionHrmsLeaveBalanceRowResponseModel,
    errors: WRITE,
  },

  // Requests (CM-312, CM-313)
  {
    method: "get",
    path: LEAVES_PATH,
    summary: "My Leaves: your own requests, newest first (hrms.leaves read)",
    tags: HRMS,
    query: ListConstructionHrmsMyLeavesRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Requests",
    successSchema: ListConstructionHrmsLeaveRequestsResponseModel,
    errors: READ,
  },
  {
    method: "post",
    path: LEAVES_PATH,
    summary:
      "Apply for leave (create; another member needs View All). LEAVE_REASON_TOO_SHORT, LEAVE_MAX_CONSECUTIVE_EXCEEDED, LEAVE_BALANCE_INSUFFICIENT, LEAVE_SPANS_YEARS 400; LEAVE_OVERLAPS, MONTH_LOCKED 409; back-dated 403",
    tags: HRMS,
    body: ApplyConstructionHrmsLeaveRequestModel,
    successStatus: StatusCodes.CREATED,
    successDescription: "The request, pending or approved",
    successSchema: ConstructionHrmsLeaveRequestResponseModel,
    errors: WRITE,
  },
  {
    method: "post",
    path: `${LEAVES_PATH}/preview`,
    summary: "Day breakdown, total and balance for Apply Leave; writes nothing",
    tags: HRMS,
    body: PreviewConstructionHrmsLeaveRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "The preview",
    successSchema: PreviewConstructionHrmsLeaveResponseModel,
    errors: READ,
  },
  {
    method: "get",
    path: `${LEAVES_PATH}/options`,
    summary:
      "Your leave permissions, the active leave types and, when you may act for others, the Team Members",
    tags: HRMS,
    successStatus: StatusCodes.OK,
    successDescription: "Options",
    successSchema: GetConstructionHrmsLeaveOptionsResponseModel,
    errors: READ,
  },
  {
    method: "get",
    path: `${LEAVES_PATH}/approvals`,
    summary:
      "Leave Approvals tab: pending, approved, rejected or cancel requests, with counts (approve or reject)",
    tags: HRMS,
    query: ListConstructionHrmsLeaveApprovalsRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Requests",
    successSchema: ListConstructionHrmsLeaveApprovalsResponseModel,
    errors: READ,
  },
  {
    method: "get",
    path: `${LEAVES_PATH}/team`,
    summary: "Team Leaves: live requests with a day in the range (View All)",
    tags: HRMS,
    query: ListConstructionHrmsTeamLeavesRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Requests",
    successSchema: ListConstructionHrmsLeaveRequestsResponseModel,
    errors: READ,
  },
  {
    method: "get",
    path: `${LEAVES_PATH}/report/team`,
    summary: "Team leave report: approved days by member and type (report)",
    tags: HRMS,
    query: ListConstructionHrmsTeamLeavesRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "Rows per member",
    successSchema: GetConstructionHrmsTeamLeaveReportResponseModel,
    errors: READ,
  },
  {
    method: "get",
    path: LEAVE,
    summary: "Leave Details: your own, or any with View All or as an approver",
    tags: HRMS,
    params: ConstructionHrmsLeaveIdParamsModel,
    successStatus: StatusCodes.OK,
    successDescription: "The request",
    successSchema: ConstructionHrmsLeaveRequestResponseModel,
    errors: READ,
  },
  ...[
    {
      verb: "withdraw",
      body: WithdrawConstructionHrmsLeaveRequestModel,
      summary:
        "Withdraw a pending request; the reserved days are released (create)",
    },
    {
      verb: "request-cancellation",
      body: RequestConstructionHrmsLeaveCancellationRequestModel,
      summary:
        "Ask to cancel approved leave with a reason; immediate when the type needs no approval (create)",
    },
    {
      verb: "approve",
      body: ApproveConstructionHrmsLeaveRequestModel,
      summary:
        "Approve the waiting level (approve; never your own unless Owner — LEAVE_OWN_REQUEST 403; LEAVE_REQUEST_CHANGED 409)",
    },
    {
      verb: "reject",
      body: RejectConstructionHrmsLeaveRequestModel,
      summary: "Reject with a reason; the reserved days are released (reject)",
    },
    {
      verb: "approve-cancellation",
      body: ApproveConstructionHrmsLeaveRequestModel,
      summary:
        "Approve a cancellation request; the days are restored (approve)",
    },
    {
      verb: "reject-cancellation",
      body: RejectConstructionHrmsLeaveRequestModel,
      summary:
        "Refuse a cancellation request with a reason; stays approved (reject)",
    },
  ].map((item): OpenApiOperation => ({
    method: "post",
    path: `${LEAVE}/${item.verb}`,
    summary: item.summary,
    tags: HRMS,
    params: ConstructionHrmsLeaveIdParamsModel,
    body: item.body,
    successStatus: StatusCodes.OK,
    successDescription: "The request",
    successSchema: ConstructionHrmsLeaveRequestResponseModel,
    errors: WRITE,
  })),
];
