-- Construction Management's first migration (ADR-0040, ADR CM-0001).
-- Construction Management and Whiteboard used to share one migration history;
-- each database now has only its own schemas. This replaces the shared
-- history from 20260909000000 to 20261012010000 (see git history for each
-- step and its reasons).
--
-- Generated by `prisma migrate diff --from-empty`, then the hand-written
-- section at the end, which Prisma cannot express.

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "construction_labour";

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "construction_masters";

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "construction_organization";

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "construction_projects";

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "construction_reporting";

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "identity";

-- CreateEnum
CREATE TYPE "construction_labour"."wage_type" AS ENUM ('daily', 'monthly');

-- CreateEnum
CREATE TYPE "construction_labour"."gender" AS ENUM ('male', 'female', 'other');

-- CreateEnum
CREATE TYPE "construction_labour"."attendance_status" AS ENUM ('present', 'half_day', 'absent', 'on_leave', 'holiday');

-- CreateEnum
CREATE TYPE "construction_labour"."party_type" AS ENUM ('labour', 'vendor');

-- CreateEnum
CREATE TYPE "construction_labour"."ledger_entry_kind" AS ENUM ('opening', 'earned', 'overtime', 'payment', 'advance');

-- CreateEnum
CREATE TYPE "construction_labour"."payment_kind" AS ENUM ('payment', 'advance');

-- CreateEnum
CREATE TYPE "construction_labour"."payment_mode" AS ENUM ('cash', 'bank');

-- CreateEnum
CREATE TYPE "construction_labour"."document_owner" AS ENUM ('labour', 'vendor');

-- CreateEnum
CREATE TYPE "construction_organization"."member_type" AS ENUM ('normal', 'hrms');

-- CreateEnum
CREATE TYPE "construction_organization"."team_member_status" AS ENUM ('joining_pending', 'active', 'rejected');

-- CreateEnum
CREATE TYPE "construction_organization"."subscription_order_kind" AS ENUM ('new', 'extend', 'upgrade', 'add_ons');

-- CreateEnum
CREATE TYPE "construction_organization"."subscription_order_status" AS ENUM ('created', 'paid', 'failed');

-- CreateEnum
CREATE TYPE "construction_projects"."project_status" AS ENUM ('not_started', 'ongoing', 'on_hold', 'completed');

-- CreateEnum
CREATE TYPE "construction_projects"."document_kind" AS ENUM ('tender', 'quotation', 'loa', 'client_order', 'agreement', 'other');

-- CreateEnum
CREATE TYPE "construction_reporting"."report_kind" AS ENUM ('labour_attendance', 'labour_payment', 'labour_month', 'vendor_attendance', 'muster_roll');

-- CreateEnum
CREATE TYPE "construction_reporting"."job_status" AS ENUM ('queued', 'running', 'done', 'failed');

-- CreateTable
CREATE TABLE "construction_labour"."labours" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "labour_code" TEXT,
    "father_name" TEXT,
    "joining_date" DATE NOT NULL,
    "wage_type" "construction_labour"."wage_type" NOT NULL,
    "wage_per_day" INTEGER,
    "wage_per_month" INTEGER,
    "overtime_wage_per_hour" INTEGER NOT NULL,
    "weekly_holidays" INTEGER[],
    "uan_number" VARCHAR(12),
    "esic_number" VARCHAR(17),
    "aadhaar_encrypted" TEXT,
    "aadhaar_last4" CHAR(4),
    "labour_category_id" UUID,
    "supervisor_id" UUID,
    "contact_number" TEXT,
    "gender" "construction_labour"."gender",
    "photo_key" TEXT,
    "current_project_id" UUID NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "labours_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_labour"."labour_transfers" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "labour_id" UUID NOT NULL,
    "from_project_id" UUID,
    "to_project_id" UUID NOT NULL,
    "transfer_date" DATE NOT NULL,
    "remark" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,

    CONSTRAINT "labour_transfers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_labour"."labour_attendance" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "project_id" UUID NOT NULL,
    "labour_id" UUID NOT NULL,
    "attendance_date" DATE NOT NULL,
    "status" "construction_labour"."attendance_status" NOT NULL,
    "is_paid_leave" BOOLEAN NOT NULL DEFAULT false,
    "shift" TEXT,
    "supervisor_id" UUID,
    "wage_type" "construction_labour"."wage_type" NOT NULL,
    "wage_rate" INTEGER NOT NULL,
    "earned" INTEGER NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "labour_attendance_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_labour"."labour_overtime" (
    "id" UUID NOT NULL,
    "attendance_id" UUID NOT NULL,
    "labour_category_id" UUID,
    "hours" DECIMAL(4,2) NOT NULL,
    "rate_per_hour" INTEGER NOT NULL,
    "amount" INTEGER NOT NULL,

    CONSTRAINT "labour_overtime_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_labour"."vendors" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "joining_date" DATE NOT NULL,
    "contact_number" TEXT,
    "address" TEXT,
    "photo_key" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "vendors_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_labour"."vendor_projects" (
    "vendor_id" UUID NOT NULL,
    "project_id" UUID NOT NULL,

    CONSTRAINT "vendor_projects_pkey" PRIMARY KEY ("vendor_id","project_id")
);

-- CreateTable
CREATE TABLE "construction_labour"."vendor_shifts" (
    "id" UUID NOT NULL,
    "vendor_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "start_time" CHAR(5),
    "end_time" CHAR(5),
    "sort_order" INTEGER NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),

    CONSTRAINT "vendor_shifts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_labour"."vendor_rates" (
    "id" UUID NOT NULL,
    "shift_id" UUID NOT NULL,
    "labour_category_id" UUID NOT NULL,
    "rate_per_day" INTEGER NOT NULL,
    "overtime_per_hour" INTEGER NOT NULL,

    CONSTRAINT "vendor_rates_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_labour"."vendor_attendance" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "project_id" UUID NOT NULL,
    "vendor_id" UUID NOT NULL,
    "attendance_date" DATE NOT NULL,
    "total_pay" INTEGER NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "vendor_attendance_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_labour"."vendor_attendance_lines" (
    "id" UUID NOT NULL,
    "attendance_id" UUID NOT NULL,
    "shift_id" UUID NOT NULL,
    "shift_name" TEXT NOT NULL,
    "labour_category_id" UUID NOT NULL,
    "full_day_count" INTEGER NOT NULL,
    "half_day_count" INTEGER NOT NULL,
    "overtime_hours" DECIMAL(6,2) NOT NULL DEFAULT 0,
    "rate_per_day" INTEGER NOT NULL,
    "overtime_per_hour" INTEGER NOT NULL,
    "amount" INTEGER NOT NULL,

    CONSTRAINT "vendor_attendance_lines_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_labour"."ledger_entries" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "party_type" "construction_labour"."party_type" NOT NULL,
    "party_id" UUID NOT NULL,
    "project_id" UUID,
    "entry_date" DATE NOT NULL,
    "kind" "construction_labour"."ledger_entry_kind" NOT NULL,
    "amount" INTEGER NOT NULL,
    "source_type" TEXT NOT NULL,
    "source_id" UUID NOT NULL,
    "reverses_entry_id" UUID,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,

    CONSTRAINT "ledger_entries_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_labour"."wage_payments" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "party_type" "construction_labour"."party_type" NOT NULL,
    "party_id" UUID NOT NULL,
    "project_id" UUID NOT NULL,
    "payment_date" DATE NOT NULL,
    "kind" "construction_labour"."payment_kind" NOT NULL,
    "mode" "construction_labour"."payment_mode" NOT NULL,
    "reference" TEXT,
    "amount" INTEGER NOT NULL,
    "paid_by_member_id" UUID,
    "remarks" TEXT,
    "document_key" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "wage_payments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_labour"."documents" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "owner_type" "construction_labour"."document_owner" NOT NULL,
    "owner_id" UUID NOT NULL,
    "file_key" TEXT NOT NULL,
    "file_name" TEXT NOT NULL,
    "content_type" TEXT NOT NULL,
    "bytes" INTEGER NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),

    CONSTRAINT "documents_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_masters"."labour_categories" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "disabled_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "labour_categories_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_masters"."departments" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "disabled_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "departments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_masters"."supervisors" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "mobile" TEXT,
    "team_member_id" UUID,
    "disabled_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "supervisors_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_organization"."company_profiles" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "name" TEXT NOT NULL DEFAULT '',
    "mobile" TEXT,
    "email" TEXT,
    "country" CHAR(2) NOT NULL DEFAULT 'IN',
    "gstin" VARCHAR(15),
    "pan" VARCHAR(10),
    "address" TEXT,
    "currency" CHAR(3) NOT NULL DEFAULT 'INR',
    "is_indian" BOOLEAN NOT NULL DEFAULT true,
    "timezone" TEXT NOT NULL DEFAULT 'Asia/Kolkata',
    "logo_key" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),

    CONSTRAINT "company_profiles_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_organization"."audit_events" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "actor_user_id" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "entity_type" TEXT NOT NULL,
    "entity_id" TEXT NOT NULL,
    "before" JSONB,
    "after" JSONB,
    "occurred_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "audit_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_organization"."subscriptions" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "plan_code" TEXT NOT NULL,
    "starts_at" TIMESTAMPTZ(3) NOT NULL,
    "ends_at" TIMESTAMPTZ(3) NOT NULL,
    "auto_renew" BOOLEAN NOT NULL DEFAULT false,
    "add_ons" JSONB NOT NULL DEFAULT '{}',
    "paid_value" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "subscriptions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_organization"."designations" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "permission_template" JSONB,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),

    CONSTRAINT "designations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_organization"."member_menu_permissions" (
    "workspace_id" TEXT NOT NULL,
    "member_id" UUID NOT NULL,
    "menu" TEXT NOT NULL,
    "flags" INTEGER NOT NULL,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" TEXT NOT NULL,

    CONSTRAINT "member_menu_permissions_pkey" PRIMARY KEY ("member_id","menu")
);

-- CreateTable
CREATE TABLE "construction_organization"."team_members" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "user_id" TEXT,
    "name" TEXT NOT NULL,
    "designation_id" UUID NOT NULL,
    "mobile" TEXT,
    "email" TEXT,
    "address" TEXT,
    "aadhaar_encrypted" TEXT,
    "aadhaar_last4" CHAR(4),
    "pan_encrypted" TEXT,
    "pan_last4" CHAR(4),
    "emergency_contact" TEXT,
    "photo_key" TEXT,
    "member_type" "construction_organization"."member_type" NOT NULL DEFAULT 'normal',
    "is_owner" BOOLEAN NOT NULL DEFAULT false,
    "status" "construction_organization"."team_member_status" NOT NULL DEFAULT 'joining_pending',
    "invite_token" TEXT,
    "invited_at" TIMESTAMPTZ(3),
    "joined_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),

    CONSTRAINT "team_members_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_organization"."team_member_projects" (
    "member_id" UUID NOT NULL,
    "project_id" TEXT NOT NULL,

    CONSTRAINT "team_member_projects_pkey" PRIMARY KEY ("member_id","project_id")
);

-- CreateTable
CREATE TABLE "construction_organization"."backdated_entry_policies" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "create_days" INTEGER NOT NULL,
    "create_override_designation_ids" UUID[],
    "edit_days" INTEGER NOT NULL,
    "edit_override_designation_ids" UUID[],
    "financial_closing_date" DATE,
    "modules" JSONB NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,

    CONSTRAINT "backdated_entry_policies_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_organization"."sequence_rules" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "module" TEXT NOT NULL,
    "project_id" TEXT,
    "prefix" TEXT NOT NULL,
    "project_token" TEXT NOT NULL DEFAULT '',
    "start_number" INTEGER NOT NULL,
    "padding" INTEGER NOT NULL DEFAULT 5,
    "separator" TEXT NOT NULL DEFAULT '/',
    "fiscal_year_token" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),

    CONSTRAINT "sequence_rules_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_organization"."sequence_counters" (
    "rule_id" UUID NOT NULL,
    "fiscal_year" INTEGER NOT NULL,
    "last_number" INTEGER NOT NULL,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "sequence_counters_pkey" PRIMARY KEY ("rule_id","fiscal_year")
);

-- CreateTable
CREATE TABLE "construction_organization"."stored_files" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "kind" TEXT NOT NULL,
    "content_type" TEXT NOT NULL,
    "bytes" INTEGER NOT NULL,
    "created_by" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(3),

    CONSTRAINT "stored_files_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_organization"."subscription_orders" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "kind" "construction_organization"."subscription_order_kind" NOT NULL,
    "plan_code" TEXT NOT NULL,
    "plan_name" TEXT NOT NULL,
    "months" INTEGER,
    "days" INTEGER,
    "add_ons" JSONB NOT NULL,
    "lines" JSONB NOT NULL,
    "catalogue_version" INTEGER NOT NULL,
    "currency" CHAR(3) NOT NULL DEFAULT 'INR',
    "sub_total" INTEGER NOT NULL,
    "last_plan_discount" INTEGER NOT NULL,
    "taxable_amount" INTEGER NOT NULL,
    "cgst" INTEGER NOT NULL,
    "sgst" INTEGER NOT NULL,
    "igst" INTEGER NOT NULL,
    "total" INTEGER NOT NULL,
    "starts_at" TIMESTAMPTZ(3) NOT NULL,
    "ends_at" TIMESTAMPTZ(3) NOT NULL,
    "billing_name" TEXT NOT NULL,
    "billing_address" TEXT NOT NULL,
    "billing_state_code" CHAR(2) NOT NULL,
    "billing_gstin" VARCHAR(15),
    "seller" JSONB NOT NULL,
    "gateway" TEXT NOT NULL DEFAULT 'razorpay',
    "gateway_order_id" TEXT NOT NULL,
    "gateway_payment_id" TEXT,
    "status" "construction_organization"."subscription_order_status" NOT NULL DEFAULT 'created',
    "invoice_number" TEXT,
    "created_by" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "paid_at" TIMESTAMPTZ(3),
    "failed_at" TIMESTAMPTZ(3),

    CONSTRAINT "subscription_orders_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_organization"."subscription_invoice_counters" (
    "fiscal_year" TEXT NOT NULL,
    "last_number" INTEGER NOT NULL,

    CONSTRAINT "subscription_invoice_counters_pkey" PRIMARY KEY ("fiscal_year")
);

-- CreateTable
CREATE TABLE "construction_projects"."projects" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "status" "construction_projects"."project_status" NOT NULL DEFAULT 'ongoing',
    "address" TEXT,
    "start_date" DATE,
    "end_date" DATE,
    "client_name" TEXT,
    "client_phone" TEXT,
    "tender_ref" TEXT,
    "quotation_no" TEXT,
    "quotation_date" DATE,
    "loa_no" TEXT,
    "loa_date" DATE,
    "client_order_no" TEXT,
    "client_order_date" DATE,
    "agreement_no" TEXT,
    "agreement_date" DATE,
    "order_value" BIGINT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "projects_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_projects"."custom_fields" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "project_id" UUID NOT NULL,
    "label" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "position" INTEGER NOT NULL,

    CONSTRAINT "custom_fields_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_projects"."documents" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "project_id" UUID NOT NULL,
    "kind" "construction_projects"."document_kind" NOT NULL,
    "file_key" TEXT NOT NULL,
    "file_name" TEXT NOT NULL,
    "content_type" TEXT NOT NULL,
    "bytes" INTEGER NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "documents_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_reporting"."report_jobs" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "project_id" UUID,
    "kind" "construction_reporting"."report_kind" NOT NULL,
    "params" JSONB NOT NULL,
    "status" "construction_reporting"."job_status" NOT NULL DEFAULT 'queued',
    "includes_money" BOOLEAN NOT NULL DEFAULT false,
    "xlsx_key" TEXT,
    "pdf_key" TEXT,
    "file_name" TEXT,
    "error" TEXT,
    "requested_by" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "started_at" TIMESTAMPTZ(3),
    "finished_at" TIMESTAMPTZ(3),

    CONSTRAINT "report_jobs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "identity"."users" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "email_verified" BOOLEAN NOT NULL DEFAULT false,
    "image" TEXT,
    "phone_number" TEXT,
    "phone_number_verified" BOOLEAN,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "identity"."sessions" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "token" TEXT NOT NULL,
    "expires_at" TIMESTAMP(3) NOT NULL,
    "ip_address" TEXT,
    "user_agent" TEXT,
    "active_workspace_id" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "identity"."accounts" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "account_id" TEXT NOT NULL,
    "provider_id" TEXT NOT NULL,
    "access_token" TEXT,
    "refresh_token" TEXT,
    "id_token" TEXT,
    "access_token_expires_at" TIMESTAMP(3),
    "refresh_token_expires_at" TIMESTAMP(3),
    "scope" TEXT,
    "password" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "accounts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "identity"."verifications" (
    "id" TEXT NOT NULL,
    "identifier" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "expires_at" TIMESTAMP(3) NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "verifications_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "identity"."workspaces" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "logo" TEXT,
    "metadata" TEXT,
    "institution_type" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "workspaces_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "identity"."workspace_members" (
    "id" TEXT NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "workspace_members_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "identity"."workspace_invitations" (
    "id" TEXT NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "role" TEXT,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "expires_at" TIMESTAMP(3) NOT NULL,
    "inviter_id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "workspace_invitations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "identity"."rate_limits" (
    "id" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "count" INTEGER NOT NULL,
    "last_request" BIGINT NOT NULL,

    CONSTRAINT "rate_limits_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "labours_workspace_id_current_project_id_idx" ON "construction_labour"."labours"("workspace_id", "current_project_id");

-- CreateIndex
CREATE INDEX "labours_workspace_id_name_idx" ON "construction_labour"."labours"("workspace_id", "name");

-- CreateIndex
CREATE INDEX "labour_transfers_labour_id_transfer_date_idx" ON "construction_labour"."labour_transfers"("labour_id", "transfer_date");

-- CreateIndex
CREATE INDEX "labour_transfers_workspace_id_to_project_id_idx" ON "construction_labour"."labour_transfers"("workspace_id", "to_project_id");

-- CreateIndex
CREATE INDEX "labour_attendance_workspace_id_project_id_attendance_date_idx" ON "construction_labour"."labour_attendance"("workspace_id", "project_id", "attendance_date");

-- CreateIndex
CREATE INDEX "labour_attendance_labour_id_attendance_date_idx" ON "construction_labour"."labour_attendance"("labour_id", "attendance_date");

-- CreateIndex
CREATE INDEX "labour_overtime_attendance_id_idx" ON "construction_labour"."labour_overtime"("attendance_id");

-- CreateIndex
CREATE INDEX "vendors_workspace_id_name_idx" ON "construction_labour"."vendors"("workspace_id", "name");

-- CreateIndex
CREATE INDEX "vendor_projects_project_id_idx" ON "construction_labour"."vendor_projects"("project_id");

-- CreateIndex
CREATE INDEX "vendor_shifts_vendor_id_idx" ON "construction_labour"."vendor_shifts"("vendor_id");

-- CreateIndex
CREATE UNIQUE INDEX "vendor_rates_shift_id_labour_category_id_key" ON "construction_labour"."vendor_rates"("shift_id", "labour_category_id");

-- CreateIndex
CREATE INDEX "vendor_attendance_workspace_id_project_id_attendance_date_idx" ON "construction_labour"."vendor_attendance"("workspace_id", "project_id", "attendance_date");

-- CreateIndex
CREATE INDEX "vendor_attendance_vendor_id_attendance_date_idx" ON "construction_labour"."vendor_attendance"("vendor_id", "attendance_date");

-- CreateIndex
CREATE INDEX "vendor_attendance_lines_attendance_id_idx" ON "construction_labour"."vendor_attendance_lines"("attendance_id");

-- CreateIndex
CREATE UNIQUE INDEX "ledger_entries_reverses_entry_id_key" ON "construction_labour"."ledger_entries"("reverses_entry_id");

-- CreateIndex
CREATE INDEX "ledger_entries_workspace_id_party_type_party_id_entry_date_idx" ON "construction_labour"."ledger_entries"("workspace_id", "party_type", "party_id", "entry_date");

-- CreateIndex
CREATE INDEX "ledger_entries_workspace_id_project_id_entry_date_idx" ON "construction_labour"."ledger_entries"("workspace_id", "project_id", "entry_date");

-- CreateIndex
CREATE INDEX "ledger_entries_source_type_source_id_idx" ON "construction_labour"."ledger_entries"("source_type", "source_id");

-- CreateIndex
CREATE INDEX "wage_payments_workspace_id_project_id_payment_date_idx" ON "construction_labour"."wage_payments"("workspace_id", "project_id", "payment_date");

-- CreateIndex
CREATE INDEX "wage_payments_workspace_id_party_type_party_id_idx" ON "construction_labour"."wage_payments"("workspace_id", "party_type", "party_id");

-- CreateIndex
CREATE UNIQUE INDEX "documents_file_key_key" ON "construction_labour"."documents"("file_key");

-- CreateIndex
CREATE INDEX "documents_workspace_id_owner_type_owner_id_idx" ON "construction_labour"."documents"("workspace_id", "owner_type", "owner_id");

-- CreateIndex
CREATE INDEX "labour_categories_workspace_id_idx" ON "construction_masters"."labour_categories"("workspace_id");

-- CreateIndex
CREATE INDEX "departments_workspace_id_idx" ON "construction_masters"."departments"("workspace_id");

-- CreateIndex
CREATE INDEX "supervisors_workspace_id_idx" ON "construction_masters"."supervisors"("workspace_id");

-- CreateIndex
CREATE UNIQUE INDEX "company_profiles_workspace_id_key" ON "construction_organization"."company_profiles"("workspace_id");

-- CreateIndex
CREATE INDEX "audit_events_workspace_id_entity_type_entity_id_idx" ON "construction_organization"."audit_events"("workspace_id", "entity_type", "entity_id");

-- CreateIndex
CREATE INDEX "audit_events_workspace_id_occurred_at_idx" ON "construction_organization"."audit_events"("workspace_id", "occurred_at");

-- CreateIndex
CREATE UNIQUE INDEX "subscriptions_workspace_id_key" ON "construction_organization"."subscriptions"("workspace_id");

-- CreateIndex
CREATE INDEX "designations_workspace_id_idx" ON "construction_organization"."designations"("workspace_id");

-- CreateIndex
CREATE INDEX "member_menu_permissions_workspace_id_menu_idx" ON "construction_organization"."member_menu_permissions"("workspace_id", "menu");

-- CreateIndex
CREATE UNIQUE INDEX "team_members_invite_token_key" ON "construction_organization"."team_members"("invite_token");

-- CreateIndex
CREATE INDEX "team_members_workspace_id_created_at_idx" ON "construction_organization"."team_members"("workspace_id", "created_at");

-- CreateIndex
CREATE INDEX "team_members_user_id_idx" ON "construction_organization"."team_members"("user_id");

-- CreateIndex
CREATE INDEX "team_members_mobile_idx" ON "construction_organization"."team_members"("mobile");

-- CreateIndex
CREATE UNIQUE INDEX "backdated_entry_policies_workspace_id_key" ON "construction_organization"."backdated_entry_policies"("workspace_id");

-- CreateIndex
CREATE INDEX "sequence_rules_workspace_id_module_idx" ON "construction_organization"."sequence_rules"("workspace_id", "module");

-- CreateIndex
CREATE UNIQUE INDEX "stored_files_key_key" ON "construction_organization"."stored_files"("key");

-- CreateIndex
CREATE INDEX "stored_files_workspace_id_deleted_at_idx" ON "construction_organization"."stored_files"("workspace_id", "deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "subscription_orders_gateway_order_id_key" ON "construction_organization"."subscription_orders"("gateway_order_id");

-- CreateIndex
CREATE UNIQUE INDEX "subscription_orders_invoice_number_key" ON "construction_organization"."subscription_orders"("invoice_number");

-- CreateIndex
CREATE INDEX "subscription_orders_workspace_id_created_at_idx" ON "construction_organization"."subscription_orders"("workspace_id", "created_at");

-- CreateIndex
CREATE INDEX "subscription_orders_workspace_id_paid_at_idx" ON "construction_organization"."subscription_orders"("workspace_id", "paid_at");

-- CreateIndex
CREATE INDEX "projects_workspace_id_status_idx" ON "construction_projects"."projects"("workspace_id", "status");

-- CreateIndex
CREATE INDEX "custom_fields_project_id_position_idx" ON "construction_projects"."custom_fields"("project_id", "position");

-- CreateIndex
CREATE INDEX "custom_fields_workspace_id_idx" ON "construction_projects"."custom_fields"("workspace_id");

-- CreateIndex
CREATE UNIQUE INDEX "documents_file_key_key" ON "construction_projects"."documents"("file_key");

-- CreateIndex
CREATE INDEX "documents_workspace_id_project_id_deleted_at_idx" ON "construction_projects"."documents"("workspace_id", "project_id", "deleted_at");

-- CreateIndex
CREATE INDEX "report_jobs_workspace_id_project_id_created_at_idx" ON "construction_reporting"."report_jobs"("workspace_id", "project_id", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "identity"."users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "users_phone_number_key" ON "identity"."users"("phone_number");

-- CreateIndex
CREATE UNIQUE INDEX "sessions_token_key" ON "identity"."sessions"("token");

-- CreateIndex
CREATE INDEX "sessions_user_id_idx" ON "identity"."sessions"("user_id");

-- CreateIndex
CREATE INDEX "accounts_user_id_idx" ON "identity"."accounts"("user_id");

-- CreateIndex
CREATE INDEX "verifications_identifier_idx" ON "identity"."verifications"("identifier");

-- CreateIndex
CREATE UNIQUE INDEX "workspaces_slug_key" ON "identity"."workspaces"("slug");

-- CreateIndex
CREATE INDEX "workspace_members_user_id_idx" ON "identity"."workspace_members"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "workspace_members_workspace_id_user_id_key" ON "identity"."workspace_members"("workspace_id", "user_id");

-- CreateIndex
CREATE INDEX "workspace_invitations_workspace_id_idx" ON "identity"."workspace_invitations"("workspace_id");

-- CreateIndex
CREATE INDEX "workspace_invitations_email_idx" ON "identity"."workspace_invitations"("email");

-- CreateIndex
CREATE UNIQUE INDEX "rate_limits_key_key" ON "identity"."rate_limits"("key");

-- AddForeignKey
ALTER TABLE "construction_labour"."labour_transfers" ADD CONSTRAINT "labour_transfers_labour_id_fkey" FOREIGN KEY ("labour_id") REFERENCES "construction_labour"."labours"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_labour"."labour_attendance" ADD CONSTRAINT "labour_attendance_labour_id_fkey" FOREIGN KEY ("labour_id") REFERENCES "construction_labour"."labours"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_labour"."labour_overtime" ADD CONSTRAINT "labour_overtime_attendance_id_fkey" FOREIGN KEY ("attendance_id") REFERENCES "construction_labour"."labour_attendance"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_labour"."vendor_projects" ADD CONSTRAINT "vendor_projects_vendor_id_fkey" FOREIGN KEY ("vendor_id") REFERENCES "construction_labour"."vendors"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_labour"."vendor_shifts" ADD CONSTRAINT "vendor_shifts_vendor_id_fkey" FOREIGN KEY ("vendor_id") REFERENCES "construction_labour"."vendors"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_labour"."vendor_rates" ADD CONSTRAINT "vendor_rates_shift_id_fkey" FOREIGN KEY ("shift_id") REFERENCES "construction_labour"."vendor_shifts"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_labour"."vendor_attendance" ADD CONSTRAINT "vendor_attendance_vendor_id_fkey" FOREIGN KEY ("vendor_id") REFERENCES "construction_labour"."vendors"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_labour"."vendor_attendance_lines" ADD CONSTRAINT "vendor_attendance_lines_attendance_id_fkey" FOREIGN KEY ("attendance_id") REFERENCES "construction_labour"."vendor_attendance"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_organization"."member_menu_permissions" ADD CONSTRAINT "member_menu_permissions_member_id_fkey" FOREIGN KEY ("member_id") REFERENCES "construction_organization"."team_members"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_organization"."team_member_projects" ADD CONSTRAINT "team_member_projects_member_id_fkey" FOREIGN KEY ("member_id") REFERENCES "construction_organization"."team_members"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_organization"."sequence_counters" ADD CONSTRAINT "sequence_counters_rule_id_fkey" FOREIGN KEY ("rule_id") REFERENCES "construction_organization"."sequence_rules"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_projects"."custom_fields" ADD CONSTRAINT "custom_fields_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "construction_projects"."projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_projects"."documents" ADD CONSTRAINT "documents_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "construction_projects"."projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "identity"."sessions" ADD CONSTRAINT "sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "identity"."accounts" ADD CONSTRAINT "accounts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "identity"."workspace_members" ADD CONSTRAINT "workspace_members_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES "identity"."workspaces"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "identity"."workspace_members" ADD CONSTRAINT "workspace_members_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "identity"."workspace_invitations" ADD CONSTRAINT "workspace_invitations_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES "identity"."workspaces"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "identity"."workspace_invitations" ADD CONSTRAINT "workspace_invitations_inviter_id_fkey" FOREIGN KEY ("inviter_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE CASCADE;


-- ---------------------------------------------------------------------------
-- Written by hand: Prisma cannot express CHECK constraints, or partial and
-- expression indexes.
-- ---------------------------------------------------------------------------

-- At most one pending invitation per email per Company.
CREATE UNIQUE INDEX "workspace_invitations_one_pending_key" ON "identity"."workspace_invitations"("workspace_id", "email") WHERE "status" = 'pending';

-- One live Designation per name per Company.
CREATE UNIQUE INDEX "designations_live_name_key" ON "construction_organization"."designations"("workspace_id", lower("name")) WHERE "deleted_at" IS NULL;

-- One live Team Member per mobile, per email and per User in a Company.
CREATE UNIQUE INDEX "team_members_live_mobile_key" ON "construction_organization"."team_members"("workspace_id", "mobile") WHERE "deleted_at" IS NULL AND "mobile" IS NOT NULL;
CREATE UNIQUE INDEX "team_members_live_email_key" ON "construction_organization"."team_members"("workspace_id", lower("email")) WHERE "deleted_at" IS NULL AND "email" IS NOT NULL;
CREATE UNIQUE INDEX "team_members_live_user_key" ON "construction_organization"."team_members"("workspace_id", "user_id") WHERE "deleted_at" IS NULL AND "user_id" IS NOT NULL;

ALTER TABLE "construction_organization"."team_members" ADD CONSTRAINT "team_members_mobile_or_email" CHECK ("mobile" IS NOT NULL OR "email" IS NOT NULL);

-- Days are 0 (no restriction) or more.
ALTER TABLE "construction_organization"."backdated_entry_policies" ADD CONSTRAINT "backdated_entry_policies_days_check" CHECK ("create_days" >= 0 AND "edit_days" >= 0);

-- One live default rule per module and one live rule per (module, project).
-- `nextSequenceNumber` relies on the first for ON CONFLICT when it saves a
-- module's standard rule.
CREATE UNIQUE INDEX "sequence_rules_live_default_key" ON "construction_organization"."sequence_rules"("workspace_id", "module") WHERE "project_id" IS NULL AND "deleted_at" IS NULL;
CREATE UNIQUE INDEX "sequence_rules_live_project_key" ON "construction_organization"."sequence_rules"("workspace_id", "module", "project_id") WHERE "project_id" IS NOT NULL AND "deleted_at" IS NULL;

ALTER TABLE "construction_organization"."sequence_rules" ADD CONSTRAINT "sequence_rules_numbers_check" CHECK ("start_number" >= 1 AND "padding" BETWEEN 1 AND 10);
ALTER TABLE "construction_organization"."sequence_counters" ADD CONSTRAINT "sequence_counters_last_number_check" CHECK ("last_number" >= 1);

-- One live row per name per Company, per list; one live Project per name;
-- one live Labour Id per Company.
CREATE UNIQUE INDEX "labour_categories_live_name_key" ON "construction_masters"."labour_categories"("workspace_id", lower("name")) WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "departments_live_name_key" ON "construction_masters"."departments"("workspace_id", lower("name")) WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "supervisors_live_name_key" ON "construction_masters"."supervisors"("workspace_id", lower("name")) WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "projects_live_name_key" ON "construction_projects"."projects"("workspace_id", lower("name")) WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "labours_live_code_key" ON "construction_labour"."labours"("workspace_id", lower("labour_code")) WHERE "deleted_at" IS NULL AND "labour_code" IS NOT NULL;

-- One live attendance row per labourer per day, and per vendor per Project
-- per day (CM-210, CM-212).
CREATE UNIQUE INDEX "labour_attendance_live_day_key" ON "construction_labour"."labour_attendance"("labour_id", "attendance_date") WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "vendor_attendance_live_day_key" ON "construction_labour"."vendor_attendance"("vendor_id", "project_id", "attendance_date") WHERE "deleted_at" IS NULL;

-- Money is never negative where it is a rate or a payment; ledger amounts
-- are signed (ADR CM-0004).
ALTER TABLE "construction_labour"."labours" ADD CONSTRAINT "labours_wages_check" CHECK (
  "overtime_wage_per_hour" >= 0
  AND ("wage_type" <> 'daily' OR ("wage_per_day" IS NOT NULL AND "wage_per_day" >= 0))
  AND ("wage_type" <> 'monthly' OR ("wage_per_month" IS NOT NULL AND "wage_per_month" >= 0))
);
ALTER TABLE "construction_labour"."labour_overtime" ADD CONSTRAINT "labour_overtime_hours_check" CHECK ("hours" > 0 AND "hours" <= 24 AND "rate_per_hour" >= 0);
ALTER TABLE "construction_labour"."vendor_attendance_lines" ADD CONSTRAINT "vendor_attendance_lines_counts_check" CHECK ("full_day_count" >= 0 AND "half_day_count" >= 0 AND "overtime_hours" >= 0);
ALTER TABLE "construction_labour"."wage_payments" ADD CONSTRAINT "wage_payments_amount_check" CHECK ("amount" > 0);

-- One field per label on a Project, ignoring case ("Site engineer" and
-- "site Engineer" are the same field).
CREATE UNIQUE INDEX "custom_fields_project_label_key" ON "construction_projects"."custom_fields"("project_id", lower("label"));
