-- Company billing addresses and GRN field visibility for M5 (CM-501,
-- CM-505, ADR CM-0015 §1 and §9). Touches no other schema (ADR-0030).
--
-- Generated by `prisma migrate diff`, then the partial unique indexes Prisma
-- cannot express.

-- CreateTable
CREATE TABLE "construction_organization"."billing_addresses" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "state_code" CHAR(2) NOT NULL,
    "gstin" VARCHAR(15),
    "is_default" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "billing_addresses_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_organization"."grn_field_settings" (
    "workspace_id" TEXT NOT NULL,
    "hidden_fields" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_by" TEXT NOT NULL,

    CONSTRAINT "grn_field_settings_pkey" PRIMARY KEY ("workspace_id")
);

-- CreateIndex
CREATE INDEX "billing_addresses_workspace_id_idx" ON "construction_organization"."billing_addresses"("workspace_id");

-- At most one default billing address per Company among live rows; names unique ignoring case.
CREATE UNIQUE INDEX "billing_addresses_one_default_key" ON "construction_organization"."billing_addresses"("workspace_id") WHERE "is_default" AND "deleted_at" IS NULL;
CREATE UNIQUE INDEX "billing_addresses_live_name_key" ON "construction_organization"."billing_addresses"("workspace_id", lower("name")) WHERE "deleted_at" IS NULL;
