-- Whiteboard's first migration (ADR-0040). Whiteboard and Construction
-- Management used to share one migration history; each database now has only
-- its own schemas. This replaces the shared history from 20260909000000 to
-- 20261012010000 (see git history for each step and its reasons).
--
-- Generated by `prisma migrate diff --from-empty`, then the hand-written
-- section at the end, which Prisma cannot express.

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "identity";

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "training_institute";

-- CreateEnum
CREATE TYPE "training_institute"."class_mode" AS ENUM ('offline', 'online', 'hybrid');

-- CreateEnum
CREATE TYPE "training_institute"."meeting_option" AS ENUM ('external', 'whiteboard');

-- CreateEnum
CREATE TYPE "training_institute"."class_change_kind" AS ENUM ('cancelled', 'moved');

-- CreateEnum
CREATE TYPE "training_institute"."timing_source" AS ENUM ('batch', 'student');

-- CreateEnum
CREATE TYPE "training_institute"."fee_plan_type" AS ENUM ('one_time', 'monthly', 'installments');

-- CreateEnum
CREATE TYPE "training_institute"."fee_payment_method" AS ENUM ('cash', 'upi', 'card', 'other');

-- CreateEnum
CREATE TYPE "training_institute"."course_duration_kind" AS ENUM ('fixed', 'flexible');

-- CreateEnum
CREATE TYPE "training_institute"."course_duration_unit" AS ENUM ('days', 'weeks', 'months');

-- CreateEnum
CREATE TYPE "training_institute"."teacher_kind" AS ENUM ('centre_teacher', 'visiting_tutor');

-- CreateEnum
CREATE TYPE "training_institute"."teacher_invitation_status" AS ENUM ('not_sent', 'sent', 'failed', 'accepted');

-- CreateEnum
CREATE TYPE "training_institute"."attendance_status" AS ENUM ('unmarked', 'present', 'absent', 'late', 'excused');

-- CreateEnum
CREATE TYPE "training_institute"."fee_follow_up_channel" AS ENUM ('phone', 'whatsapp_sms', 'in_person', 'other');

-- CreateEnum
CREATE TYPE "training_institute"."fee_follow_up_close_reason" AS ENUM ('superseded', 'done', 'dues_cleared');

-- CreateEnum
CREATE TYPE "training_institute"."enquiry_stage" AS ENUM ('new', 'follow_up', 'demo_scheduled', 'demo_attended', 'joined', 'not_interested');

-- CreateEnum
CREATE TYPE "training_institute"."enquiry_activity_kind" AS ENUM ('created', 'follow_up', 'not_interested', 'reopened', 'joined', 'details_updated');

-- CreateEnum
CREATE TYPE "training_institute"."demo_kind" AS ENUM ('batch', 'one_to_one');

-- CreateEnum
CREATE TYPE "training_institute"."demo_fee_kind" AS ENUM ('free', 'paid');

-- CreateEnum
CREATE TYPE "training_institute"."demo_attendance" AS ENUM ('unmarked', 'attended', 'missed');

-- CreateEnum
CREATE TYPE "training_institute"."poster_role" AS ENUM ('owner', 'teacher');

-- CreateEnum
CREATE TYPE "training_institute"."submitter_role" AS ENUM ('student', 'parent');

-- CreateEnum
CREATE TYPE "training_institute"."class_test_scope" AS ENUM ('batch', 'student');

-- CreateEnum
CREATE TYPE "training_institute"."test_result_status" AS ENUM ('scored', 'absent', 'exempt');

-- CreateTable
CREATE TABLE "identity"."users" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "email_verified" BOOLEAN NOT NULL DEFAULT false,
    "image" TEXT,
    "username" TEXT,
    "display_username" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "identity"."sessions" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "token" TEXT NOT NULL,
    "expires_at" TIMESTAMP(3) NOT NULL,
    "ip_address" TEXT,
    "user_agent" TEXT,
    "active_workspace_id" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "identity"."accounts" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "account_id" TEXT NOT NULL,
    "provider_id" TEXT NOT NULL,
    "access_token" TEXT,
    "refresh_token" TEXT,
    "id_token" TEXT,
    "access_token_expires_at" TIMESTAMP(3),
    "refresh_token_expires_at" TIMESTAMP(3),
    "scope" TEXT,
    "password" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "accounts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "identity"."verifications" (
    "id" TEXT NOT NULL,
    "identifier" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "expires_at" TIMESTAMP(3) NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "verifications_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "identity"."workspaces" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "logo" TEXT,
    "metadata" TEXT,
    "institution_type" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "workspaces_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "identity"."workspace_members" (
    "id" TEXT NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "workspace_members_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "identity"."workspace_invitations" (
    "id" TEXT NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "role" TEXT,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "expires_at" TIMESTAMP(3) NOT NULL,
    "inviter_id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "workspace_invitations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "identity"."rate_limits" (
    "id" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "count" INTEGER NOT NULL,
    "last_request" BIGINT NOT NULL,

    CONSTRAINT "rate_limits_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "training_institute"."courses" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "created_by_user_id" TEXT NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    "duration_kind" "training_institute"."course_duration_kind" NOT NULL DEFAULT 'flexible',
    "duration_value" INTEGER,
    "duration_unit" "training_institute"."course_duration_unit",
    "code" VARCHAR(40),
    "category" VARCHAR(100),
    "total_learning_hours" INTEGER,
    "eligibility" TEXT,
    "learning_outcomes" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "syllabus_outline" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "description" TEXT,
    "default_fee_amount_paise" INTEGER NOT NULL,
    "archived_at" TIMESTAMP(3),
    "archived_by_user_id" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),
    "deleted_by_user_id" TEXT,

    CONSTRAINT "courses_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "training_institute"."batches" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "course_id" UUID NOT NULL,
    "created_by_user_id" TEXT NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    "class_mode" "training_institute"."class_mode" NOT NULL,
    "capacity" INTEGER NOT NULL,
    "room" VARCHAR(80),
    "join_url" VARCHAR(2048),
    "meeting_option" "training_institute"."meeting_option" NOT NULL DEFAULT 'external',
    "timings" JSONB NOT NULL,
    "timezone" VARCHAR(64) NOT NULL DEFAULT 'Asia/Kolkata',
    "closed_at" TIMESTAMP(3),
    "closed_by_user_id" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),
    "deleted_by_user_id" TEXT,

    CONSTRAINT "batches_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "training_institute"."class_occurrences" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "batch_id" UUID NOT NULL,
    "class_date" DATE NOT NULL,
    "start_time" VARCHAR(5) NOT NULL,
    "end_time" VARCHAR(5) NOT NULL,
    "provider_meeting_id" VARCHAR(100),
    "status" VARCHAR(20) NOT NULL DEFAULT 'starting',
    "recording_id" VARCHAR(100),
    "recording_status" VARCHAR(20) NOT NULL DEFAULT 'pending',
    "recording_object_key" VARCHAR(1024),
    "started_by_user_id" TEXT NOT NULL,
    "started_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ended_at" TIMESTAMP(3),

    CONSTRAINT "class_occurrences_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "training_institute"."class_changes" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "batch_id" UUID NOT NULL,
    "class_date" DATE NOT NULL,
    "start_time" VARCHAR(5) NOT NULL,
    "end_time" VARCHAR(5) NOT NULL,
    "kind" "training_institute"."class_change_kind" NOT NULL,
    "reason" VARCHAR(200),
    "moved_to_date" DATE,
    "moved_to_start_time" VARCHAR(5),
    "moved_to_end_time" VARCHAR(5),
    "created_by_user_id" TEXT NOT NULL,
    "updated_by_user_id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),
    "deleted_by_user_id" TEXT,

    CONSTRAINT "class_changes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "training_institute"."holidays" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "start_date" DATE NOT NULL,
    "end_date" DATE NOT NULL,
    "reason" VARCHAR(200),
    "created_by_user_id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),
    "deleted_by_user_id" TEXT,

    CONSTRAINT "holidays_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "training_institute"."teachers" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "created_by_user_id" TEXT NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    "email" VARCHAR(320) NOT NULL,
    "kind" "training_institute"."teacher_kind" NOT NULL,
    "phone" VARCHAR(32),
    "qualification_summary" VARCHAR(1000),
    "profile_details" JSONB NOT NULL DEFAULT '{}',
    "photo_data" BYTEA,
    "photo_mime_type" VARCHAR(50),
    "photo_updated_at" TIMESTAMP(3),
    "id_number_encrypted" TEXT,
    "id_number_last4" VARCHAR(4),
    "bank_account_encrypted" TEXT,
    "bank_account_last4" VARCHAR(4),
    "user_id" TEXT,
    "invitation_id" TEXT,
    "invitation_status" "training_institute"."teacher_invitation_status" NOT NULL DEFAULT 'not_sent',
    "deactivated_at" TIMESTAMP(3),
    "deactivated_by_user_id" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),
    "deleted_by_user_id" TEXT,

    CONSTRAINT "teachers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "training_institute"."teacher_documents" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "teacher_id" UUID NOT NULL,
    "kind" VARCHAR(32) NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    "mime_type" VARCHAR(50) NOT NULL,
    "encrypted_data" BYTEA NOT NULL,
    "size_bytes" INTEGER NOT NULL,
    "uploaded_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "uploaded_by_user_id" TEXT NOT NULL,
    "deleted_at" TIMESTAMP(3),
    "deleted_by_user_id" TEXT,

    CONSTRAINT "teacher_documents_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "training_institute"."batch_teacher_assignments" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "teacher_id" UUID NOT NULL,
    "batch_id" UUID NOT NULL,
    "assigned_by_user_id" TEXT NOT NULL,
    "assigned_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "unassigned_at" TIMESTAMP(3),
    "unassigned_by_user_id" TEXT,
    "deleted_at" TIMESTAMP(3),
    "deleted_by_user_id" TEXT,

    CONSTRAINT "batch_teacher_assignments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "training_institute"."students" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "created_by_user_id" TEXT NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    "phone" VARCHAR(32) NOT NULL,
    "email" VARCHAR(320),
    "photo_url" VARCHAR(2048),
    "address" TEXT,
    "id_proof_note" TEXT,
    "guardian_name" VARCHAR(200),
    "guardian_phone" VARCHAR(32),
    "profile_details" JSONB NOT NULL DEFAULT '{}',
    "dropped_at" TIMESTAMP(3),
    "dropped_by_user_id" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),
    "deleted_by_user_id" TEXT,

    CONSTRAINT "students_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "training_institute"."enrollments" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "student_id" UUID NOT NULL,
    "course_id" UUID NOT NULL,
    "batch_id" UUID NOT NULL,
    "created_by_user_id" TEXT NOT NULL,
    "class_mode_override" "training_institute"."class_mode",
    "timing_source" "training_institute"."timing_source" NOT NULL,
    "student_timings" JSONB,
    "ended_at" TIMESTAMP(3),
    "ended_by_user_id" TEXT,
    "fee_plan_type" "training_institute"."fee_plan_type" NOT NULL,
    "fee_plan_amount_paise" INTEGER NOT NULL,
    "fee_plan_installment_count" INTEGER,
    "fee_plan_concession_paise" INTEGER NOT NULL DEFAULT 0,
    "fee_plan_due_dates" JSONB NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),
    "deleted_by_user_id" TEXT,

    CONSTRAINT "enrollments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "training_institute"."attendance_registers" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "batch_id" UUID NOT NULL,
    "date" DATE NOT NULL,
    "timezone" VARCHAR(64) NOT NULL,
    "created_by_user_id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),
    "deleted_by_user_id" TEXT,

    CONSTRAINT "attendance_registers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "training_institute"."attendance_marks" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "register_id" UUID NOT NULL,
    "enrollment_id" UUID NOT NULL,
    "student_id" UUID NOT NULL,
    "student_name_snapshot" VARCHAR(200) NOT NULL,
    "status" "training_institute"."attendance_status" NOT NULL DEFAULT 'unmarked',
    "note" VARCHAR(500),
    "marked_by_user_id" TEXT,
    "marked_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),
    "deleted_by_user_id" TEXT,

    CONSTRAINT "attendance_marks_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "training_institute"."attendance_mark_changes" (
    "id" UUID NOT NULL,
    "mark_id" UUID NOT NULL,
    "old_status" "training_institute"."attendance_status" NOT NULL,
    "new_status" "training_institute"."attendance_status" NOT NULL,
    "old_note" VARCHAR(500),
    "new_note" VARCHAR(500),
    "changed_by_user_id" TEXT NOT NULL,
    "changed_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "attendance_mark_changes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "training_institute"."fee_payments" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "enrollment_id" UUID NOT NULL,
    "recorded_by_user_id" TEXT NOT NULL,
    "amount_paise" INTEGER NOT NULL,
    "method" "training_institute"."fee_payment_method" NOT NULL,
    "paid_at" TIMESTAMP(3) NOT NULL,
    "receipt_number" VARCHAR(32) NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),
    "deleted_by_user_id" TEXT,

    CONSTRAINT "fee_payments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "training_institute"."fee_follow_ups" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "enrollment_id" UUID NOT NULL,
    "channel" "training_institute"."fee_follow_up_channel" NOT NULL,
    "note" VARCHAR(500),
    "next_follow_up_on" DATE,
    "logged_by_user_id" TEXT NOT NULL,
    "edited_by_user_id" TEXT,
    "edited_at" TIMESTAMP(3),
    "closed_by_user_id" TEXT,
    "closed_at" TIMESTAMP(3),
    "close_reason" "training_institute"."fee_follow_up_close_reason",
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "fee_follow_ups_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "training_institute"."enquiry_sources" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "name" VARCHAR(80) NOT NULL,
    "retired_at" TIMESTAMP(3),
    "retired_by_user_id" TEXT,
    "created_by_user_id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "enquiry_sources_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "training_institute"."enquiries" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "created_by_user_id" TEXT NOT NULL,
    "prospect_name" VARCHAR(200) NOT NULL,
    "phone" VARCHAR(32) NOT NULL,
    "email" VARCHAR(320),
    "guardian_name" VARCHAR(200),
    "guardian_phone" VARCHAR(32),
    "course_id" UUID,
    "subject" VARCHAR(200),
    "preferred_class_mode" "training_institute"."class_mode",
    "preferred_timing" VARCHAR(200),
    "source_id" UUID,
    "notes" TEXT,
    "stage" "training_institute"."enquiry_stage" NOT NULL DEFAULT 'new',
    "next_follow_up_on" DATE,
    "not_interested_reason" VARCHAR(200),
    "closed_at" TIMESTAMP(3),
    "closed_by_user_id" TEXT,
    "converted_student_id" UUID,
    "converted_enrollment_id" UUID,
    "converted_at" TIMESTAMP(3),
    "converted_by_user_id" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),
    "deleted_by_user_id" TEXT,

    CONSTRAINT "enquiries_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "training_institute"."enquiry_activities" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "enquiry_id" UUID NOT NULL,
    "kind" "training_institute"."enquiry_activity_kind" NOT NULL,
    "note" VARCHAR(1000),
    "next_follow_up_on" DATE,
    "created_by_user_id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "enquiry_activities_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "training_institute"."enquiry_demos" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "enquiry_id" UUID NOT NULL,
    "kind" "training_institute"."demo_kind" NOT NULL,
    "batch_id" UUID,
    "teacher_id" UUID,
    "demo_date" DATE NOT NULL,
    "start_time" VARCHAR(5) NOT NULL,
    "end_time" VARCHAR(5) NOT NULL,
    "timezone" VARCHAR(64) NOT NULL,
    "fee_kind" "training_institute"."demo_fee_kind" NOT NULL,
    "fee_amount_paise" INTEGER,
    "fee_paid_at" TIMESTAMP(3),
    "fee_paid_by_user_id" TEXT,
    "attendance" "training_institute"."demo_attendance" NOT NULL DEFAULT 'unmarked',
    "attendance_marked_at" TIMESTAMP(3),
    "attendance_marked_by_user_id" TEXT,
    "cancelled_at" TIMESTAMP(3),
    "cancelled_by_user_id" TEXT,
    "created_by_user_id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "enquiry_demos_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "training_institute"."study_materials" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "batch_id" UUID NOT NULL,
    "title" VARCHAR(200) NOT NULL,
    "note" TEXT,
    "link_url" VARCHAR(2048),
    "class_date" DATE,
    "posted_by_user_id" TEXT NOT NULL,
    "posted_by_role" "training_institute"."poster_role" NOT NULL,
    "posted_by_teacher_id" UUID,
    "updated_by_user_id" TEXT NOT NULL,
    "removed_at" TIMESTAMP(3),
    "removed_by_user_id" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "study_materials_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "training_institute"."homework" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "batch_id" UUID NOT NULL,
    "title" VARCHAR(200) NOT NULL,
    "instructions" TEXT NOT NULL,
    "class_date" DATE NOT NULL,
    "due_on" DATE NOT NULL,
    "posted_by_user_id" TEXT NOT NULL,
    "posted_by_role" "training_institute"."poster_role" NOT NULL,
    "posted_by_teacher_id" UUID,
    "updated_by_user_id" TEXT NOT NULL,
    "removed_at" TIMESTAMP(3),
    "removed_by_user_id" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "homework_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "training_institute"."homework_submissions" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "homework_id" UUID NOT NULL,
    "student_id" UUID NOT NULL,
    "note" VARCHAR(1000),
    "submitted_at" TIMESTAMP(3) NOT NULL,
    "submitted_by_user_id" TEXT NOT NULL,
    "submitted_by_role" "training_institute"."submitter_role" NOT NULL,
    "updated_by_user_id" TEXT NOT NULL,
    "updated_by_role" "training_institute"."submitter_role" NOT NULL,
    "checked_at" TIMESTAMP(3),
    "checked_by_user_id" TEXT,
    "remark" VARCHAR(500),
    "withdrawn_at" TIMESTAMP(3),
    "withdrawn_by_user_id" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "homework_submissions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "training_institute"."attachments" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "study_material_id" UUID,
    "homework_id" UUID,
    "submission_id" UUID,
    "name" VARCHAR(200) NOT NULL,
    "mime_type" VARCHAR(50) NOT NULL,
    "size_bytes" INTEGER NOT NULL,
    "data" BYTEA NOT NULL,
    "uploaded_by_user_id" TEXT NOT NULL,
    "uploaded_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMP(3),
    "deleted_by_user_id" TEXT,

    CONSTRAINT "attachments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "training_institute"."class_tests" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "batch_id" UUID NOT NULL,
    "scope" "training_institute"."class_test_scope" NOT NULL,
    "student_id" UUID,
    "name" VARCHAR(200) NOT NULL,
    "held_on" DATE NOT NULL,
    "max_marks" INTEGER NOT NULL,
    "pass_marks" INTEGER,
    "topic" VARCHAR(1000),
    "created_by_user_id" TEXT NOT NULL,
    "created_by_role" "training_institute"."poster_role" NOT NULL,
    "created_by_teacher_id" UUID,
    "updated_by_user_id" TEXT NOT NULL,
    "published_at" TIMESTAMP(3),
    "published_by_user_id" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),
    "deleted_by_user_id" TEXT,

    CONSTRAINT "class_tests_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "training_institute"."test_results" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "test_id" UUID NOT NULL,
    "student_id" UUID NOT NULL,
    "status" "training_institute"."test_result_status" NOT NULL,
    "marks" DECIMAL(6,1),
    "remark" VARCHAR(500),
    "updated_by_user_id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "test_results_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "training_institute"."test_result_changes" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "result_id" UUID NOT NULL,
    "old_status" "training_institute"."test_result_status" NOT NULL,
    "new_status" "training_institute"."test_result_status" NOT NULL,
    "old_marks" DECIMAL(6,1),
    "new_marks" DECIMAL(6,1),
    "old_remark" VARCHAR(500),
    "new_remark" VARCHAR(500),
    "changed_by_user_id" TEXT NOT NULL,
    "changed_by_role" "training_institute"."poster_role" NOT NULL,
    "changed_by_teacher_id" UUID,
    "changed_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "test_result_changes_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "identity"."users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "users_username_key" ON "identity"."users"("username");

-- CreateIndex
CREATE UNIQUE INDEX "sessions_token_key" ON "identity"."sessions"("token");

-- CreateIndex
CREATE INDEX "sessions_user_id_idx" ON "identity"."sessions"("user_id");

-- CreateIndex
CREATE INDEX "accounts_user_id_idx" ON "identity"."accounts"("user_id");

-- CreateIndex
CREATE INDEX "verifications_identifier_idx" ON "identity"."verifications"("identifier");

-- CreateIndex
CREATE UNIQUE INDEX "workspaces_slug_key" ON "identity"."workspaces"("slug");

-- CreateIndex
CREATE INDEX "workspace_members_user_id_idx" ON "identity"."workspace_members"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "workspace_members_workspace_id_user_id_key" ON "identity"."workspace_members"("workspace_id", "user_id");

-- CreateIndex
CREATE INDEX "workspace_invitations_workspace_id_idx" ON "identity"."workspace_invitations"("workspace_id");

-- CreateIndex
CREATE INDEX "workspace_invitations_email_idx" ON "identity"."workspace_invitations"("email");

-- CreateIndex
CREATE UNIQUE INDEX "rate_limits_key_key" ON "identity"."rate_limits"("key");

-- CreateIndex
CREATE INDEX "courses_workspace_id_deleted_at_created_at_id_idx" ON "training_institute"."courses"("workspace_id", "deleted_at", "created_at", "id");

-- CreateIndex
CREATE INDEX "batches_workspace_id_deleted_at_created_at_id_idx" ON "training_institute"."batches"("workspace_id", "deleted_at", "created_at", "id");

-- CreateIndex
CREATE INDEX "batches_course_id_deleted_at_idx" ON "training_institute"."batches"("course_id", "deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "class_occurrences_provider_meeting_id_key" ON "training_institute"."class_occurrences"("provider_meeting_id");

-- CreateIndex
CREATE INDEX "class_occurrences_workspace_id_batch_id_class_date_idx" ON "training_institute"."class_occurrences"("workspace_id", "batch_id", "class_date");

-- CreateIndex
CREATE UNIQUE INDEX "class_occurrences_batch_id_class_date_start_time_key" ON "training_institute"."class_occurrences"("batch_id", "class_date", "start_time");

-- CreateIndex
CREATE INDEX "class_changes_workspace_id_batch_id_class_date_idx" ON "training_institute"."class_changes"("workspace_id", "batch_id", "class_date");

-- CreateIndex
CREATE INDEX "class_changes_workspace_id_deleted_at_class_date_idx" ON "training_institute"."class_changes"("workspace_id", "deleted_at", "class_date");

-- CreateIndex
CREATE INDEX "holidays_workspace_id_deleted_at_start_date_idx" ON "training_institute"."holidays"("workspace_id", "deleted_at", "start_date");

-- CreateIndex
CREATE INDEX "teachers_workspace_id_deleted_at_created_at_id_idx" ON "training_institute"."teachers"("workspace_id", "deleted_at", "created_at", "id");

-- CreateIndex
CREATE INDEX "teachers_workspace_id_user_id_idx" ON "training_institute"."teachers"("workspace_id", "user_id");

-- CreateIndex
CREATE INDEX "teacher_documents_workspace_id_teacher_id_deleted_at_upload_idx" ON "training_institute"."teacher_documents"("workspace_id", "teacher_id", "deleted_at", "uploaded_at", "id");

-- CreateIndex
CREATE INDEX "batch_teacher_assignments_workspace_id_teacher_id_unassigne_idx" ON "training_institute"."batch_teacher_assignments"("workspace_id", "teacher_id", "unassigned_at");

-- CreateIndex
CREATE INDEX "batch_teacher_assignments_workspace_id_batch_id_unassigned__idx" ON "training_institute"."batch_teacher_assignments"("workspace_id", "batch_id", "unassigned_at");

-- CreateIndex
CREATE INDEX "students_workspace_id_deleted_at_created_at_id_idx" ON "training_institute"."students"("workspace_id", "deleted_at", "created_at", "id");

-- CreateIndex
CREATE INDEX "students_workspace_id_phone_idx" ON "training_institute"."students"("workspace_id", "phone");

-- CreateIndex
CREATE INDEX "students_workspace_id_name_idx" ON "training_institute"."students"("workspace_id", "name");

-- CreateIndex
CREATE INDEX "enrollments_workspace_id_deleted_at_created_at_id_idx" ON "training_institute"."enrollments"("workspace_id", "deleted_at", "created_at", "id");

-- CreateIndex
CREATE INDEX "enrollments_student_id_deleted_at_idx" ON "training_institute"."enrollments"("student_id", "deleted_at");

-- CreateIndex
CREATE INDEX "enrollments_batch_id_deleted_at_ended_at_idx" ON "training_institute"."enrollments"("batch_id", "deleted_at", "ended_at");

-- CreateIndex
CREATE INDEX "attendance_registers_workspace_id_batch_id_date_idx" ON "training_institute"."attendance_registers"("workspace_id", "batch_id", "date");

-- CreateIndex
CREATE INDEX "attendance_marks_workspace_id_student_id_created_at_idx" ON "training_institute"."attendance_marks"("workspace_id", "student_id", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "attendance_marks_register_id_enrollment_id_key" ON "training_institute"."attendance_marks"("register_id", "enrollment_id");

-- CreateIndex
CREATE INDEX "attendance_mark_changes_mark_id_changed_at_idx" ON "training_institute"."attendance_mark_changes"("mark_id", "changed_at");

-- CreateIndex
CREATE INDEX "fee_payments_workspace_id_deleted_at_created_at_id_idx" ON "training_institute"."fee_payments"("workspace_id", "deleted_at", "created_at", "id");

-- CreateIndex
CREATE INDEX "fee_payments_enrollment_id_deleted_at_paid_at_id_idx" ON "training_institute"."fee_payments"("enrollment_id", "deleted_at", "paid_at", "id");

-- CreateIndex
CREATE UNIQUE INDEX "fee_payments_workspace_id_receipt_number_key" ON "training_institute"."fee_payments"("workspace_id", "receipt_number");

-- CreateIndex
CREATE INDEX "fee_follow_ups_enrollment_id_created_at_idx" ON "training_institute"."fee_follow_ups"("enrollment_id", "created_at");

-- CreateIndex
CREATE INDEX "fee_follow_ups_workspace_id_closed_at_next_follow_up_on_idx" ON "training_institute"."fee_follow_ups"("workspace_id", "closed_at", "next_follow_up_on");

-- CreateIndex
CREATE INDEX "enquiry_sources_workspace_id_retired_at_idx" ON "training_institute"."enquiry_sources"("workspace_id", "retired_at");

-- CreateIndex
CREATE UNIQUE INDEX "enquiries_converted_student_id_key" ON "training_institute"."enquiries"("converted_student_id");

-- CreateIndex
CREATE INDEX "enquiries_workspace_id_deleted_at_created_at_id_idx" ON "training_institute"."enquiries"("workspace_id", "deleted_at", "created_at", "id");

-- CreateIndex
CREATE INDEX "enquiries_workspace_id_stage_next_follow_up_on_idx" ON "training_institute"."enquiries"("workspace_id", "stage", "next_follow_up_on");

-- CreateIndex
CREATE INDEX "enquiries_workspace_id_phone_idx" ON "training_institute"."enquiries"("workspace_id", "phone");

-- CreateIndex
CREATE INDEX "enquiry_activities_enquiry_id_created_at_idx" ON "training_institute"."enquiry_activities"("enquiry_id", "created_at");

-- CreateIndex
CREATE INDEX "enquiry_demos_workspace_id_demo_date_idx" ON "training_institute"."enquiry_demos"("workspace_id", "demo_date");

-- CreateIndex
CREATE INDEX "enquiry_demos_workspace_id_teacher_id_demo_date_idx" ON "training_institute"."enquiry_demos"("workspace_id", "teacher_id", "demo_date");

-- CreateIndex
CREATE INDEX "enquiry_demos_enquiry_id_idx" ON "training_institute"."enquiry_demos"("enquiry_id");

-- CreateIndex
CREATE INDEX "study_materials_workspace_id_batch_id_created_at_idx" ON "training_institute"."study_materials"("workspace_id", "batch_id", "created_at");

-- CreateIndex
CREATE INDEX "homework_workspace_id_batch_id_created_at_idx" ON "training_institute"."homework"("workspace_id", "batch_id", "created_at");

-- CreateIndex
CREATE INDEX "homework_submissions_workspace_id_homework_id_idx" ON "training_institute"."homework_submissions"("workspace_id", "homework_id");

-- CreateIndex
CREATE INDEX "homework_submissions_workspace_id_student_id_idx" ON "training_institute"."homework_submissions"("workspace_id", "student_id");

-- CreateIndex
CREATE INDEX "attachments_study_material_id_deleted_at_idx" ON "training_institute"."attachments"("study_material_id", "deleted_at");

-- CreateIndex
CREATE INDEX "attachments_homework_id_deleted_at_idx" ON "training_institute"."attachments"("homework_id", "deleted_at");

-- CreateIndex
CREATE INDEX "attachments_submission_id_deleted_at_idx" ON "training_institute"."attachments"("submission_id", "deleted_at");

-- CreateIndex
CREATE INDEX "attachments_workspace_id_uploaded_by_user_id_uploaded_at_idx" ON "training_institute"."attachments"("workspace_id", "uploaded_by_user_id", "uploaded_at");

-- CreateIndex
CREATE INDEX "class_tests_workspace_id_batch_id_held_on_idx" ON "training_institute"."class_tests"("workspace_id", "batch_id", "held_on");

-- CreateIndex
CREATE INDEX "test_results_workspace_id_student_id_idx" ON "training_institute"."test_results"("workspace_id", "student_id");

-- CreateIndex
CREATE UNIQUE INDEX "test_results_test_id_student_id_key" ON "training_institute"."test_results"("test_id", "student_id");

-- CreateIndex
CREATE INDEX "test_result_changes_result_id_changed_at_idx" ON "training_institute"."test_result_changes"("result_id", "changed_at");

-- AddForeignKey
ALTER TABLE "identity"."sessions" ADD CONSTRAINT "sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "identity"."accounts" ADD CONSTRAINT "accounts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "identity"."workspace_members" ADD CONSTRAINT "workspace_members_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES "identity"."workspaces"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "identity"."workspace_members" ADD CONSTRAINT "workspace_members_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "identity"."workspace_invitations" ADD CONSTRAINT "workspace_invitations_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES "identity"."workspaces"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "identity"."workspace_invitations" ADD CONSTRAINT "workspace_invitations_inviter_id_fkey" FOREIGN KEY ("inviter_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."batches" ADD CONSTRAINT "batches_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "training_institute"."courses"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."class_occurrences" ADD CONSTRAINT "class_occurrences_batch_id_fkey" FOREIGN KEY ("batch_id") REFERENCES "training_institute"."batches"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."class_changes" ADD CONSTRAINT "class_changes_batch_id_fkey" FOREIGN KEY ("batch_id") REFERENCES "training_institute"."batches"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."teacher_documents" ADD CONSTRAINT "teacher_documents_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "training_institute"."teachers"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."batch_teacher_assignments" ADD CONSTRAINT "batch_teacher_assignments_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "training_institute"."teachers"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."batch_teacher_assignments" ADD CONSTRAINT "batch_teacher_assignments_batch_id_fkey" FOREIGN KEY ("batch_id") REFERENCES "training_institute"."batches"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."enrollments" ADD CONSTRAINT "enrollments_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "training_institute"."students"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."enrollments" ADD CONSTRAINT "enrollments_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "training_institute"."courses"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."enrollments" ADD CONSTRAINT "enrollments_batch_id_fkey" FOREIGN KEY ("batch_id") REFERENCES "training_institute"."batches"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."attendance_registers" ADD CONSTRAINT "attendance_registers_batch_id_fkey" FOREIGN KEY ("batch_id") REFERENCES "training_institute"."batches"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."attendance_marks" ADD CONSTRAINT "attendance_marks_register_id_fkey" FOREIGN KEY ("register_id") REFERENCES "training_institute"."attendance_registers"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."attendance_marks" ADD CONSTRAINT "attendance_marks_enrollment_id_fkey" FOREIGN KEY ("enrollment_id") REFERENCES "training_institute"."enrollments"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."attendance_marks" ADD CONSTRAINT "attendance_marks_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "training_institute"."students"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."attendance_mark_changes" ADD CONSTRAINT "attendance_mark_changes_mark_id_fkey" FOREIGN KEY ("mark_id") REFERENCES "training_institute"."attendance_marks"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."fee_payments" ADD CONSTRAINT "fee_payments_enrollment_id_fkey" FOREIGN KEY ("enrollment_id") REFERENCES "training_institute"."enrollments"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."fee_follow_ups" ADD CONSTRAINT "fee_follow_ups_enrollment_id_fkey" FOREIGN KEY ("enrollment_id") REFERENCES "training_institute"."enrollments"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."enquiries" ADD CONSTRAINT "enquiries_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "training_institute"."courses"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."enquiries" ADD CONSTRAINT "enquiries_source_id_fkey" FOREIGN KEY ("source_id") REFERENCES "training_institute"."enquiry_sources"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."enquiries" ADD CONSTRAINT "enquiries_converted_student_id_fkey" FOREIGN KEY ("converted_student_id") REFERENCES "training_institute"."students"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."enquiries" ADD CONSTRAINT "enquiries_converted_enrollment_id_fkey" FOREIGN KEY ("converted_enrollment_id") REFERENCES "training_institute"."enrollments"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."enquiry_activities" ADD CONSTRAINT "enquiry_activities_enquiry_id_fkey" FOREIGN KEY ("enquiry_id") REFERENCES "training_institute"."enquiries"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."enquiry_demos" ADD CONSTRAINT "enquiry_demos_enquiry_id_fkey" FOREIGN KEY ("enquiry_id") REFERENCES "training_institute"."enquiries"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."enquiry_demos" ADD CONSTRAINT "enquiry_demos_batch_id_fkey" FOREIGN KEY ("batch_id") REFERENCES "training_institute"."batches"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."enquiry_demos" ADD CONSTRAINT "enquiry_demos_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "training_institute"."teachers"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."study_materials" ADD CONSTRAINT "study_materials_batch_id_fkey" FOREIGN KEY ("batch_id") REFERENCES "training_institute"."batches"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."study_materials" ADD CONSTRAINT "study_materials_posted_by_teacher_id_fkey" FOREIGN KEY ("posted_by_teacher_id") REFERENCES "training_institute"."teachers"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."homework" ADD CONSTRAINT "homework_batch_id_fkey" FOREIGN KEY ("batch_id") REFERENCES "training_institute"."batches"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."homework" ADD CONSTRAINT "homework_posted_by_teacher_id_fkey" FOREIGN KEY ("posted_by_teacher_id") REFERENCES "training_institute"."teachers"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."homework_submissions" ADD CONSTRAINT "homework_submissions_homework_id_fkey" FOREIGN KEY ("homework_id") REFERENCES "training_institute"."homework"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."homework_submissions" ADD CONSTRAINT "homework_submissions_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "training_institute"."students"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."attachments" ADD CONSTRAINT "attachments_study_material_id_fkey" FOREIGN KEY ("study_material_id") REFERENCES "training_institute"."study_materials"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."attachments" ADD CONSTRAINT "attachments_homework_id_fkey" FOREIGN KEY ("homework_id") REFERENCES "training_institute"."homework"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."attachments" ADD CONSTRAINT "attachments_submission_id_fkey" FOREIGN KEY ("submission_id") REFERENCES "training_institute"."homework_submissions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."class_tests" ADD CONSTRAINT "class_tests_batch_id_fkey" FOREIGN KEY ("batch_id") REFERENCES "training_institute"."batches"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."class_tests" ADD CONSTRAINT "class_tests_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "training_institute"."students"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."class_tests" ADD CONSTRAINT "class_tests_created_by_teacher_id_fkey" FOREIGN KEY ("created_by_teacher_id") REFERENCES "training_institute"."teachers"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."test_results" ADD CONSTRAINT "test_results_test_id_fkey" FOREIGN KEY ("test_id") REFERENCES "training_institute"."class_tests"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."test_results" ADD CONSTRAINT "test_results_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "training_institute"."students"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."test_result_changes" ADD CONSTRAINT "test_result_changes_result_id_fkey" FOREIGN KEY ("result_id") REFERENCES "training_institute"."test_results"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_institute"."test_result_changes" ADD CONSTRAINT "test_result_changes_changed_by_teacher_id_fkey" FOREIGN KEY ("changed_by_teacher_id") REFERENCES "training_institute"."teachers"("id") ON DELETE RESTRICT ON UPDATE CASCADE;


-- ---------------------------------------------------------------------------
-- Written by hand: Prisma cannot express NOT NULL lists, CHECK constraints,
-- or partial and expression indexes.
-- ---------------------------------------------------------------------------

-- At most one pending invitation per email per Workspace.
CREATE UNIQUE INDEX "workspace_invitations_one_pending_key" ON "identity"."workspace_invitations"("workspace_id", "email") WHERE "status" = 'pending';

-- Course catalog lists are empty, never null.
ALTER TABLE "training_institute"."courses" ALTER COLUMN "learning_outcomes" SET NOT NULL;
ALTER TABLE "training_institute"."courses" ALTER COLUMN "syllabus_outline" SET NOT NULL;

ALTER TABLE "training_institute"."courses" ADD CONSTRAINT "courses_duration_consistent" CHECK (
  ("duration_kind" = 'flexible' AND "duration_value" IS NULL AND "duration_unit" IS NULL)
  OR ("duration_kind" = 'fixed' AND "duration_value" BETWEEN 1 AND 1000 AND "duration_unit" IS NOT NULL)
);
ALTER TABLE "training_institute"."courses" ADD CONSTRAINT "courses_learning_hours_positive" CHECK (
  "total_learning_hours" IS NULL OR "total_learning_hours" BETWEEN 1 AND 100000
);
CREATE UNIQUE INDEX "courses_workspace_code_active_key" ON "training_institute"."courses"("workspace_id", "code") WHERE "deleted_at" IS NULL AND "code" IS NOT NULL;

-- One active Enrollment per Student per Batch.
CREATE UNIQUE INDEX "enrollments_active_student_batch_key" ON "training_institute"."enrollments"("workspace_id", "student_id", "batch_id") WHERE "deleted_at" IS NULL AND "ended_at" IS NULL;

-- One active Teacher per email and per User in a Workspace, and one active
-- assignment per Teacher per Batch.
CREATE UNIQUE INDEX "teachers_workspace_email_active_key" ON "training_institute"."teachers"("workspace_id", "email") WHERE "deleted_at" IS NULL AND "deactivated_at" IS NULL;
CREATE UNIQUE INDEX "teachers_workspace_user_active_key" ON "training_institute"."teachers"("workspace_id", "user_id") WHERE "deleted_at" IS NULL AND "deactivated_at" IS NULL AND "user_id" IS NOT NULL;
CREATE UNIQUE INDEX "batch_teacher_assignments_active_key" ON "training_institute"."batch_teacher_assignments"("workspace_id", "teacher_id", "batch_id") WHERE "deleted_at" IS NULL AND "unassigned_at" IS NULL;

-- One active Attendance Register per Batch per day.
CREATE UNIQUE INDEX "attendance_registers_active_batch_date_key" ON "training_institute"."attendance_registers"("workspace_id", "batch_id", "date") WHERE "deleted_at" IS NULL;

-- One active change per original Class, and one active Moved Class per new slot (ADR-0028).
CREATE UNIQUE INDEX "class_changes_active_class_key" ON "training_institute"."class_changes"("batch_id", "class_date", "start_time") WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "class_changes_active_moved_to_key" ON "training_institute"."class_changes"("batch_id", "moved_to_date", "moved_to_start_time") WHERE "deleted_at" IS NULL AND "kind" = 'moved';

ALTER TABLE "training_institute"."class_changes" ADD CONSTRAINT "class_changes_moved_to_check" CHECK (
  ("kind" = 'cancelled' AND "moved_to_date" IS NULL AND "moved_to_start_time" IS NULL AND "moved_to_end_time" IS NULL)
  OR ("kind" = 'moved' AND "moved_to_date" IS NOT NULL AND "moved_to_start_time" IS NOT NULL AND "moved_to_end_time" IS NOT NULL)
);

ALTER TABLE "training_institute"."holidays" ADD CONSTRAINT "holidays_date_range_check" CHECK ("end_date" >= "start_date");

-- Source names are unique among a Workspace's active Sources, ignoring case.
CREATE UNIQUE INDEX "enquiry_sources_workspace_active_name_key" ON "training_institute"."enquiry_sources"("workspace_id", lower("name")) WHERE "retired_at" IS NULL;

-- A Batch demo names a Batch; a one-to-one demo names a Teacher and no Batch.
ALTER TABLE "training_institute"."enquiry_demos" ADD CONSTRAINT "enquiry_demos_kind_check" CHECK (
  ("kind" = 'batch' AND "batch_id" IS NOT NULL AND "teacher_id" IS NULL)
  OR ("kind" = 'one_to_one' AND "teacher_id" IS NOT NULL AND "batch_id" IS NULL)
);

-- A paid demo has an amount from ₹1 to ₹1,00,000; a free demo has none.
ALTER TABLE "training_institute"."enquiry_demos" ADD CONSTRAINT "enquiry_demos_fee_check" CHECK (
  ("fee_kind" = 'free' AND "fee_amount_paise" IS NULL AND "fee_paid_at" IS NULL)
  OR ("fee_kind" = 'paid' AND "fee_amount_paise" IS NOT NULL
      AND "fee_amount_paise" BETWEEN 100 AND 10000000)
);

-- One live Submission per Homework and Student; undone ones keep withdrawn_at.
CREATE UNIQUE INDEX "homework_submissions_live_key" ON "training_institute"."homework_submissions"("homework_id", "student_id") WHERE "withdrawn_at" IS NULL;

-- Homework is due on or after its Class date.
ALTER TABLE "training_institute"."homework" ADD CONSTRAINT "homework_due_on_check" CHECK ("due_on" >= "class_date");

-- A Teacher's post names the Teacher; the Owner's doesn't.
ALTER TABLE "training_institute"."study_materials" ADD CONSTRAINT "study_materials_poster_check" CHECK (
    ("posted_by_role" = 'teacher') = ("posted_by_teacher_id" IS NOT NULL)
);
ALTER TABLE "training_institute"."homework" ADD CONSTRAINT "homework_poster_check" CHECK (
    ("posted_by_role" = 'teacher') = ("posted_by_teacher_id" IS NOT NULL)
);

-- An attachment belongs to at most one Study Material, Homework, or Submission.
-- With none it is an upload waiting to be attached (ADR-0033).
ALTER TABLE "training_institute"."attachments" ADD CONSTRAINT "attachments_owner_check" CHECK (
    num_nonnulls("study_material_id", "homework_id", "submission_id") <= 1
);

-- A single-student Test names its Student; a whole-batch Test doesn't.
ALTER TABLE "training_institute"."class_tests" ADD CONSTRAINT "class_tests_scope_check" CHECK (
    ("scope" = 'student') = ("student_id" IS NOT NULL)
);

-- Maximum 1 to 1000; a pass mark, if set, from 0 to the maximum.
ALTER TABLE "training_institute"."class_tests" ADD CONSTRAINT "class_tests_marks_check" CHECK (
    "max_marks" BETWEEN 1 AND 1000
    AND ("pass_marks" IS NULL OR "pass_marks" BETWEEN 0 AND "max_marks")
);

-- A Teacher's Test names the Teacher; the Owner's doesn't.
ALTER TABLE "training_institute"."class_tests" ADD CONSTRAINT "class_tests_creator_check" CHECK (
    ("created_by_role" = 'teacher') = ("created_by_teacher_id" IS NOT NULL)
);

-- Only a scored result has marks: zero or more, in half-mark steps.
ALTER TABLE "training_institute"."test_results" ADD CONSTRAINT "test_results_marks_check" CHECK (
    ("status" = 'scored') = ("marks" IS NOT NULL)
    AND ("marks" IS NULL OR ("marks" >= 0 AND "marks" * 2 = trunc("marks" * 2)))
);

-- A Teacher's change names the Teacher; the Owner's doesn't.
ALTER TABLE "training_institute"."test_result_changes" ADD CONSTRAINT "test_result_changes_changer_check" CHECK (
    ("changed_by_role" = 'teacher') = ("changed_by_teacher_id" IS NOT NULL)
);

-- At most one open Fee Follow-up per Enrollment: logging a new one closes the last.
CREATE UNIQUE INDEX "fee_follow_ups_one_open_per_enrollment" ON "training_institute"."fee_follow_ups"("enrollment_id") WHERE "closed_at" IS NULL;

-- A closed Fee Follow-up says why it closed.
ALTER TABLE "training_institute"."fee_follow_ups" ADD CONSTRAINT "fee_follow_ups_close_reason_when_closed" CHECK (("closed_at" IS NULL) = ("close_reason" IS NULL));
