-- Projects & structure (CM-401, `modules/03`): every M4 table of the
-- `construction_projects` schema, so later M4 tickets add code, not tables.
-- Touches no other schema (ADR-0030). Product rules behind the columns:
-- ADR CM-0013; attachments and the Gallery index: ADR CM-0014.
--
-- Generated by `prisma migrate diff`, then hand-written sections: partial
-- unique indexes and CHECK constraints Prisma cannot express, the album and
-- testing-item seeds for Projects created before M4, and Gallery rows for
-- their image and PDF documents.

-- CreateEnum
CREATE TYPE "construction_projects"."project_type" AS ENUM ('residential', 'commercial', 'mixed_use', 'villas', 'plotting', 'industrial', 'institutional', 'infrastructure', 'interiors', 'other');

-- CreateEnum
CREATE TYPE "construction_projects"."wing_type" AS ENUM ('commercial', 'residential', 'bungalow_scheme', 'residential_and_commercial', 'plotting_scheme', 'institutional', 'individual_unit', 'industrial');

-- CreateEnum
CREATE TYPE "construction_projects"."floor_kind" AS ENUM ('terrace', 'typed', 'ground', 'basement', 'site', 'other');

-- AlterTable
ALTER TABLE "construction_projects"."documents" ADD COLUMN     "thumb_key" TEXT;

-- AlterTable
ALTER TABLE "construction_projects"."projects" ADD COLUMN     "budget_value" BIGINT,
ADD COLUMN     "logo_key" TEXT,
ADD COLUMN     "project_type" "construction_projects"."project_type",
ADD COLUMN     "use_logo_in_reports" BOOLEAN NOT NULL DEFAULT false;

-- CreateTable
CREATE TABLE "construction_projects"."phases" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "project_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "position" INTEGER NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "phases_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_projects"."wings" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "project_id" UUID NOT NULL,
    "phase_id" UUID NOT NULL,
    "wing_type" "construction_projects"."wing_type" NOT NULL,
    "name" TEXT NOT NULL,
    "config" JSONB NOT NULL,
    "position" INTEGER NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "wings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_projects"."floors" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "wing_id" UUID NOT NULL,
    "kind" "construction_projects"."floor_kind" NOT NULL,
    "name" TEXT NOT NULL,
    "level" INTEGER NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "floors_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_projects"."units" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "wing_id" UUID NOT NULL,
    "floor_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "position" INTEGER NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "units_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_projects"."locations" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "project_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "position" INTEGER NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "locations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_projects"."drawing_albums" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "project_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "drawing_albums_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_projects"."drawings" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "project_id" UUID NOT NULL,
    "album_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "drawings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_projects"."drawing_revisions" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "drawing_id" UUID NOT NULL,
    "revision" INTEGER NOT NULL,
    "file_key" TEXT NOT NULL,
    "file_name" TEXT NOT NULL,
    "content_type" TEXT NOT NULL,
    "bytes" INTEGER NOT NULL,
    "thumb_key" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "drawing_revisions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_projects"."testing_items" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "project_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "testing_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_projects"."testing_reports" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "project_id" UUID NOT NULL,
    "item_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "report_date" DATE NOT NULL,
    "remark" TEXT,
    "file_key" TEXT NOT NULL,
    "file_name" TEXT NOT NULL,
    "content_type" TEXT NOT NULL,
    "bytes" INTEGER NOT NULL,
    "thumb_key" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "testing_reports_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_projects"."media_items" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "project_id" UUID NOT NULL,
    "source" TEXT NOT NULL,
    "source_id" UUID NOT NULL,
    "file_key" TEXT NOT NULL,
    "thumb_key" TEXT,
    "file_name" TEXT NOT NULL,
    "content_type" TEXT NOT NULL,
    "bytes" INTEGER NOT NULL,
    "uploaded_by" TEXT NOT NULL,
    "uploaded_at" TIMESTAMPTZ(3) NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),

    CONSTRAINT "media_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_projects"."hidden_modules" (
    "workspace_id" TEXT NOT NULL,
    "project_id" UUID NOT NULL,
    "module_key" TEXT NOT NULL,
    "hidden_by" TEXT NOT NULL,
    "hidden_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "hidden_modules_pkey" PRIMARY KEY ("project_id","module_key")
);

-- CreateTable
CREATE TABLE "construction_projects"."pins" (
    "workspace_id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "project_id" UUID NOT NULL,
    "pinned_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "pins_pkey" PRIMARY KEY ("workspace_id","user_id","project_id")
);

-- CreateTable
CREATE TABLE "construction_projects"."member_preferences" (
    "workspace_id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "tile_order" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "dashboard_sections" JSONB,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "member_preferences_pkey" PRIMARY KEY ("workspace_id","user_id")
);

-- CreateIndex
CREATE INDEX "phases_workspace_id_project_id_idx" ON "construction_projects"."phases"("workspace_id", "project_id");

-- CreateIndex
CREATE INDEX "wings_workspace_id_project_id_idx" ON "construction_projects"."wings"("workspace_id", "project_id");

-- CreateIndex
CREATE INDEX "wings_phase_id_idx" ON "construction_projects"."wings"("phase_id");

-- CreateIndex
CREATE INDEX "floors_wing_id_level_idx" ON "construction_projects"."floors"("wing_id", "level");

-- CreateIndex
CREATE INDEX "floors_workspace_id_idx" ON "construction_projects"."floors"("workspace_id");

-- CreateIndex
CREATE INDEX "units_floor_id_position_idx" ON "construction_projects"."units"("floor_id", "position");

-- CreateIndex
CREATE INDEX "units_wing_id_idx" ON "construction_projects"."units"("wing_id");

-- CreateIndex
CREATE INDEX "units_workspace_id_idx" ON "construction_projects"."units"("workspace_id");

-- CreateIndex
CREATE INDEX "locations_workspace_id_project_id_idx" ON "construction_projects"."locations"("workspace_id", "project_id");

-- CreateIndex
CREATE INDEX "drawing_albums_workspace_id_project_id_idx" ON "construction_projects"."drawing_albums"("workspace_id", "project_id");

-- CreateIndex
CREATE INDEX "drawings_workspace_id_project_id_idx" ON "construction_projects"."drawings"("workspace_id", "project_id");

-- CreateIndex
CREATE INDEX "drawings_album_id_deleted_at_idx" ON "construction_projects"."drawings"("album_id", "deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "drawing_revisions_file_key_key" ON "construction_projects"."drawing_revisions"("file_key");

-- CreateIndex
CREATE INDEX "drawing_revisions_workspace_id_idx" ON "construction_projects"."drawing_revisions"("workspace_id");

-- CreateIndex
CREATE UNIQUE INDEX "drawing_revisions_drawing_id_revision_key" ON "construction_projects"."drawing_revisions"("drawing_id", "revision");

-- CreateIndex
CREATE INDEX "testing_items_workspace_id_project_id_idx" ON "construction_projects"."testing_items"("workspace_id", "project_id");

-- CreateIndex
CREATE UNIQUE INDEX "testing_reports_file_key_key" ON "construction_projects"."testing_reports"("file_key");

-- CreateIndex
CREATE INDEX "testing_reports_workspace_id_project_id_report_date_idx" ON "construction_projects"."testing_reports"("workspace_id", "project_id", "report_date");

-- CreateIndex
CREATE INDEX "testing_reports_item_id_deleted_at_idx" ON "construction_projects"."testing_reports"("item_id", "deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "media_items_file_key_key" ON "construction_projects"."media_items"("file_key");

-- CreateIndex
CREATE INDEX "media_items_workspace_id_project_id_uploaded_at_idx" ON "construction_projects"."media_items"("workspace_id", "project_id", "uploaded_at");

-- CreateIndex
CREATE INDEX "media_items_source_source_id_idx" ON "construction_projects"."media_items"("source", "source_id");

-- CreateIndex
CREATE INDEX "hidden_modules_workspace_id_idx" ON "construction_projects"."hidden_modules"("workspace_id");

-- CreateIndex
CREATE INDEX "pins_project_id_idx" ON "construction_projects"."pins"("project_id");

-- AddForeignKey
ALTER TABLE "construction_projects"."phases" ADD CONSTRAINT "phases_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "construction_projects"."projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_projects"."wings" ADD CONSTRAINT "wings_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "construction_projects"."projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_projects"."wings" ADD CONSTRAINT "wings_phase_id_fkey" FOREIGN KEY ("phase_id") REFERENCES "construction_projects"."phases"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_projects"."floors" ADD CONSTRAINT "floors_wing_id_fkey" FOREIGN KEY ("wing_id") REFERENCES "construction_projects"."wings"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_projects"."units" ADD CONSTRAINT "units_wing_id_fkey" FOREIGN KEY ("wing_id") REFERENCES "construction_projects"."wings"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_projects"."units" ADD CONSTRAINT "units_floor_id_fkey" FOREIGN KEY ("floor_id") REFERENCES "construction_projects"."floors"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_projects"."locations" ADD CONSTRAINT "locations_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "construction_projects"."projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_projects"."drawing_albums" ADD CONSTRAINT "drawing_albums_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "construction_projects"."projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_projects"."drawings" ADD CONSTRAINT "drawings_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "construction_projects"."projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_projects"."drawings" ADD CONSTRAINT "drawings_album_id_fkey" FOREIGN KEY ("album_id") REFERENCES "construction_projects"."drawing_albums"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_projects"."drawing_revisions" ADD CONSTRAINT "drawing_revisions_drawing_id_fkey" FOREIGN KEY ("drawing_id") REFERENCES "construction_projects"."drawings"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_projects"."testing_items" ADD CONSTRAINT "testing_items_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "construction_projects"."projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_projects"."testing_reports" ADD CONSTRAINT "testing_reports_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "construction_projects"."projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_projects"."testing_reports" ADD CONSTRAINT "testing_reports_item_id_fkey" FOREIGN KEY ("item_id") REFERENCES "construction_projects"."testing_items"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_projects"."media_items" ADD CONSTRAINT "media_items_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "construction_projects"."projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_projects"."hidden_modules" ADD CONSTRAINT "hidden_modules_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "construction_projects"."projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_projects"."pins" ADD CONSTRAINT "pins_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "construction_projects"."projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Names unique ignoring case among live rows (ADR CM-0013).
CREATE UNIQUE INDEX "phases_live_name_key" ON "construction_projects"."phases"("project_id", lower("name")) WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "wings_live_name_key" ON "construction_projects"."wings"("project_id", lower("name")) WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "units_live_name_key" ON "construction_projects"."units"("wing_id", lower("name")) WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "locations_live_name_key" ON "construction_projects"."locations"("project_id", lower("name")) WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "drawing_albums_live_name_key" ON "construction_projects"."drawing_albums"("project_id", lower("name")) WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX "testing_items_live_name_key" ON "construction_projects"."testing_items"("project_id", lower("name")) WHERE "deleted_at" IS NULL;

-- Bounds the domain also checks; the database refuses what slips past.
ALTER TABLE "construction_projects"."projects" ADD CONSTRAINT "projects_budget_value_check" CHECK ("budget_value" IS NULL OR "budget_value" >= 0);
ALTER TABLE "construction_projects"."drawing_revisions" ADD CONSTRAINT "drawing_revisions_revision_check" CHECK ("revision" >= 1);
ALTER TABLE "construction_projects"."drawing_revisions" ADD CONSTRAINT "drawing_revisions_bytes_check" CHECK ("bytes" > 0);
ALTER TABLE "construction_projects"."testing_reports" ADD CONSTRAINT "testing_reports_bytes_check" CHECK ("bytes" > 0);
ALTER TABLE "construction_projects"."media_items" ADD CONSTRAINT "media_items_bytes_check" CHECK ("bytes" > 0);

-- Projects created before M4 get the seed albums and testing items new
-- Projects receive on creation (ADR CM-0013 §8–9; keep in step with
-- apps/construction-management/src/projects/domain/project-seeds.ts).
INSERT INTO "construction_projects"."drawing_albums" ("id", "workspace_id", "project_id", "name", "is_seed", "created_by", "updated_by")
SELECT gen_random_uuid(), p."workspace_id", p."id", s."name", true, 'system', 'system'
FROM "construction_projects"."projects" p
CROSS JOIN (VALUES ('Architect'), ('Electrical'), ('Plumbing'), ('Structural Drawing')) AS s ("name")
WHERE p."deleted_at" IS NULL;

INSERT INTO "construction_projects"."testing_items" ("id", "workspace_id", "project_id", "name", "is_seed", "created_by", "updated_by")
SELECT gen_random_uuid(), p."workspace_id", p."id", s."name", true, 'system', 'system'
FROM "construction_projects"."projects" p
CROSS JOIN (VALUES ('Rcc cube'), ('Steel'), ('Cement'), ('Bricks')) AS s ("name")
WHERE p."deleted_at" IS NULL;

-- The Gallery indexes the images and PDFs already kept as Project
-- Documents (ADR CM-0014).
INSERT INTO "construction_projects"."media_items" ("id", "workspace_id", "project_id", "source", "source_id", "file_key", "thumb_key", "file_name", "content_type", "bytes", "uploaded_by", "uploaded_at", "deleted_at")
SELECT gen_random_uuid(), d."workspace_id", d."project_id", 'document', d."id", d."file_key", NULL, d."file_name", d."content_type", d."bytes", d."created_by", d."created_at", d."deleted_at"
FROM "construction_projects"."documents" d
WHERE d."content_type" IN ('application/pdf', 'image/png', 'image/jpeg', 'image/webp');
