-- Staff HRMS (CM-302, `modules/10`): the `construction_hrms` schema with
-- every M3 table, so later M3 tickets add code, not tables. Touches no
-- other schema (ADR-0030). Product rules behind the columns: ADR CM-0012;
-- statutory tables: ADR CM-0008.
--
-- Generated by `prisma migrate diff`, then two hand-written sections:
-- CHECK constraints and partial indexes Prisma cannot express, and the
-- statutory seed rows (generated from
-- `apps/construction-management/src/hrms/infrastructure/seeds/statutory/*.json`
-- by `statutorySeedSql`; a unit test keeps them in step).


-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "construction_hrms";

-- CreateEnum
CREATE TYPE "construction_hrms"."gps_requirement" AS ENUM ('disabled', 'record_only', 'required');

-- CreateEnum
CREATE TYPE "construction_hrms"."leave_year" AS ENUM ('calendar', 'financial');

-- CreateEnum
CREATE TYPE "construction_hrms"."branch_kind" AS ENUM ('office_branch', 'project_site');

-- CreateEnum
CREATE TYPE "construction_hrms"."holiday_type" AS ENUM ('national', 'festival', 'company');

-- CreateEnum
CREATE TYPE "construction_hrms"."rotation_type" AS ENUM ('week', 'month', 'custom_cycle');

-- CreateEnum
CREATE TYPE "construction_hrms"."attendance_source" AS ENUM ('check_in', 'manual', 'missed_checkout');

-- CreateEnum
CREATE TYPE "construction_hrms"."approval_status" AS ENUM ('none', 'pending', 'approved', 'rejected');

-- CreateEnum
CREATE TYPE "construction_hrms"."accrual_mode" AS ENUM ('none', 'upfront', 'periodic');

-- CreateEnum
CREATE TYPE "construction_hrms"."accrual_frequency" AS ENUM ('monthly');

-- CreateEnum
CREATE TYPE "construction_hrms"."leave_ledger_kind" AS ENUM ('initial', 'accrual', 'carry_forward', 'adjustment', 'used', 'reserved', 'released', 'restored');

-- CreateEnum
CREATE TYPE "construction_hrms"."leave_request_status" AS ENUM ('pending', 'approved', 'rejected', 'withdrawn', 'cancellation_requested', 'cancelled');

-- CreateEnum
CREATE TYPE "construction_hrms"."leave_session" AS ENUM ('full', 'morning', 'afternoon');

-- CreateEnum
CREATE TYPE "construction_hrms"."leave_decision_stage" AS ENUM ('request', 'cancellation');

-- CreateEnum
CREATE TYPE "construction_hrms"."decision_outcome" AS ENUM ('approved', 'rejected');

-- CreateEnum
CREATE TYPE "construction_hrms"."component_basis" AS ENUM ('fixed', 'percent_of_base');

-- CreateEnum
CREATE TYPE "construction_hrms"."gender" AS ENUM ('male', 'female', 'other');

-- CreateEnum
CREATE TYPE "construction_hrms"."salary_slip_kind" AS ENUM ('regular', 'advance');

-- CreateEnum
CREATE TYPE "construction_hrms"."salary_slip_status" AS ENUM ('calculated', 'approved', 'paid');

-- CreateEnum
CREATE TYPE "construction_hrms"."payment_mode" AS ENUM ('cash', 'bank');

-- CreateEnum
CREATE TYPE "construction_hrms"."pt_applies_to" AS ENUM ('everyone', 'men', 'women');

-- CreateTable
CREATE TABLE "construction_hrms"."settings" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "gps_requirement" "construction_hrms"."gps_requirement" NOT NULL DEFAULT 'disabled',
    "grace_minutes" INTEGER NOT NULL DEFAULT 15,
    "working_hours_per_day" DECIMAL(4,2) NOT NULL DEFAULT 8,
    "half_day_hours" DECIMAL(4,2) NOT NULL DEFAULT 4,
    "working_days" INTEGER[],
    "leave_approval_levels" INTEGER NOT NULL DEFAULT 1,
    "leave_year" "construction_hrms"."leave_year" NOT NULL DEFAULT 'calendar',
    "carry_forward_enabled" BOOLEAN NOT NULL DEFAULT false,
    "carry_forward_max_days" DECIMAL(5,2),
    "leave_accrual_enabled" BOOLEAN NOT NULL DEFAULT false,
    "auto_salary_calculation" BOOLEAN NOT NULL DEFAULT false,
    "salary_calculation_day" INTEGER,
    "pt_state_code" CHAR(2),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,

    CONSTRAINT "settings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_hrms"."branches" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "kind" "construction_hrms"."branch_kind" NOT NULL,
    "name" TEXT NOT NULL,
    "address" TEXT,
    "project_id" UUID,
    "latitude" DECIMAL(9,6) NOT NULL,
    "longitude" DECIMAL(9,6) NOT NULL,
    "radius_metres" INTEGER NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "branches_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_hrms"."member_branches" (
    "workspace_id" TEXT NOT NULL,
    "member_id" UUID NOT NULL,
    "branch_id" UUID NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,

    CONSTRAINT "member_branches_pkey" PRIMARY KEY ("member_id","branch_id")
);

-- CreateTable
CREATE TABLE "construction_hrms"."holidays" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "holiday_date" DATE NOT NULL,
    "type" "construction_hrms"."holiday_type" NOT NULL,
    "is_optional" BOOLEAN NOT NULL DEFAULT false,
    "description" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "holidays_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_hrms"."shift_templates" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "start_time" CHAR(5) NOT NULL,
    "end_time" CHAR(5) NOT NULL,
    "working_days" INTEGER[],
    "working_hours" DECIMAL(4,2) NOT NULL,
    "half_day_hours" DECIMAL(4,2) NOT NULL,
    "grace_minutes" INTEGER NOT NULL,
    "overtime_allowed" BOOLEAN NOT NULL DEFAULT false,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "shift_templates_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_hrms"."rotation_templates" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "rotation_type" "construction_hrms"."rotation_type" NOT NULL,
    "days_per_cycle" INTEGER,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "rotation_templates_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_hrms"."rotation_slots" (
    "id" UUID NOT NULL,
    "rotation_id" UUID NOT NULL,
    "position" INTEGER NOT NULL,
    "shift_template_id" UUID,
    "is_week_off" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "rotation_slots_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_hrms"."shift_assignments" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "member_id" UUID NOT NULL,
    "shift_template_id" UUID,
    "rotation_template_id" UUID,
    "effective_from" DATE NOT NULL,
    "effective_to" DATE,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "shift_assignments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_hrms"."attendance_entries" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "member_id" UUID NOT NULL,
    "attendance_date" DATE NOT NULL,
    "check_in_at" TIMESTAMPTZ(3) NOT NULL,
    "check_in_latitude" DECIMAL(9,6),
    "check_in_longitude" DECIMAL(9,6),
    "check_in_accuracy" DECIMAL(8,2),
    "check_in_branch_id" UUID,
    "check_out_at" TIMESTAMPTZ(3),
    "check_out_latitude" DECIMAL(9,6),
    "check_out_longitude" DECIMAL(9,6),
    "check_out_accuracy" DECIMAL(8,2),
    "check_out_branch_id" UUID,
    "source" "construction_hrms"."attendance_source" NOT NULL,
    "approval_status" "construction_hrms"."approval_status" NOT NULL DEFAULT 'none',
    "out_of_fence" BOOLEAN NOT NULL DEFAULT false,
    "reason" TEXT,
    "decided_by" TEXT,
    "decided_at" TIMESTAMPTZ(3),
    "rejection_reason" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "attendance_entries_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_hrms"."leave_types" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "yearly_limit" DECIMAL(6,2) NOT NULL,
    "is_paid" BOOLEAN NOT NULL,
    "requires_approval" BOOLEAN NOT NULL DEFAULT true,
    "approval_levels" INTEGER,
    "max_consecutive_days" INTEGER,
    "carry_forward" BOOLEAN NOT NULL DEFAULT false,
    "max_carry_forward" DECIMAL(6,2),
    "accrual_mode" "construction_hrms"."accrual_mode" NOT NULL DEFAULT 'none',
    "accrual_frequency" "construction_hrms"."accrual_frequency",
    "accrual_day" INTEGER,
    "credit_per_period" DECIMAL(6,2),
    "allow_advance_use" BOOLEAN NOT NULL DEFAULT false,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "is_seed" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "leave_types_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_hrms"."leave_structures" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "leave_structures_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_hrms"."leave_structure_lines" (
    "id" UUID NOT NULL,
    "structure_id" UUID NOT NULL,
    "leave_type_id" UUID NOT NULL,
    "entitlement_days" DECIMAL(6,2),

    CONSTRAINT "leave_structure_lines_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_hrms"."leave_structure_assignments" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "member_id" UUID NOT NULL,
    "structure_id" UUID NOT NULL,
    "effective_from" DATE NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "leave_structure_assignments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_hrms"."leave_ledger_entries" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "member_id" UUID NOT NULL,
    "leave_type_id" UUID NOT NULL,
    "leave_year" VARCHAR(5) NOT NULL,
    "kind" "construction_hrms"."leave_ledger_kind" NOT NULL,
    "days" DECIMAL(6,2) NOT NULL,
    "entry_date" DATE NOT NULL,
    "period_key" CHAR(7),
    "request_id" UUID,
    "reason" TEXT,
    "reverses_entry_id" UUID,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,

    CONSTRAINT "leave_ledger_entries_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_hrms"."leave_requests" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "member_id" UUID NOT NULL,
    "leave_type_id" UUID NOT NULL,
    "from_date" DATE NOT NULL,
    "to_date" DATE NOT NULL,
    "total_days" DECIMAL(5,1) NOT NULL,
    "leave_year" VARCHAR(5) NOT NULL,
    "reason" TEXT NOT NULL,
    "status" "construction_hrms"."leave_request_status" NOT NULL DEFAULT 'pending',
    "approval_levels" INTEGER NOT NULL DEFAULT 1,
    "current_level" INTEGER NOT NULL DEFAULT 1,
    "approval_remarks" TEXT,
    "rejection_reason" TEXT,
    "cancellation_reason" TEXT,
    "applied_by_member_id" UUID NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,

    CONSTRAINT "leave_requests_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_hrms"."leave_request_days" (
    "id" UUID NOT NULL,
    "request_id" UUID NOT NULL,
    "leave_date" DATE NOT NULL,
    "session" "construction_hrms"."leave_session" NOT NULL,

    CONSTRAINT "leave_request_days_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_hrms"."leave_decisions" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "request_id" UUID NOT NULL,
    "stage" "construction_hrms"."leave_decision_stage" NOT NULL,
    "level" INTEGER NOT NULL,
    "outcome" "construction_hrms"."decision_outcome" NOT NULL,
    "remarks" TEXT,
    "decider_member_id" UUID,
    "decided_by" TEXT NOT NULL,
    "decided_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "leave_decisions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_hrms"."salary_structures" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "pf_applicable" BOOLEAN NOT NULL DEFAULT false,
    "pf_employee_percent" DECIMAL(5,2),
    "pf_cap_at_ceiling" BOOLEAN NOT NULL DEFAULT true,
    "pf_wage_ceiling" INTEGER,
    "esi_applicable" BOOLEAN NOT NULL DEFAULT false,
    "esi_employee_percent" DECIMAL(5,2),
    "pt_applicable" BOOLEAN NOT NULL DEFAULT false,
    "pt_monthly_amount" INTEGER,
    "deduct_absent_days" BOOLEAN NOT NULL DEFAULT true,
    "deduct_unpaid_leave" BOOLEAN NOT NULL DEFAULT true,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "salary_structures_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_hrms"."salary_components" (
    "id" UUID NOT NULL,
    "structure_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "basis" "construction_hrms"."component_basis" NOT NULL,
    "amount" INTEGER,
    "percent" DECIMAL(5,2),
    "is_balancing" BOOLEAN NOT NULL DEFAULT false,
    "counts_for_pf_wage" BOOLEAN NOT NULL DEFAULT false,
    "sort_order" INTEGER NOT NULL,

    CONSTRAINT "salary_components_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_hrms"."salary_deductions" (
    "id" UUID NOT NULL,
    "structure_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "amount" INTEGER NOT NULL,
    "sort_order" INTEGER NOT NULL,

    CONSTRAINT "salary_deductions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_hrms"."employee_salary_configs" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "member_id" UUID NOT NULL,
    "structure_id" UUID NOT NULL,
    "base_monthly" INTEGER NOT NULL,
    "component_overrides" JSONB NOT NULL DEFAULT '{}',
    "gender" "construction_hrms"."gender",
    "effective_from" DATE NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "employee_salary_configs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_hrms"."salary_runs" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "month" CHAR(7) NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,

    CONSTRAINT "salary_runs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_hrms"."salary_slips" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "run_id" UUID,
    "member_id" UUID NOT NULL,
    "month" CHAR(7) NOT NULL,
    "kind" "construction_hrms"."salary_slip_kind" NOT NULL,
    "status" "construction_hrms"."salary_slip_status" NOT NULL DEFAULT 'calculated',
    "structure_id" UUID,
    "days_in_month" INTEGER NOT NULL,
    "working_days" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "present_days" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "absent_days" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "half_days" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "paid_leave_days" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "unpaid_leave_days" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "week_off_days" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "holiday_days" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "payable_days" DECIMAL(5,2) NOT NULL DEFAULT 0,
    "overtime_hours" DECIMAL(6,2) NOT NULL DEFAULT 0,
    "total_hours" DECIMAL(6,2) NOT NULL DEFAULT 0,
    "base_monthly" INTEGER NOT NULL DEFAULT 0,
    "components" JSONB NOT NULL DEFAULT '[]',
    "overtime_pay" INTEGER NOT NULL DEFAULT 0,
    "gross_earnings" INTEGER NOT NULL DEFAULT 0,
    "pf_employee" INTEGER NOT NULL DEFAULT 0,
    "esi_employee" INTEGER NOT NULL DEFAULT 0,
    "professional_tax" INTEGER NOT NULL DEFAULT 0,
    "absent_deduction" INTEGER NOT NULL DEFAULT 0,
    "unpaid_leave_deduction" INTEGER NOT NULL DEFAULT 0,
    "other_deductions" INTEGER NOT NULL DEFAULT 0,
    "advance_recovered" INTEGER NOT NULL DEFAULT 0,
    "net_payable" INTEGER NOT NULL DEFAULT 0,
    "pf_employer" INTEGER NOT NULL DEFAULT 0,
    "eps_employer" INTEGER NOT NULL DEFAULT 0,
    "esi_employer" INTEGER NOT NULL DEFAULT 0,
    "statutory_snapshot" JSONB NOT NULL DEFAULT '{}',
    "approved_by" TEXT,
    "approved_at" TIMESTAMPTZ(3),
    "paid_by" TEXT,
    "paid_at" TIMESTAMPTZ(3),
    "payment_mode" "construction_hrms"."payment_mode",
    "payment_date" DATE,
    "payment_reference" TEXT,
    "payslip_key" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "salary_slips_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_hrms"."salary_advances" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "member_id" UUID NOT NULL,
    "slip_id" UUID,
    "amount" INTEGER NOT NULL,
    "instalments" INTEGER NOT NULL DEFAULT 1,
    "advance_date" DATE NOT NULL,
    "first_recovery_month" CHAR(7) NOT NULL,
    "reason" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,
    "updated_by" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),
    "deleted_by" TEXT,

    CONSTRAINT "salary_advances_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_hrms"."salary_advance_recoveries" (
    "id" UUID NOT NULL,
    "advance_id" UUID NOT NULL,
    "slip_id" UUID NOT NULL,
    "month" CHAR(7) NOT NULL,
    "amount" INTEGER NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" TEXT NOT NULL,

    CONSTRAINT "salary_advance_recoveries_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_hrms"."month_locks" (
    "id" UUID NOT NULL,
    "workspace_id" TEXT NOT NULL,
    "member_id" UUID,
    "month" CHAR(7) NOT NULL,
    "slip_id" UUID,
    "locked_at" TIMESTAMPTZ(3) NOT NULL,
    "locked_by" TEXT NOT NULL,

    CONSTRAINT "month_locks_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_hrms"."statutory_pf_rates" (
    "id" UUID NOT NULL,
    "effective_from" DATE NOT NULL,
    "wage_ceiling" INTEGER NOT NULL,
    "employee_percent" DECIMAL(5,2) NOT NULL,
    "employer_percent" DECIMAL(5,2) NOT NULL,
    "eps_percent" DECIMAL(5,2) NOT NULL,
    "source" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "statutory_pf_rates_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_hrms"."statutory_esi_rates" (
    "id" UUID NOT NULL,
    "effective_from" DATE NOT NULL,
    "wage_ceiling" INTEGER NOT NULL,
    "pwd_wage_ceiling" INTEGER NOT NULL,
    "employee_percent" DECIMAL(5,2) NOT NULL,
    "employer_percent" DECIMAL(5,2) NOT NULL,
    "source" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "statutory_esi_rates_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "construction_hrms"."statutory_pt_slabs" (
    "id" UUID NOT NULL,
    "state_code" CHAR(2) NOT NULL,
    "effective_from" DATE NOT NULL,
    "applies_to" "construction_hrms"."pt_applies_to" NOT NULL DEFAULT 'everyone',
    "gross_from" INTEGER NOT NULL,
    "gross_to" INTEGER,
    "monthly_amount" INTEGER NOT NULL,
    "special_month" INTEGER,
    "special_month_amount" INTEGER,
    "source" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "statutory_pt_slabs_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "settings_workspace_id_key" ON "construction_hrms"."settings"("workspace_id");

-- CreateIndex
CREATE INDEX "branches_workspace_id_kind_idx" ON "construction_hrms"."branches"("workspace_id", "kind");

-- CreateIndex
CREATE INDEX "branches_workspace_id_project_id_idx" ON "construction_hrms"."branches"("workspace_id", "project_id");

-- CreateIndex
CREATE INDEX "member_branches_workspace_id_branch_id_idx" ON "construction_hrms"."member_branches"("workspace_id", "branch_id");

-- CreateIndex
CREATE INDEX "holidays_workspace_id_holiday_date_idx" ON "construction_hrms"."holidays"("workspace_id", "holiday_date");

-- CreateIndex
CREATE INDEX "shift_templates_workspace_id_idx" ON "construction_hrms"."shift_templates"("workspace_id");

-- CreateIndex
CREATE INDEX "rotation_templates_workspace_id_idx" ON "construction_hrms"."rotation_templates"("workspace_id");

-- CreateIndex
CREATE UNIQUE INDEX "rotation_slots_rotation_id_position_key" ON "construction_hrms"."rotation_slots"("rotation_id", "position");

-- CreateIndex
CREATE INDEX "shift_assignments_workspace_id_member_id_effective_from_idx" ON "construction_hrms"."shift_assignments"("workspace_id", "member_id", "effective_from");

-- CreateIndex
CREATE INDEX "attendance_entries_workspace_id_attendance_date_idx" ON "construction_hrms"."attendance_entries"("workspace_id", "attendance_date");

-- CreateIndex
CREATE INDEX "attendance_entries_workspace_id_member_id_attendance_date_idx" ON "construction_hrms"."attendance_entries"("workspace_id", "member_id", "attendance_date");

-- CreateIndex
CREATE INDEX "attendance_entries_workspace_id_approval_status_idx" ON "construction_hrms"."attendance_entries"("workspace_id", "approval_status");

-- CreateIndex
CREATE INDEX "leave_types_workspace_id_idx" ON "construction_hrms"."leave_types"("workspace_id");

-- CreateIndex
CREATE INDEX "leave_structures_workspace_id_idx" ON "construction_hrms"."leave_structures"("workspace_id");

-- CreateIndex
CREATE UNIQUE INDEX "leave_structure_lines_structure_id_leave_type_id_key" ON "construction_hrms"."leave_structure_lines"("structure_id", "leave_type_id");

-- CreateIndex
CREATE INDEX "leave_structure_assignments_workspace_id_member_id_effectiv_idx" ON "construction_hrms"."leave_structure_assignments"("workspace_id", "member_id", "effective_from");

-- CreateIndex
CREATE UNIQUE INDEX "leave_ledger_entries_reverses_entry_id_key" ON "construction_hrms"."leave_ledger_entries"("reverses_entry_id");

-- CreateIndex
CREATE INDEX "leave_ledger_entries_workspace_id_member_id_leave_type_id_l_idx" ON "construction_hrms"."leave_ledger_entries"("workspace_id", "member_id", "leave_type_id", "leave_year");

-- CreateIndex
CREATE INDEX "leave_ledger_entries_request_id_idx" ON "construction_hrms"."leave_ledger_entries"("request_id");

-- CreateIndex
CREATE INDEX "leave_requests_workspace_id_member_id_from_date_idx" ON "construction_hrms"."leave_requests"("workspace_id", "member_id", "from_date");

-- CreateIndex
CREATE INDEX "leave_requests_workspace_id_status_idx" ON "construction_hrms"."leave_requests"("workspace_id", "status");

-- CreateIndex
CREATE INDEX "leave_request_days_leave_date_idx" ON "construction_hrms"."leave_request_days"("leave_date");

-- CreateIndex
CREATE UNIQUE INDEX "leave_request_days_request_id_leave_date_key" ON "construction_hrms"."leave_request_days"("request_id", "leave_date");

-- CreateIndex
CREATE INDEX "leave_decisions_request_id_idx" ON "construction_hrms"."leave_decisions"("request_id");

-- CreateIndex
CREATE INDEX "salary_structures_workspace_id_idx" ON "construction_hrms"."salary_structures"("workspace_id");

-- CreateIndex
CREATE INDEX "salary_components_structure_id_idx" ON "construction_hrms"."salary_components"("structure_id");

-- CreateIndex
CREATE INDEX "salary_deductions_structure_id_idx" ON "construction_hrms"."salary_deductions"("structure_id");

-- CreateIndex
CREATE INDEX "employee_salary_configs_workspace_id_member_id_effective_fr_idx" ON "construction_hrms"."employee_salary_configs"("workspace_id", "member_id", "effective_from");

-- CreateIndex
CREATE UNIQUE INDEX "salary_runs_workspace_id_month_key" ON "construction_hrms"."salary_runs"("workspace_id", "month");

-- CreateIndex
CREATE INDEX "salary_slips_workspace_id_month_idx" ON "construction_hrms"."salary_slips"("workspace_id", "month");

-- CreateIndex
CREATE INDEX "salary_slips_workspace_id_member_id_month_idx" ON "construction_hrms"."salary_slips"("workspace_id", "member_id", "month");

-- CreateIndex
CREATE UNIQUE INDEX "salary_advances_slip_id_key" ON "construction_hrms"."salary_advances"("slip_id");

-- CreateIndex
CREATE INDEX "salary_advances_workspace_id_member_id_idx" ON "construction_hrms"."salary_advances"("workspace_id", "member_id");

-- CreateIndex
CREATE UNIQUE INDEX "salary_advance_recoveries_advance_id_slip_id_key" ON "construction_hrms"."salary_advance_recoveries"("advance_id", "slip_id");

-- CreateIndex
CREATE INDEX "month_locks_workspace_id_month_idx" ON "construction_hrms"."month_locks"("workspace_id", "month");

-- CreateIndex
CREATE UNIQUE INDEX "statutory_pf_rates_effective_from_key" ON "construction_hrms"."statutory_pf_rates"("effective_from");

-- CreateIndex
CREATE UNIQUE INDEX "statutory_esi_rates_effective_from_key" ON "construction_hrms"."statutory_esi_rates"("effective_from");

-- CreateIndex
CREATE UNIQUE INDEX "statutory_pt_slabs_state_code_effective_from_applies_to_gro_key" ON "construction_hrms"."statutory_pt_slabs"("state_code", "effective_from", "applies_to", "gross_from");

-- AddForeignKey
ALTER TABLE "construction_hrms"."member_branches" ADD CONSTRAINT "member_branches_branch_id_fkey" FOREIGN KEY ("branch_id") REFERENCES "construction_hrms"."branches"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_hrms"."rotation_slots" ADD CONSTRAINT "rotation_slots_rotation_id_fkey" FOREIGN KEY ("rotation_id") REFERENCES "construction_hrms"."rotation_templates"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_hrms"."rotation_slots" ADD CONSTRAINT "rotation_slots_shift_template_id_fkey" FOREIGN KEY ("shift_template_id") REFERENCES "construction_hrms"."shift_templates"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_hrms"."shift_assignments" ADD CONSTRAINT "shift_assignments_shift_template_id_fkey" FOREIGN KEY ("shift_template_id") REFERENCES "construction_hrms"."shift_templates"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_hrms"."shift_assignments" ADD CONSTRAINT "shift_assignments_rotation_template_id_fkey" FOREIGN KEY ("rotation_template_id") REFERENCES "construction_hrms"."rotation_templates"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_hrms"."leave_structure_lines" ADD CONSTRAINT "leave_structure_lines_structure_id_fkey" FOREIGN KEY ("structure_id") REFERENCES "construction_hrms"."leave_structures"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_hrms"."leave_structure_lines" ADD CONSTRAINT "leave_structure_lines_leave_type_id_fkey" FOREIGN KEY ("leave_type_id") REFERENCES "construction_hrms"."leave_types"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_hrms"."leave_structure_assignments" ADD CONSTRAINT "leave_structure_assignments_structure_id_fkey" FOREIGN KEY ("structure_id") REFERENCES "construction_hrms"."leave_structures"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_hrms"."leave_request_days" ADD CONSTRAINT "leave_request_days_request_id_fkey" FOREIGN KEY ("request_id") REFERENCES "construction_hrms"."leave_requests"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_hrms"."leave_decisions" ADD CONSTRAINT "leave_decisions_request_id_fkey" FOREIGN KEY ("request_id") REFERENCES "construction_hrms"."leave_requests"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_hrms"."salary_components" ADD CONSTRAINT "salary_components_structure_id_fkey" FOREIGN KEY ("structure_id") REFERENCES "construction_hrms"."salary_structures"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_hrms"."salary_deductions" ADD CONSTRAINT "salary_deductions_structure_id_fkey" FOREIGN KEY ("structure_id") REFERENCES "construction_hrms"."salary_structures"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_hrms"."employee_salary_configs" ADD CONSTRAINT "employee_salary_configs_structure_id_fkey" FOREIGN KEY ("structure_id") REFERENCES "construction_hrms"."salary_structures"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_hrms"."salary_slips" ADD CONSTRAINT "salary_slips_run_id_fkey" FOREIGN KEY ("run_id") REFERENCES "construction_hrms"."salary_runs"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_hrms"."salary_advance_recoveries" ADD CONSTRAINT "salary_advance_recoveries_advance_id_fkey" FOREIGN KEY ("advance_id") REFERENCES "construction_hrms"."salary_advances"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "construction_hrms"."salary_advance_recoveries" ADD CONSTRAINT "salary_advance_recoveries_slip_id_fkey" FOREIGN KEY ("slip_id") REFERENCES "construction_hrms"."salary_slips"("id") ON DELETE CASCADE ON UPDATE CASCADE;



-- ---------------------------------------------------------------------------
-- Written by hand: Prisma cannot express CHECK constraints, or partial and
-- expression indexes. Each repeats a rule the hrms domain enforces.
-- ---------------------------------------------------------------------------

-- A set of ISO weekdays (1 = Monday … 7 = Sunday): at least one, no repeats.
CREATE FUNCTION "construction_hrms"."is_iso_weekday_set"(days integer[]) RETURNS boolean
  LANGUAGE sql IMMUTABLE STRICT
  AS $$ SELECT cardinality(days) BETWEEN 1 AND 7 AND days <@ ARRAY[1, 2, 3, 4, 5, 6, 7] AND cardinality(days) = (SELECT count(DISTINCT day) FROM unnest(days) AS day) $$;

-- `YYYY-MM`.
CREATE FUNCTION "construction_hrms"."is_month_key"(value text) RETURNS boolean
  LANGUAGE sql IMMUTABLE STRICT
  AS $$ SELECT value ~ '^[0-9]{4}-(0[1-9]|1[0-2])$' $$;

-- Settings (CM-303). One row per Company is the unique `workspace_id`.
ALTER TABLE "construction_hrms"."settings" ADD CONSTRAINT "settings_rules_check" CHECK (
  "grace_minutes" BETWEEN 0 AND 120
  AND "working_hours_per_day" > 0 AND "working_hours_per_day" <= 24
  AND "half_day_hours" > 0 AND "half_day_hours" < "working_hours_per_day"
  AND "construction_hrms"."is_iso_weekday_set"("working_days")
  AND "leave_approval_levels" BETWEEN 1 AND 2
  AND (("carry_forward_enabled" AND "carry_forward_max_days" IS NOT NULL AND "carry_forward_max_days" >= 0)
    OR (NOT "carry_forward_enabled" AND "carry_forward_max_days" IS NULL))
  AND (("auto_salary_calculation" AND "salary_calculation_day" BETWEEN 1 AND 28)
    OR (NOT "auto_salary_calculation" AND "salary_calculation_day" IS NULL))
  AND ("pt_state_code" IS NULL OR "pt_state_code" ~ '^[0-9]{2}$')
);

-- Branches (CM-304): a point and a radius; a project site names its Project.
-- Office branch names are unique per Company, site labels per Project.
ALTER TABLE "construction_hrms"."branches" ADD CONSTRAINT "branches_fence_check" CHECK (
  "latitude" BETWEEN -90 AND 90
  AND "longitude" BETWEEN -180 AND 180
  AND "radius_metres" > 0
  AND (("kind" = 'project_site') = ("project_id" IS NOT NULL))
);
CREATE UNIQUE INDEX "branches_live_office_name_key" ON "construction_hrms"."branches"("workspace_id", lower("name")) WHERE "deleted_at" IS NULL AND "kind" = 'office_branch';
CREATE UNIQUE INDEX "branches_live_site_name_key" ON "construction_hrms"."branches"("workspace_id", "project_id", lower("name")) WHERE "deleted_at" IS NULL AND "kind" = 'project_site';

-- One live holiday per date per Company (CM-305).
CREATE UNIQUE INDEX "holidays_live_date_key" ON "construction_hrms"."holidays"("workspace_id", "holiday_date") WHERE "deleted_at" IS NULL;

-- Shift and rotation templates (CM-306).
ALTER TABLE "construction_hrms"."shift_templates" ADD CONSTRAINT "shift_templates_rules_check" CHECK (
  "start_time" ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'
  AND "end_time" ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'
  AND "construction_hrms"."is_iso_weekday_set"("working_days")
  AND "working_hours" > 0 AND "working_hours" <= 24
  AND "half_day_hours" > 0 AND "half_day_hours" < "working_hours"
  AND "grace_minutes" BETWEEN 0 AND 120
);
CREATE UNIQUE INDEX "shift_templates_live_name_key" ON "construction_hrms"."shift_templates"("workspace_id", lower("name")) WHERE "deleted_at" IS NULL;
ALTER TABLE "construction_hrms"."rotation_templates" ADD CONSTRAINT "rotation_templates_cycle_check" CHECK (
  ("days_per_cycle" IS NULL OR "days_per_cycle" > 0)
  AND ("rotation_type" <> 'custom_cycle' OR "days_per_cycle" BETWEEN 2 AND 12)
);
CREATE UNIQUE INDEX "rotation_templates_live_name_key" ON "construction_hrms"."rotation_templates"("workspace_id", lower("name")) WHERE "deleted_at" IS NULL;
ALTER TABLE "construction_hrms"."rotation_slots" ADD CONSTRAINT "rotation_slots_shift_check" CHECK (
  "position" >= 0
  AND ("is_week_off" = ("shift_template_id" IS NULL))
);

-- Shift assignments (CM-307): a shift or a rotation; at most one open
-- ("until changed") assignment and one start date per member.
ALTER TABLE "construction_hrms"."shift_assignments" ADD CONSTRAINT "shift_assignments_rules_check" CHECK (
  num_nonnulls("shift_template_id", "rotation_template_id") = 1
  AND ("effective_to" IS NULL OR "effective_to" >= "effective_from")
);
CREATE UNIQUE INDEX "shift_assignments_live_open_key" ON "construction_hrms"."shift_assignments"("workspace_id", "member_id") WHERE "deleted_at" IS NULL AND "effective_to" IS NULL;
CREATE UNIQUE INDEX "shift_assignments_live_start_key" ON "construction_hrms"."shift_assignments"("workspace_id", "member_id", "effective_from") WHERE "deleted_at" IS NULL;

-- Attendance entries (CM-308): at most one open entry per member (the
-- active check-in guard); only check-ins skip approval; a decision has its
-- decider and a rejection its reason.
CREATE UNIQUE INDEX "attendance_entries_one_open_key" ON "construction_hrms"."attendance_entries"("workspace_id", "member_id") WHERE "deleted_at" IS NULL AND "check_out_at" IS NULL AND "approval_status" <> 'rejected';
ALTER TABLE "construction_hrms"."attendance_entries" ADD CONSTRAINT "attendance_entries_rules_check" CHECK (
  ("check_out_at" IS NULL OR "check_out_at" > "check_in_at")
  AND (("check_in_latitude" IS NULL) = ("check_in_longitude" IS NULL))
  AND (("check_out_latitude" IS NULL) = ("check_out_longitude" IS NULL))
  AND ("check_in_latitude" IS NULL OR ("check_in_latitude" BETWEEN -90 AND 90 AND "check_in_longitude" BETWEEN -180 AND 180))
  AND ("check_out_latitude" IS NULL OR ("check_out_latitude" BETWEEN -90 AND 90 AND "check_out_longitude" BETWEEN -180 AND 180))
  AND ("check_in_accuracy" IS NULL OR "check_in_accuracy" >= 0)
  AND ("check_out_accuracy" IS NULL OR "check_out_accuracy" >= 0)
  AND ("source" = 'check_in' OR "check_out_at" IS NOT NULL)
  AND ("source" = 'check_in' OR "approval_status" <> 'none')
  AND ("approval_status" NOT IN ('approved', 'rejected') OR ("decided_by" IS NOT NULL AND "decided_at" IS NOT NULL))
  AND ("approval_status" <> 'rejected' OR "rejection_reason" IS NOT NULL)
);

-- Leave types (CM-310): accrual settings exactly when periodic; carry-forward
-- cap exactly when carrying forward. Names unique per Company.
ALTER TABLE "construction_hrms"."leave_types" ADD CONSTRAINT "leave_types_rules_check" CHECK (
  "yearly_limit" >= 0
  AND ("approval_levels" IS NULL OR "approval_levels" BETWEEN 1 AND 2)
  AND ("max_consecutive_days" IS NULL OR "max_consecutive_days" > 0)
  AND ("carry_forward" = ("max_carry_forward" IS NOT NULL))
  AND ("max_carry_forward" IS NULL OR "max_carry_forward" >= 0)
  AND (("accrual_mode" = 'periodic'
      AND "accrual_frequency" IS NOT NULL
      AND "accrual_day" BETWEEN 1 AND 28
      AND "credit_per_period" > 0)
    OR ("accrual_mode" <> 'periodic'
      AND "accrual_frequency" IS NULL
      AND "accrual_day" IS NULL
      AND "credit_per_period" IS NULL))
);
CREATE UNIQUE INDEX "leave_types_live_name_key" ON "construction_hrms"."leave_types"("workspace_id", lower("name")) WHERE "deleted_at" IS NULL;

-- Leave structures (CM-311).
CREATE UNIQUE INDEX "leave_structures_live_name_key" ON "construction_hrms"."leave_structures"("workspace_id", lower("name")) WHERE "deleted_at" IS NULL;
ALTER TABLE "construction_hrms"."leave_structure_lines" ADD CONSTRAINT "leave_structure_lines_entitlement_check" CHECK ("entitlement_days" IS NULL OR "entitlement_days" >= 0);
CREATE UNIQUE INDEX "leave_structure_assignments_live_start_key" ON "construction_hrms"."leave_structure_assignments"("workspace_id", "member_id", "effective_from") WHERE "deleted_at" IS NULL;

-- Leave ledger (ADR CM-0004): signs follow the kind; an accrual period, a
-- year's opening credit and a year's carry forward are posted once.
ALTER TABLE "construction_hrms"."leave_ledger_entries" ADD CONSTRAINT "leave_ledger_entries_rules_check" CHECK (
  "leave_year" ~ '^([0-9]{4}|[0-9]{2}-[0-9]{2})$'
  AND (CASE "kind"
    WHEN 'initial' THEN "days" >= 0
    WHEN 'carry_forward' THEN "days" >= 0
    WHEN 'accrual' THEN "days" > 0
    WHEN 'released' THEN "days" > 0
    WHEN 'restored' THEN "days" > 0
    WHEN 'used' THEN "days" < 0
    WHEN 'reserved' THEN "days" < 0
    ELSE "days" <> 0
  END)
  AND ("kind" <> 'accrual' OR "construction_hrms"."is_month_key"("period_key"))
  AND ("kind" NOT IN ('used', 'reserved', 'released', 'restored') OR "request_id" IS NOT NULL)
  AND ("kind" <> 'adjustment' OR "reason" IS NOT NULL)
);
CREATE UNIQUE INDEX "leave_ledger_entries_accrual_key" ON "construction_hrms"."leave_ledger_entries"("member_id", "leave_type_id", "period_key") WHERE "kind" = 'accrual' AND "reverses_entry_id" IS NULL;
CREATE UNIQUE INDEX "leave_ledger_entries_initial_key" ON "construction_hrms"."leave_ledger_entries"("member_id", "leave_type_id", "leave_year") WHERE "kind" = 'initial' AND "reverses_entry_id" IS NULL;
CREATE UNIQUE INDEX "leave_ledger_entries_carry_forward_key" ON "construction_hrms"."leave_ledger_entries"("member_id", "leave_type_id", "leave_year") WHERE "kind" = 'carry_forward' AND "reverses_entry_id" IS NULL;

-- Leave requests (CM-312).
ALTER TABLE "construction_hrms"."leave_requests" ADD CONSTRAINT "leave_requests_rules_check" CHECK (
  "to_date" >= "from_date"
  AND "total_days" > 0
  AND char_length(btrim("reason")) >= 10
  AND "leave_year" ~ '^([0-9]{4}|[0-9]{2}-[0-9]{2})$'
  AND "approval_levels" BETWEEN 1 AND 2
  AND "current_level" BETWEEN 1 AND "approval_levels"
  AND ("status" <> 'rejected' OR "rejection_reason" IS NOT NULL)
  AND ("status" NOT IN ('cancellation_requested', 'cancelled') OR "cancellation_reason" IS NOT NULL)
);
ALTER TABLE "construction_hrms"."leave_decisions" ADD CONSTRAINT "leave_decisions_rules_check" CHECK (
  "level" BETWEEN 1 AND 2
  AND ("outcome" <> 'rejected' OR "remarks" IS NOT NULL)
);
-- One decision per level on the request itself; two approvers cannot both
-- decide the same level.
CREATE UNIQUE INDEX "leave_decisions_request_level_key" ON "construction_hrms"."leave_decisions"("request_id", "level") WHERE "stage" = 'request';

-- Salary structures (CM-314).
ALTER TABLE "construction_hrms"."salary_structures" ADD CONSTRAINT "salary_structures_rules_check" CHECK (
  ("pf_employee_percent" IS NULL OR "pf_employee_percent" BETWEEN 0 AND 100)
  AND ("esi_employee_percent" IS NULL OR "esi_employee_percent" BETWEEN 0 AND 100)
  AND ("pf_wage_ceiling" IS NULL OR "pf_wage_ceiling" > 0)
  AND ("pt_monthly_amount" IS NULL OR "pt_monthly_amount" >= 0)
);
CREATE UNIQUE INDEX "salary_structures_live_name_key" ON "construction_hrms"."salary_structures"("workspace_id", lower("name")) WHERE "deleted_at" IS NULL;
ALTER TABLE "construction_hrms"."salary_components" ADD CONSTRAINT "salary_components_value_check" CHECK (
  "sort_order" >= 0
  AND (("is_balancing" AND "amount" IS NULL AND "percent" IS NULL)
    OR (NOT "is_balancing" AND "basis" = 'fixed' AND "amount" >= 0 AND "percent" IS NULL)
    OR (NOT "is_balancing" AND "basis" = 'percent_of_base' AND "percent" BETWEEN 0 AND 100 AND "amount" IS NULL))
);
CREATE UNIQUE INDEX "salary_components_name_key" ON "construction_hrms"."salary_components"("structure_id", lower("name"));
CREATE UNIQUE INDEX "salary_components_one_balancing_key" ON "construction_hrms"."salary_components"("structure_id") WHERE "is_balancing";
ALTER TABLE "construction_hrms"."salary_deductions" ADD CONSTRAINT "salary_deductions_amount_check" CHECK ("amount" >= 0 AND "sort_order" >= 0);

-- Employee salary configuration (CM-315).
ALTER TABLE "construction_hrms"."employee_salary_configs" ADD CONSTRAINT "employee_salary_configs_rules_check" CHECK (
  "base_monthly" >= 0
  AND jsonb_typeof("component_overrides") = 'object'
);
CREATE UNIQUE INDEX "employee_salary_configs_live_start_key" ON "construction_hrms"."employee_salary_configs"("workspace_id", "member_id", "effective_from") WHERE "deleted_at" IS NULL;

-- Salary runs and slips (CM-316): one live regular slip per member per
-- month; approval and payment carry who and when.
ALTER TABLE "construction_hrms"."salary_runs" ADD CONSTRAINT "salary_runs_month_check" CHECK ("construction_hrms"."is_month_key"("month"));
ALTER TABLE "construction_hrms"."salary_slips" ADD CONSTRAINT "salary_slips_rules_check" CHECK (
  "construction_hrms"."is_month_key"("month")
  AND "days_in_month" BETWEEN 28 AND 31
  AND (("kind" = 'regular') = ("run_id" IS NOT NULL))
  AND "working_days" >= 0 AND "present_days" >= 0 AND "absent_days" >= 0
  AND "half_days" >= 0 AND "paid_leave_days" >= 0 AND "unpaid_leave_days" >= 0
  AND "week_off_days" >= 0 AND "holiday_days" >= 0 AND "payable_days" >= 0
  AND "overtime_hours" >= 0 AND "total_hours" >= 0
  AND "base_monthly" >= 0 AND "overtime_pay" >= 0 AND "gross_earnings" >= 0
  AND "pf_employee" >= 0 AND "esi_employee" >= 0 AND "professional_tax" >= 0
  AND "absent_deduction" >= 0 AND "unpaid_leave_deduction" >= 0
  AND "other_deductions" >= 0 AND "advance_recovered" >= 0
  AND "pf_employer" >= 0 AND "eps_employer" >= 0 AND "esi_employer" >= 0
  AND jsonb_typeof("components") = 'array'
  AND jsonb_typeof("statutory_snapshot") = 'object'
  AND ("status" = 'calculated' OR ("approved_by" IS NOT NULL AND "approved_at" IS NOT NULL))
  AND ("status" <> 'paid' OR ("paid_by" IS NOT NULL AND "paid_at" IS NOT NULL AND "payment_mode" IS NOT NULL AND "payment_date" IS NOT NULL))
);
CREATE UNIQUE INDEX "salary_slips_live_regular_key" ON "construction_hrms"."salary_slips"("workspace_id", "member_id", "month") WHERE "kind" = 'regular' AND "deleted_at" IS NULL;

-- Advances (ADR CM-0012 §15).
ALTER TABLE "construction_hrms"."salary_advances" ADD CONSTRAINT "salary_advances_rules_check" CHECK (
  "amount" > 0
  AND "instalments" BETWEEN 1 AND 24
  AND "construction_hrms"."is_month_key"("first_recovery_month")
);
ALTER TABLE "construction_hrms"."salary_advance_recoveries" ADD CONSTRAINT "salary_advance_recoveries_rules_check" CHECK (
  "amount" > 0
  AND "construction_hrms"."is_month_key"("month")
);

-- Month locks (ADR CM-0012 §17): one per member per month, one per Company
-- per month.
ALTER TABLE "construction_hrms"."month_locks" ADD CONSTRAINT "month_locks_month_check" CHECK ("construction_hrms"."is_month_key"("month"));
CREATE UNIQUE INDEX "month_locks_member_month_key" ON "construction_hrms"."month_locks"("workspace_id", "member_id", "month") WHERE "member_id" IS NOT NULL;
CREATE UNIQUE INDEX "month_locks_company_month_key" ON "construction_hrms"."month_locks"("workspace_id", "month") WHERE "member_id" IS NULL;

-- Statutory tables (ADR CM-0008).
ALTER TABLE "construction_hrms"."statutory_pf_rates" ADD CONSTRAINT "statutory_pf_rates_rules_check" CHECK (
  "wage_ceiling" > 0
  AND "employee_percent" BETWEEN 0 AND 100
  AND "employer_percent" BETWEEN 0 AND 100
  AND "eps_percent" BETWEEN 0 AND "employer_percent"
);
ALTER TABLE "construction_hrms"."statutory_esi_rates" ADD CONSTRAINT "statutory_esi_rates_rules_check" CHECK (
  "wage_ceiling" > 0
  AND "pwd_wage_ceiling" >= "wage_ceiling"
  AND "employee_percent" BETWEEN 0 AND 100
  AND "employer_percent" BETWEEN 0 AND 100
);
ALTER TABLE "construction_hrms"."statutory_pt_slabs" ADD CONSTRAINT "statutory_pt_slabs_rules_check" CHECK (
  "state_code" ~ '^[0-9]{2}$'
  AND "gross_from" >= 0
  AND ("gross_to" IS NULL OR "gross_to" >= "gross_from")
  AND "monthly_amount" >= 0
  AND (("special_month" IS NULL) = ("special_month_amount" IS NULL))
  AND ("special_month" IS NULL OR ("special_month" BETWEEN 1 AND 12 AND "special_month_amount" >= 0))
);


-- ---------------------------------------------------------------------------
-- Statutory seed rows (ADR CM-0008), one line per JSON row. Idempotent.
-- ---------------------------------------------------------------------------

INSERT INTO "construction_hrms"."statutory_pf_rates" ("id", "effective_from", "wage_ceiling", "employee_percent", "employer_percent", "eps_percent", "source") VALUES (gen_random_uuid(), '2014-09-01', 1500000, 12.00, 12.00, 8.33, 'EPF Scheme 1952 para 2(f) as amended by GSR 609(E), 22 Aug 2014 (wage ceiling Rs 15,000 from 1 Sep 2014); EPF & MP Act 1952 s.6 (12%); EPS 1995 (8.33% of wage up to the ceiling)') ON CONFLICT DO NOTHING;
INSERT INTO "construction_hrms"."statutory_esi_rates" ("id", "effective_from", "wage_ceiling", "pwd_wage_ceiling", "employee_percent", "employer_percent", "source") VALUES (gen_random_uuid(), '2019-07-01', 2100000, 2500000, 0.75, 3.25, 'ESI (Central) Rules 1950 r.51 as amended by GSR 423(E), 13 Jun 2019 (0.75% / 3.25% from 1 Jul 2019); wage ceiling Rs 21,000 (Rs 25,000 for persons with disability) from 1 Jan 2017') ON CONFLICT DO NOTHING;
INSERT INTO "construction_hrms"."statutory_pt_slabs" ("id", "state_code", "effective_from", "applies_to", "gross_from", "gross_to", "monthly_amount", "special_month", "special_month_amount", "source") VALUES (gen_random_uuid(), '29', '2025-04-01', 'everyone', 2500000, NULL, 20000, 2, 30000, 'Karnataka Tax on Professions, Trades, Callings and Employments Act 1976, Schedule entry 1 as amended by Karnataka Act 33 of 2025 (from 1 Apr 2025): Rs 25,000 and above, Rs 200 a month, Rs 300 in February') ON CONFLICT DO NOTHING;
INSERT INTO "construction_hrms"."statutory_pt_slabs" ("id", "state_code", "effective_from", "applies_to", "gross_from", "gross_to", "monthly_amount", "special_month", "special_month_amount", "source") VALUES (gen_random_uuid(), '27', '2023-04-01', 'men', 750001, 1000000, 17500, NULL, NULL, 'Maharashtra State Tax on Professions, Trades, Callings and Employments Act 1975, Schedule I entry 1 (as in force from 1 Apr 2023): men above Rs 7,500 up to Rs 10,000, Rs 175') ON CONFLICT DO NOTHING;
INSERT INTO "construction_hrms"."statutory_pt_slabs" ("id", "state_code", "effective_from", "applies_to", "gross_from", "gross_to", "monthly_amount", "special_month", "special_month_amount", "source") VALUES (gen_random_uuid(), '27', '2023-04-01', 'men', 1000001, NULL, 20000, 2, 30000, 'Maharashtra State Tax on Professions, Trades, Callings and Employments Act 1975, Schedule I entry 1 (as in force from 1 Apr 2023): men above Rs 10,000, Rs 200 a month, Rs 300 in February') ON CONFLICT DO NOTHING;
INSERT INTO "construction_hrms"."statutory_pt_slabs" ("id", "state_code", "effective_from", "applies_to", "gross_from", "gross_to", "monthly_amount", "special_month", "special_month_amount", "source") VALUES (gen_random_uuid(), '27', '2023-04-01', 'women', 2500001, NULL, 20000, 2, 30000, 'Maharashtra State Tax on Professions, Trades, Callings and Employments Act 1975, Schedule I entry 1 as amended from 1 Apr 2023: women up to Rs 25,000 exempt; above, Rs 200 a month, Rs 300 in February') ON CONFLICT DO NOTHING;
INSERT INTO "construction_hrms"."statutory_pt_slabs" ("id", "state_code", "effective_from", "applies_to", "gross_from", "gross_to", "monthly_amount", "special_month", "special_month_amount", "source") VALUES (gen_random_uuid(), '36', '2025-04-01', 'everyone', 1500001, 2000000, 15000, NULL, NULL, 'Telangana Tax on Professions, Trades, Callings and Employments Act 1987, Schedule entry 1 (in force FY 2025-26): above Rs 15,000 up to Rs 20,000, Rs 150') ON CONFLICT DO NOTHING;
INSERT INTO "construction_hrms"."statutory_pt_slabs" ("id", "state_code", "effective_from", "applies_to", "gross_from", "gross_to", "monthly_amount", "special_month", "special_month_amount", "source") VALUES (gen_random_uuid(), '36', '2025-04-01', 'everyone', 2000001, NULL, 20000, NULL, NULL, 'Telangana Tax on Professions, Trades, Callings and Employments Act 1987, Schedule entry 1 (in force FY 2025-26): above Rs 20,000, Rs 200') ON CONFLICT DO NOTHING;
INSERT INTO "construction_hrms"."statutory_pt_slabs" ("id", "state_code", "effective_from", "applies_to", "gross_from", "gross_to", "monthly_amount", "special_month", "special_month_amount", "source") VALUES (gen_random_uuid(), '37', '2025-04-01', 'everyone', 1500001, 2000000, 15000, NULL, NULL, 'Andhra Pradesh Tax on Professions, Trades, Callings and Employments Act 1987, Schedule entry 1 (in force FY 2025-26): above Rs 15,000 up to Rs 20,000, Rs 150') ON CONFLICT DO NOTHING;
INSERT INTO "construction_hrms"."statutory_pt_slabs" ("id", "state_code", "effective_from", "applies_to", "gross_from", "gross_to", "monthly_amount", "special_month", "special_month_amount", "source") VALUES (gen_random_uuid(), '37', '2025-04-01', 'everyone', 2000001, NULL, 20000, NULL, NULL, 'Andhra Pradesh Tax on Professions, Trades, Callings and Employments Act 1987, Schedule entry 1 (in force FY 2025-26): above Rs 20,000, Rs 200') ON CONFLICT DO NOTHING;
INSERT INTO "construction_hrms"."statutory_pt_slabs" ("id", "state_code", "effective_from", "applies_to", "gross_from", "gross_to", "monthly_amount", "special_month", "special_month_amount", "source") VALUES (gen_random_uuid(), '19', '2025-04-01', 'everyone', 1000001, 1500000, 11000, NULL, NULL, 'West Bengal State Tax on Professions, Trades, Callings and Employments Act 1979, Schedule I entry 1 (in force FY 2025-26): above Rs 10,000 up to Rs 15,000, Rs 110') ON CONFLICT DO NOTHING;
INSERT INTO "construction_hrms"."statutory_pt_slabs" ("id", "state_code", "effective_from", "applies_to", "gross_from", "gross_to", "monthly_amount", "special_month", "special_month_amount", "source") VALUES (gen_random_uuid(), '19', '2025-04-01', 'everyone', 1500001, 2500000, 13000, NULL, NULL, 'West Bengal State Tax on Professions, Trades, Callings and Employments Act 1979, Schedule I entry 1 (in force FY 2025-26): above Rs 15,000 up to Rs 25,000, Rs 130') ON CONFLICT DO NOTHING;
INSERT INTO "construction_hrms"."statutory_pt_slabs" ("id", "state_code", "effective_from", "applies_to", "gross_from", "gross_to", "monthly_amount", "special_month", "special_month_amount", "source") VALUES (gen_random_uuid(), '19', '2025-04-01', 'everyone', 2500001, 4000000, 15000, NULL, NULL, 'West Bengal State Tax on Professions, Trades, Callings and Employments Act 1979, Schedule I entry 1 (in force FY 2025-26): above Rs 25,000 up to Rs 40,000, Rs 150') ON CONFLICT DO NOTHING;
INSERT INTO "construction_hrms"."statutory_pt_slabs" ("id", "state_code", "effective_from", "applies_to", "gross_from", "gross_to", "monthly_amount", "special_month", "special_month_amount", "source") VALUES (gen_random_uuid(), '19', '2025-04-01', 'everyone', 4000001, NULL, 20000, NULL, NULL, 'West Bengal State Tax on Professions, Trades, Callings and Employments Act 1979, Schedule I entry 1 (in force FY 2025-26): above Rs 40,000, Rs 200') ON CONFLICT DO NOTHING;
