import { StatusCodes } from "http-status-codes";

import type {
  OpenApiComponents,
  OpenApiOperation,
} from "@/app/api/_lib/openapi";
import { XLSX_CONTENT_TYPE } from "@/src/procurement/infrastructure/inventory-workbook";

import {
  AdjustConstructionProcurementStockRequestModel,
  ConstructionProcurementInventoryRowResponseModel,
  ConstructionProcurementSiteLocationModel,
  ConstructionProcurementStockEntryResponseModel,
  ConstructionProcurementStockLocationModel,
  ConstructionProcurementStockMovementParamsModel,
  ConstructionProcurementStockMovementResponseModel,
  ConstructionProcurementStockRegisterRowResponseModel,
  DeleteConstructionProcurementStockMovementRequestModel,
  EditConstructionProcurementStockMovementRequestModel,
  ExportConstructionProcurementInventoryRequestModel,
  GetConstructionProcurementInventoryHistoryRequestModel,
  GetConstructionProcurementInventoryHistoryResponseModel,
  GetConstructionProcurementStockRegisterRequestModel,
  GetConstructionProcurementStockRegisterResponseModel,
  ImportConstructionProcurementInventoryRequestModel,
  ImportConstructionProcurementInventoryResponseModel,
  INVENTORY_PATH,
  ListConstructionProcurementInventoryRequestModel,
  ListConstructionProcurementInventoryResponseModel,
  RecordConstructionProcurementStockMovementsRequestModel,
  RecordConstructionProcurementStockMovementsResponseModel,
  SampleConstructionProcurementInventoryRequestModel,
  UpdateConstructionProcurementStockSettingsRequestModel,
} from "./inventory-models";

const TAGS = ["Construction · Procurement"];

const READ = [
  StatusCodes.BAD_REQUEST,
  StatusCodes.UNAUTHORIZED,
  StatusCodes.FORBIDDEN,
  StatusCodes.NOT_FOUND,
];
const WRITE = [...READ, StatusCodes.CONFLICT, StatusCodes.PAYMENT_REQUIRED];

const MENU =
  "Current Inventory (`procurement.current_inventory`) on a Project; Central store (`procurement.central_store`) for a Store";

/** Request and Response models of `/api/construction/procurement/inventory` (M5). */
export const inventoryOpenApiComponents: OpenApiComponents = {
  ConstructionProcurementStockLocationModel,
  ConstructionProcurementSiteLocationModel,
  UpdateConstructionProcurementStockSettingsRequestModel,
  RecordConstructionProcurementStockMovementsRequestModel,
  AdjustConstructionProcurementStockRequestModel,
  EditConstructionProcurementStockMovementRequestModel,
  DeleteConstructionProcurementStockMovementRequestModel,
  ConstructionProcurementInventoryRowResponseModel,
  ListConstructionProcurementInventoryResponseModel,
  ConstructionProcurementStockMovementResponseModel,
  RecordConstructionProcurementStockMovementsResponseModel,
  ConstructionProcurementStockEntryResponseModel,
  GetConstructionProcurementInventoryHistoryResponseModel,
  ConstructionProcurementStockRegisterRowResponseModel,
  GetConstructionProcurementStockRegisterResponseModel,
  ImportConstructionProcurementInventoryResponseModel,
};

/** Operations of `/api/construction/procurement/inventory` (M5). */
export const inventoryOpenApiOperations: OpenApiOperation[] = [
  {
    method: "get",
    path: INVENTORY_PATH,
    summary: `Stock per material at a Project or Store: estimated, in stock, in transit in / out, minimum, state (${MENU}, read)`,
    tags: TAGS,
    query: ListConstructionProcurementInventoryRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "The stock list",
    successSchema: ListConstructionProcurementInventoryResponseModel,
    errors: READ,
  },
  {
    method: "get",
    path: `${INVENTORY_PATH}/export`,
    summary: `Export Data: the stock list as .xlsx (${MENU}, print)`,
    tags: TAGS,
    query: ExportConstructionProcurementInventoryRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "An .xlsx file",
    successBinaryContentTypes: [XLSX_CONTENT_TYPE],
    errors: READ,
  },
  {
    method: "get",
    path: `${INVENTORY_PATH}/sample`,
    summary: `Export Sample Excel: the Import Inventory Stock sheet (${MENU}, read)`,
    tags: TAGS,
    query: SampleConstructionProcurementInventoryRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "An .xlsx file",
    successBinaryContentTypes: [XLSX_CONTENT_TYPE],
    errors: READ,
  },
  {
    method: "post",
    path: `${INVENTORY_PATH}/import`,
    summary: `Import Inventory Stock from the sample (the .xlsx as the body): preview with ?dryRun=true, post Opening stock and Estimated Qty for all rows or none with false — IMPORT_HAS_ERRORS 400 (${MENU}, create)`,
    tags: TAGS,
    query: ImportConstructionProcurementInventoryRequestModel,
    bodyBinaryContentTypes: [XLSX_CONTENT_TYPE],
    successStatus: StatusCodes.OK,
    successDescription: "The row-by-row check (201 with `imported` when posted)",
    successSchema: ImportConstructionProcurementInventoryResponseModel,
    errors: WRITE,
  },
  {
    method: "get",
    path: `${INVENTORY_PATH}/history`,
    summary: `A material's history at a location: every ledger entry with source, counterparty, site location, who and running balance (${MENU}, read)`,
    tags: TAGS,
    query: GetConstructionProcurementInventoryHistoryRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "A page of entries, newest date first",
    successSchema: GetConstructionProcurementInventoryHistoryResponseModel,
    errors: READ,
  },
  {
    method: "get",
    path: `${INVENTORY_PATH}/register`,
    summary: `Stock Register for a date range: opening, received, transferred in / out, issued, received from store, consumed, missing, adjustment, closing (${MENU}, report)`,
    tags: TAGS,
    query: GetConstructionProcurementStockRegisterRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "One row per material",
    successSchema: GetConstructionProcurementStockRegisterResponseModel,
    errors: READ,
  },
  {
    method: "get",
    path: `${INVENTORY_PATH}/register/export`,
    summary: `The Stock Register as .xlsx (${MENU}, report)`,
    tags: TAGS,
    query: GetConstructionProcurementStockRegisterRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "An .xlsx file",
    successBinaryContentTypes: [XLSX_CONTENT_TYPE],
    errors: READ,
  },
  {
    method: "post",
    path: `${INVENTORY_PATH}/settings`,
    summary: `Estimated Qty, minimum-stock override and alert toggle of one material at a location (${MENU}, update)`,
    tags: TAGS,
    body: UpdateConstructionProcurementStockSettingsRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "The material's stock row",
    successSchema: ConstructionProcurementInventoryRowResponseModel,
    errors: WRITE,
  },
  {
    method: "post",
    path: `${INVENTORY_PATH}/movements`,
    summary: `Consume or Missing Material, one or many lines; STOCK_INSUFFICIENT 409 when stock would go below zero on any later date (${MENU}, create)`,
    tags: TAGS,
    body: RecordConstructionProcurementStockMovementsRequestModel,
    successStatus: StatusCodes.CREATED,
    successDescription: "The entries",
    successSchema: RecordConstructionProcurementStockMovementsResponseModel,
    errors: WRITE,
  },
  {
    method: "post",
    path: `${INVENTORY_PATH}/adjustments`,
    summary: `Adjust stock: counted quantity and reason; the difference posts as an Adjustment (ADJUSTMENT_NO_CHANGE 400; ${MENU}, update)`,
    tags: TAGS,
    body: AdjustConstructionProcurementStockRequestModel,
    successStatus: StatusCodes.CREATED,
    successDescription: "The adjustment",
    successSchema: ConstructionProcurementStockMovementResponseModel,
    errors: WRITE,
  },
  {
    method: "post",
    path: `${INVENTORY_PATH}/movements/{id}/update`,
    summary: `Edit a Consumed, Missing or Opening entry: reversal and repost (STOCK_MOVEMENT_CHANGED, STOCK_MOVEMENT_NOT_EDITABLE, STOCK_INSUFFICIENT 409; ${MENU}, update)`,
    tags: TAGS,
    params: ConstructionProcurementStockMovementParamsModel,
    body: EditConstructionProcurementStockMovementRequestModel,
    successStatus: StatusCodes.OK,
    successDescription: "The entry",
    successSchema: ConstructionProcurementStockMovementResponseModel,
    errors: WRITE,
  },
  {
    method: "post",
    path: `${INVENTORY_PATH}/movements/{id}/delete`,
    summary: `Delete a hand-entered stock entry: tombstone and reversal (STOCK_INSUFFICIENT 409; ${MENU}, delete)`,
    tags: TAGS,
    params: ConstructionProcurementStockMovementParamsModel,
    body: DeleteConstructionProcurementStockMovementRequestModel,
    successStatus: StatusCodes.NO_CONTENT,
    successDescription: "Deleted",
    errors: WRITE,
  },
];
